### ISSUE TITLE
Automatic Docker interception

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#1]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by daluu** [comment]
This is about automatically capturing/proxying traffic that goes in/out of docker containers that are running on the local system where httptoolkit is running?

If so, relating to this, in the interim, might be good to document how one might do this manually to get things working while waiting for this feature.

**Comment by pimterry** [comment]
> This is about automatically capturing/proxying traffic that goes in/out of docker containers that are running on the local system where httptoolkit is running?

Yep, exactly

> If so, relating to this, in the interim, might be good to document how one might do this manually to get things working while waiting for this feature.

Good idea! The general steps are:

* Configure your container to use the proxy. For many cases you may be able to just set `HTTP_PROXY=172.17.0.1` as an env var (that's the default ip for the Docker host from inside a container). Some clients will need manual configuration though.
* Configure your app to trust the certificate for HTTPS. To do this, you'll need to copy the certificate from your machine into the docker container. The path on your host machine is shown in the 'Anything' option in HTTP Toolkit. The steps to trust the certificate vary significantly between clients, but setting these environment variables to the path to the certificate inside your container will work for quite a few cases:
	* `SSL_CERT_FILE` - many OpenSSL-based tools
	* `NODE_EXTRA_CA_CERTS` - Node.js
	* `REQUESTS_CA_BUNDLE` - Python's Requests module

That's not perfect - once it's automated it will be much easier - but that might help anybody interested in this get started.

**Comment by pimterry** [comment]
Automatic Docker interception is now just a couple of weeks away. I need testers! Who wants early access in return for feedback?

If you're interested, send me your email via http://httptoolkit.tech/contact/ and I'll set you up.
