### ISSUE TITLE
Option to save response JSON to disk if it passes a rule

### ISSUE THREAD

**Issue by rsivapr** [httptoolkit/httptoolkit#107]
It would be amazing to have an option to save response body to disk. I can see this being used for setting up automation. For instance, every time I play a song, I can setup a python script to record the names in a spreadsheet. 

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by rsivapr** [comment]
I'm new to HTTP Toolkit, so I'd be more than happy if someone were to tell me this can be hacked together somehow already.

**Comment by pimterry** [comment]
Great suggestion, thanks @rsivapr!

I'm open to this, but I think it's most likely to be implemented as part of #37 - if you could write your own scripts for proxy behaviour within the app, then those scripts could easily save content to a file, or anything else you'd like. Would that work for you?

I'll keep this issue open anyway - if it does turn out to be a popular request, it might well make sense to have as a rule in its own right.

In the meantime, right now you can probably do this at a lower level by using [Mockttp](github.com/httptoolkit/mockttp) directly. That's the internals of HTTP Toolkit as a standalone JS lib, and you can use it to start a proxy, define rules including callbacks with any logic you like, and build automation on top. It doesn't have the UI or the automated interception setup, but if you're capturing content from just a single client then you can probably simple automation work by manually configuring your client to use your Mockttp server as its proxy server.

**Comment by rsivapr** [comment]
Awesome! #37 will definitely work for me. My guess is, this might be a simpler implementation (since I assume this'll be offloading the code execution step to some scheduler). But since that issue has upvotes (I added mine), I'm happy to close this out.
