### ISSUE TITLE
How skip HTTPS interception for some hosts

### ISSUE THREAD

**Issue by intari** [httptoolkit/httptoolkit#108]
Android app.
It's rather diffucult (and not necessary for my purposes) to add HTTP Toolkit's certificate as trusted (some libraries have their own settings for this, because...security).
Traffic to development servers is in http anyway.
How to make HTTP Toolkit forget about https at all?

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hmmm, that's an interesting problem! Right now no, there's no specific built-in support for not intercepting HTTPS in the desktop app, and it'd be a little fiddly to implement. The existing rules system matches requests only after they're received, so it doesn't have any way to match or interact with TLS connections before HTTPS interception starts, as you'd need.

It is possible, it's just it would need to be part of some separate configuration system somewhere.

Have you tried the new option in the Android client to filter interception to just specific apps? Does that help at all? If your development app is sending everything in plain HTTP and the HTTPS is coming from elsewhere then that should work for you, by ensuring that everything except your app skips the VPN (and therefore the HTTPS interception) entirely.

Alternatively, if it's all in the same app, you can probably make this work by not using the HTTP Toolkit Android client to setup interception, and instead manually configuring the proxy settings for your HTTP requests yourself, just for the traffic that you're interested in.

**Comment by intari** [comment]
I can't find this option.
Also, it will not help.
App  itself have 3rd party security libs which communicated with their own servers for security purposes  and disabling all of this is problematic. (production version of app works with customers money and it's it main purpose. so a lot of integrated security libs which doesn't get disabled in debug).
What about passing through https on client (without replacing certificates)?

**Comment by pimterry** [comment]
> I can't find this option.

When you're connected to the proxy, in the latest version of the app, there's a "Intercepting all/N apps" button below the certificate status. Like so: https://twitter.com/HttpToolkit/status/1310611093576912901.

If you can't see that then you might have an older version of the app - to update, you either need the Play Store available on your device, and you can update it there like any other app, or on rooted devices & emulators etc you can just uninstall the app, and HTTP Toolkit on your computer will install the latest version for you next time you activate the device via ADB. Doesn't matter much if that won't work for you though, just fyi.

> App itself have 3rd party security libs which communicated with their own servers for security purposes and disabling all of this is problematic. (production version of app works with customers money and it's it main purpose. so a lot of integrated security libs which doesn't get disabled in debug).

Ok, that makes perfect sense. Right now I can see two main options:

1. Don't use the app, and manually configure your device to use the proxy in Android's settings, but excluding the domains used by your security libraries from that configuration. To do this:
    * Edit the settings for your wifi network
    * Open 'advanced options'
    * Scroll down to the proxy settings
    * Enter your computer's ip & HTTP Toolkit port (probably 8000)
    * Add the domains you want to skip intercepting to the bypass list:
![Screenshot from 2020-10-19 19-28-39](https://user-images.githubusercontent.com/1526883/96490831-a37d3c80-1241-11eb-9997-07cb1719a7af.png)

2. Change the code that talks to your development servers (i.e. not your security code) and configure just that code to use your HTTP Toolkit computer as a proxy server. E.g. with OkHTTP that requires something like:

    ```java
    OkHttpClient client = new OkHttpClient().proxy(
      new Proxy(Proxy.Type.HTTP,
        new InetSocketAddress("10.0.0.1", 8000) // Your HTTP Toolkit computer's address
      )
    )
    // Use client as normal
    ```

Do either of those options work for you?

**Comment by pimterry** [comment]
Hi @intari did you try the above? Does one of those options work for you?

**Comment by intari** [comment]
2nd one works.

пн, 2 нояб. 2020 г., 17:28 Tim Perry <notifications@github.com>:

**Comment by pimterry** [comment]
Great! Thanks for letting me know. I'm going to close this for now, but feel free to get in touch if you have any other issues.

**Comment by pimterry** [comment]
I've had another request for this, so I'm going to reopen it as a pending feature request for now. In the meantime, there's some Android workarounds above.

**Comment by lord-ne** [comment]
> Don't use the app, and manually configure your device to use the proxy in Android's settings, but excluding the domains used by your security libraries from that configuration.

If I potentially wanted to try adding support to the HTTPToolkit-android app for ignoring certain domains, how would I go about doing that? I've taken a look at the source code but I'm a little bit lost, my best guess is it would go somewhere in the ProxyVPNRunnable or ProxyVPNService class.

**Comment by pimterry** [comment]
@lord-ne, good enthusiasm! I'd like to get this fixed too, and I've actually been looking into it myself recently - I think although it might be possible to configure this on the Android end, as you've discovered it's very complicated, and I think it's going to be better to support this on the desktop side instead.

Effectively we'd capture the packets in the desktop app there, derive the correct domain from SNI in the TLS handshake (or the CONNECT request, if there is one) and then blindly forward that TLS upstream instead of intercepting it if the domain matched the user's configuration. This has the advantage that it'll work for Android and also all other HTTP Toolkit clients in exactly the same way.

I've been working on manually parsing the handshake to support that here: https://github.com/httptoolkit/read-tls-client-hello. There's still a little work left here, but it should be usable soon!

The first step to support that will be landing in Mockttp (the internal HTTP-handling proxy library) hopefully some time this week. That's tracked over here: https://github.com/httptoolkit/mockttp/issues/68.

**Comment by pimterry** [comment]
This is now live! The option is available in the Pro settings, and the resulting tunnels show up in the normal list, like so:

![Screenshot from 2022-11-07 19-16-35](https://user-images.githubusercontent.com/1526883/200396148-65c6c51b-abd3-4002-8d7e-bc6d1b7a7a6f.png)

![Screenshot from 2022-11-07 19-52-44](https://user-images.githubusercontent.com/1526883/200396169-79350559-e55b-4385-8c0d-0b4b571d28be.png)
