### ISSUE TITLE
Big Sur CPU panic

### ISSUE THREAD

**Issue by askl56** [httptoolkit/httptoolkit#109]
Hey,

Each time i start recording on HTTP Toolkit I get a kernel panic about 30s later on Big Sur. Its the only time I get them. 

Relevant part of log below:
```
panic(cpu 0 caller 0xffffff80166b8681): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.40.137.201.1/bsd/net/content_filter.c, line: 1089
Backtrace (CPU 0), Frame : Return Address
0xffffffa14ad538b0 : 0xffffff8015eb666d 
0xffffffa14ad53900 : 0xffffff8015ff8f93 
0xffffffa14ad53940 : 0xffffff8015fe95ca 
0xffffffa14ad53990 : 0xffffff8015e5ba2f 
0xffffffa14ad539b0 : 0xffffff8015eb5f0d 
0xffffffa14ad53ad0 : 0xffffff8015eb61f8 
0xffffffa14ad53b40 : 0xffffff80166b792a 
0xffffffa14ad53bb0 : 0xffffff80166b8681 
0xffffffa14ad53bc0 : 0xffffff80162a7d0e 
0xffffffa14ad53c00 : 0xffffff80162ab38a 
0xffffffa14ad53c50 : 0xffffff80162aca28 
0xffffffa14ad53ce0 : 0xffffff80164a2c11 
0xffffffa14ad53e00 : 0xffffff80164774e8 
0xffffffa14ad53e30 : 0xffffff8016471e55 
0xffffffa14ad53ee0 : 0xffffff8016471c67 
0xffffffa14ad53f40 : 0xffffff8016563d0b 
0xffffffa14ad53fa0 : 0xffffff8015e5c1f6 

Process name corresponding to current thread: node
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20A5395g
```

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Wow, ok! That's very bad, I have no idea why that would happen.

Are you low on disk space or memory? Anything else unusual about this machine? I can think of reasons why HTTP Toolkit itself might crash in certain conditions, but I'm not aware of any way that it could cause a kernel panic.

**Comment by askl56** [comment]
Nope neither. New 16 inch mbp. In terms of apps that may interact with HTTP Toolkit, I have Little Snitch firewall and use ExpressVPN but they both work fine individually.

**Comment by pimterry** [comment]
@askl56 can you try using HTTP Toolkit with Little Snitch disabled? There's [reports](https://www.reddit.com/r/MacOSBeta/comments/i4hcz2/frequent_kernel_panics_on_all_big_sur_betas/g0ny3uk/) of Little Snitch causing kernel panic's with Big Sur, and that's mentioned as a known issue for some combations of beta versions in Little Snitch's [own docs](https://www.obdev.at/support/littlesnitch/245908328454673) too.

Are you using the latest Big Sur release & Little Snitch update?

As far as I can tell from quick googling, a [common culprit](https://developer.apple.com/forums/thread/659877) of kernel panics is the new Network Extensions framework, which is still quite crashy in the latest MacOS. Little Snitch uses this framework (some background from their team here: https://blog.obdev.at/little-snitch-and-the-deprecation-of-kernel-extensions/) whilst HTTP Toolkit does not (it doesn't have any non-trivial interactions with the kernel at all - it's just a user-level HTTP proxy). I don't know the details, but I could imagine that Little Snitch activates some code paths which then get heavily tested once HTTP Toolkit begins handling lots of traffic via the extension that Little Snitch is managing.

To be clear, even if it is the cause, I strongly suspect the Little Snitch team aren't at fault here at all either - Apple should really ship APIs that don't kernel panic in normal use! If disabling Little Snitch and/or ExpressVPN does help then do let me know, and I'll get in touch with those developers to see if we can work together on this at all.

**Comment by pimterry** [comment]
@askl56 did you ever work out what the issue was here?
