### ISSUE TITLE
Dropping requests to simulate connection errors

### ISSUE THREAD

**Issue by pieterdd** [httptoolkit/httptoolkit#111]
Hi! I would like to emulate a scenario where an in-browser API call fails due to a connection error (e.g. user is offline, server dropped the request). Does HTTP Toolkit have a way to simulate connection errors?

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Yes, absolutely! Pro users can do so with mock rules, to automatically match and explicitly kill connections before any content is sent (responding with a hard TCP connection close and no data) or to simply drop them so they time out (i.e. never send any data at all and ignore the request). They're at the bottom of the list of mock rule actions:

![Screenshot from 2020-11-13 09-47-07](https://user-images.githubusercontent.com/1526883/99048030-52890b80-2595-11eb-851f-c6b3f8b714c1.png)

Does that work for your use case?

**Comment by pieterdd** [comment]
Ah indeed, I overlooked it here since it was under the Pro-only features... That covers my use case, thanks!
