### ISSUE TITLE
User installed CA on Android can cause lockup and Play Store issues

### ISSUE THREAD

**Issue by CeruleanSky** [httptoolkit/httptoolkit#112]
I have not figured out the exact scenario but I was testing http toolkit on Android 10(QQ2a.200501.001.B2 the May 2020 update) through the adb root method, but I decided to hit disconnect and then use the QR method to see what it was like.  

After accepting the certificate it worked fine.  

I rebooted later and android gave me a security warning about certificates and the play store no longer worked, and the settings app among others would not open blank screen. 

 Eventually a watchdog rebooted the OS, and afterwards it was stuck on the boot animation, so I held power and after shutting down I rebooted again. The device powered up and I was able to access Settings->Security->Encryption & Credentials ->Trusted Credentials->User and remove the certificate just as the security warning appeared. It then disappeared after the certificate was removed and I was then able to use the phone as normal again.

I do not understand why the problems occurred, and perhaps it is an OS bug but retaining the user credentials may in rare circumstances cause issues and lockups on the OS.

I figured it was best to document things in case anybody else had a similar issue.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Huh, that's very unusual. What device was this, and how exactly was it rooted?

HTTP Toolkit doesn't do anything special for user certificate setup, it's just using the standard Android APIs like everybody else, so it's very surprising if that can break the Play Store and the device settings (in fact if you can reproduce serious breakage like this without using adb at all then you can probably claim an Android bug bounty from Google).

Have you managed to reproduce this any more than once? I've never seen this but I'd be extremely interested to hear more about it, especially any reliable steps so I can reproduce it myself.
