### ISSUE TITLE
I want to get https of tiktok app

### ISSUE THREAD

**Issue by datphuot** [httptoolkit/httptoolkit#114]
I want to get https of tiktok application, I am willing to pay extra cost. Thanks!

**Comment by pimterry** [comment]
Hi @datphuot. That's going to be tricky I think. I'm not 100% sure, but I suspect tiktok's traffic uses certificate pinning, so there'll be some reverse engineering and APK manipulation required.

This isn't really a product feedback question, so I'm going to close this issue, but if you want to talk about it you can send me an email at tim @ httptoolkit.tech to talk about this. If you let me know what you're trying to do and why, I'll see if I can give you some pointers in the right general direction.
