### ISSUE TITLE
iOS would be great

### ISSUE THREAD

**Issue by tmvnk** [httptoolkit/httptoolkit#123]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I totally agree! It's absolutely on the list, eventually (and contributions are very welcome in the meantime, if you're especially keen!)

Unfortunately however this is a duplicated of #11, so I'm going to close it for now. Feel free to :+1: and subscribe to that issue instead though.
