### ISSUE TITLE
Unable to connect to a real device

### ISSUE THREAD

**Issue by akinsolb** [httptoolkit/httptoolkit#124]
I have tried to connect to a number pf physical devices using a cable and over wifi (on the same network as desktop) but after scanning the QR code, or selecting to connect over adb, I see the connecting screen followed by the screen that states 'Oh no! We couldn't connect to HTTP Toolkit. Is it running, and connected to the same network as this device?'

I have tried on android 9, 10 & 11

However, it does connect successfully to an emulator.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Interesting, that's very unusual, sorry to hear that.

Can you run `adb logcat`, and share the logs from the device that cover the period where it tries to set up & fails?

**Comment by akinsolb** [comment]
@pimterry Here's a gist of the connected device. It'll take me a moment to get logcat of the device over wifi
https://gist.github.com/akinsolb/4eec966e933a69210b2bdc672fe4e7ab

**Comment by akinsolb** [comment]
and here is a gist of a failed connection over adb wifi  https://gist.github.com/akinsolb/619b0675cb8b04cffc29dc81ec61fcf6

**Comment by pimterry** [comment]
Thanks @akinsolb. It looks like your computer IP is `192.168.1.72` on the local network, and your HTTP Toolkit is running on port 8000 (should be shown on the 'Anything' interception option). Is that right?

Both of those logs show the device failing to connect to that IP & port:

> 2021-02-14 12:57:42.929 17399-17452/? I/tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 192.168.1.72: java.net.SocketTimeoutException: failed to connect to /192.168.1.72 (port 8000) from /192.168.1.180 (port 60026) after 2000ms

> 2021-02-14 13:06:43.164 10742-26221/? I/tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 192.168.1.72: java.net.SocketTimeoutException: failed to connect to /192.168.1.72 (port 8000) from /192.168.1.76 (port 52804) after 2000ms

This is the first step in the connection setup: the device connects to HTTP Toolkit on your computer to check it's available and pull the detailed connection settings. For some reason that's failing.

Can you test that the device can connect otherwise? If you try using https://play.google.com/store/apps/details?id=com.simplesockettester&hl=en&gl=US for example, can you connect to port 8000 on your computer from your phone with that app?

What OS are you running on your computer? Do you have a firewall or similar that might be blocking connections from your phone to HTTP Toolkit?

**Comment by akinsolb** [comment]
Yes, that's correct. Port 8000, and my local machine is .72

**Comment by pimterry** [comment]
Thanks for confirming that @akinsolb. Did you see the questions at the bottom of the message too? I'm happy to investigate further, if there's anything more you can tell me about connectivity between your device & computer.

**Comment by akinsolb** [comment]
Sorry I only saw the first couple of lines. I'm running on Windows Pro. 

The machine does have antivirus installed so I'll double check that and get back to you tomorrow

**Comment by pimterry** [comment]
Ok, great. It would also be sensible to check firewalls, including the built-in Windows Defender Firewall. There will have been a firewall prompt when you first started HTTP Toolkit. If you used the defaults that should be fine, but if you unticked HTTP Toolkit's access to the network then that would cause this.

You can check that in the Windows settings: Control Panel -> System & Security -> Windows Defender Firewall -> Allowed Apps. It'll be in there as node.exe. It needs to be allowed to pass the firewall at least on private networks (and public, if you're trying this on a network that Windows deems public, I'm not sure how it makes that decision). This is the setting that allows incoming access to the HTTP Toolkit proxy from other devices, like your phone.

You can confirm whether it's working by testing the connection from any machine or device on the network. If your firewalls are set up correctly, they should be able to connect to port 8000 on your machine.

**Comment by akinsolb** [comment]
So, as suspected, I have a firewall blocking it. I didn't get the notification as described, but I can see from the event logs that McAfee blocks the request. Thank you for your help

**Comment by pimterry** [comment]
Great to hear! Thanks for letting me know. I'll look into improving the error message in the app, and see if I can make that possibility clearer.
