### ISSUE TITLE
It does not connect via adb

### ISSUE THREAD

**Issue by ZZolotov** [httptoolkit/httptoolkit#129]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @ZZolotov, can you provide more details please? A couple of useful things:

* What phone & OS version are you using?
* Do you see an error on the phone? What does it say?
* Can you run `adb logcat` on your computer, and share the logs around the time when the connection fails?
* What's the network setup between your phone and your computer? Do you have a firewall on your computer that might block incoming connections?

**Comment by pimterry** [comment]
I'm going to close this for now. Feel free to reply with more details in future if you're still having issues though and I'll reopen & investigate further.
