### ISSUE TITLE
Startup failed: "Server XHR error during getVersion, status 403 Forbidden

### ISSUE THREAD

**Issue by eeiee** [httptoolkit/httptoolkit#131]
**environment:**
mac:10.15.2
chrome: 89.0.4389.90 (x86_64)

**occurrence**:
when httptoolkit-desktop start, the index show error:Startup failed: "Server XHR error during getVersion, status 403 Forbidden

**message**:

index.js:3592 POST http://127.0.0.1:45457/ 403 (Forbidden)
(anonymous)	@	index.js:3592
(anonymous)	@	server-api.ts:39
a	@	collapsible-section.tsx:252
Promise.then (async)		
c	@	collapsible-section.tsx:252
(anonymous)	@	collapsible-section.tsx:252
s	@	collapsible-section.tsx:252
l	@	server-api.ts:38
(anonymous)	@	server-api.ts:95
(anonymous)	@	collapsible-section.tsx:252
s	@	collapsible-section.tsx:252
p	@	app.js:3363
Promise.then (async)		
(anonymous)	@	service-versions.ts:20
Promise.then (async)		
c	@	observable.ts:54
10	@	service-versions.ts:18
a	@	bootstrap:84
16	@	errors.ts:1
a	@	bootstrap:84
1369	@	app.js:7
a	@	bootstrap:84
629	@	app.js:3363
a	@	bootstrap:84
n	@	bootstrap:45
(anonymous)	@	bootstrap:221
(anonymous)	@	app.js:1

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hmm, that's very unusual, thanks for letting me know.

Has HTTP Toolkit worked for you in the past? Did it crash recently?

If you quite HTTP Toolkit completely, and then look at the macOS activity monitor, do you have a `node` process running unexpectedly? It's possible that this could be caused by a leftover background server process like that.

**Comment by pimterry** [comment]
Hi @eeiee is there anything more you can tell me about this issue? Are you still seeing the same error? I'd love to get this fixed for you!
