### ISSUE TITLE
select all requests and copy url

### ISSUE THREAD

**Issue by nutterthanos** [httptoolkit/httptoolkit#134]
How do you select all requests and copy url for all requests?
also think this is a feature request but don't know if i can already do it so i didn't mark it in the title.

**Comment by pimterry** [comment]
You can't directly copy just all the URLs, but with [HTTP Toolkit Pro](https://httptoolkit.tech/get-pro/) you can export all requests as a [HAR](https://en.wikipedia.org/wiki/HAR_(file_format)) file. HAR files contain all the request & response data. They can be imported and used in many other tools, and internally they're just simple JSON, so you can extract all the request URLs yourself very easily.

Using jq for example, you can get all request URLs with `cat your-har-file.har | jq '.log.entries[].request.url'`. If you're not familiar with jq, you can do the same in a couple of lines with any tool that can parse JSON.

**Comment by DavraYoung** [comment]
https://gist.github.com/DavraYoung/dc49ded10533aee24383179a3a2a06a0

I have created a gist that will allow to do that using the devtools console. 
Just paste this in console and it will export you a json
