### ISSUE TITLE
support proxy cascade

### ISSUE THREAD

**Issue by intari** [httptoolkit/httptoolkit#135]
Let's say my mobile app needs to access xxx.yyy.com and xxx2.yyy.com via proxy or via specialized VPN client.
It's not ok to configure proxy system-wide so .pac-file was created and configured in system's proxy settings (Edge uses it, Chrome doesn't for some reason).
httptoolkit ignores .PAC file.
Is it possible to make httptoolkit at least proxy requests for specific sites to another proxy (while retaining all other functions)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
This is now supported (see lots more discussion in #117). For all users, the system proxy settings will be used by default. Pro users can configure settings for HTTP Toolkit specifically on the Pro settings page. Thanks for reporting this!
