### ISSUE TITLE
1

### ISSUE THREAD

**Issue by liangyueen** [httptoolkit/httptoolkit#136]
1

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @liangyueen, it looks like something's gone wrong here. Are you having some kind of issue? If you can post details I'm happy to help.
