### ISSUE TITLE
Http Toolkit is throwing Server crashed with 'Error: read ENOTCONN

### ISSUE THREAD

**Issue by jsanzmex** [httptoolkit/httptoolkit#137]
HttpToolkit is not working lately :/

It is throwing this error most of time:

**Server crashed with 'Error: read ENOTCONN' (1).**

What can I do? I'm a paid user

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I see, thanks for reporting this. It's likely to be linked to a specific oddly behaving client or host, which is unexpectedly closing a connection at some moment when HTTP Toolkit isn't currently expecting it.

What traffic are you intercepting when this happens? Is this something you can reproduce reliably? If you can find out what triggers this so I can reproduce it myself then I should be able to hunt down the edge cases that are not being caught and fix it very quickly.

**Comment by pimterry** [comment]
Hi @jsanzmex anything more you can tell me about this issue? I'm happy to look into it, and it's quite possible I can get a permanent fix for you within a couple of days, I just need a little more information so I can reproduce the crashes for myself first.

**Comment by jsanzmex** [comment]
Hi Tim
Sorry for the long wait!
All I did was restart my Macbook, and my ADSL modem. That made it work again :)

**Comment by pimterry** [comment]
Huh, weird. No idea what would cause that then! Good to hear it's working nicely for you though, do let me know if you have any more issues in future.
