### ISSUE TITLE
if i reload the app with CTRL + R. all the requests disappear

### ISSUE THREAD

**Issue by nutterthanos** [httptoolkit/httptoolkit#140]
When I want to reload the app with CTRL + R what happens is all my requests will disappear and there is no way to get those requests back

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Yes, it does, that's kind of the idea! Reloading the app reloads all the data in the app.

I suppose there could be a warning here, that would be easy enough. Is this something you're triggering accidentally? Was there some reason you wanted to reload the app like this without losing your data?

If you want to persist data in general, there are Pro import & export features, to save all data to disk as a HAR file. You can use that to store & examine the same data later, for longer-term comparisons or analysis, and to share collected requests with other users.

**Comment by nutterthanos** [comment]
Well ok I just hope the memory from the requests gets removed as in unused 
As in I hope there is no memory leak

**Comment by pimterry** [comment]
Yes, all requests held in memory will be completely removed as soon as you click the 'Clear all requests' button at the bottom of the request list. You can reload the app too if you'd prefer of course (which will completely drop and reset _all_ UI memory) but that's not normally necessary. There can be small delays in all memory being released, but after clearing all requests the overall memory usage should return to something close to memory usage shortly after startup within 30 seconds or so.

If you're interested in the internals behind this, you can see how that works here:

https://github.com/httptoolkit/httptoolkit-ui/blob/3a42691d2bda922fdc93457acf20332b232529d1/src/model/http/events-store.ts#L296-L312

We remove all unpinned data completely from the event store, cleanup after everything, and then explicitly trigger the garbage collector to immediately reclaim everything.

If you are seeing a memory leak, where HTTP Toolkit uses many times more memory than it does at startup even though all requests have been cleared, then I'd be very interested to know about it. Is that happening? If you can send me details to reproduce that I'll look into it.

**Comment by nutterthanos** [comment]
nope no memory leaks here
