### ISSUE TITLE
tom@machinefloor.com <tom@machinefloor.com>;

### ISSUE THREAD

**Issue by nuisystem** [httptoolkit/httptoolkit#142]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by nuisystem** [comment]
+😀 #137 👍

**Comment by pimterry** [comment]
I'm a bit confused by this issue...

Are you having the same problem as #137? I'm happy to look into this and fix it, I just need more info about what triggers it so I can reproduce it.
