### ISSUE TITLE
http://localhost:8000

### ISSUE THREAD

**Issue by nuisystem** [httptoolkit/httptoolkit#144]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @nuisystem it seems there's some confusion here. This is a public issue tracker for reporting bugs & feedback. Are you having some kind of issues? Feel free to let me know here or email me at tim@httptoolkit.tech.

**Comment by pimterry** [comment]
I'm going to close this now - I'm happy to help, just let me know what issues you're having (if any).
