### ISSUE TITLE
Android Device Connected Via ADB is "Not Available"

### ISSUE THREAD

**Issue by khag7** [httptoolkit/httptoolkit#145]
I am trying to connect to an emulator running on the same PC that HTTP Toolkit is installed. I am using Bluestacks. I have no trouble ADB-ing to the emulator from command line. I don't have the option to use ADB in HTTP Toolkit. At first I thought it was a premium feature, so I paid for premium, but it still isn't available. Am I overlooking something?

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by khag7** [comment]
I tried using Android Studio's emulator and it worked fine. I guess its a Bluestacks issue.

**Comment by pimterry** [comment]
Thanks for the report @khag7! Sorry to hear you had issues with Bluestacks, I'll look into that and see if there's anything I can do to make the integration work there.

**Comment by khag7** [comment]
Thanks for following up. Yeah I'm not sure if it was something I was doing wrong or if it's a BlueStacks thing. One thing I noticed was BlueStacks used a different port for ADB. Regardless, I got things working better with Android studio. Thanks again

**Comment by pimterry** [comment]
> BlueStacks used a different port for ADB

Ah yes, that'll do it! HTTP Toolkit just checks the default port (5037), and then attempts to start adb from scratch if it's not already running there. It's not currently possible to configure the port in the UI, but as a workaround you can start HTTP Toolkit with the `ANDROID_ADB_SERVER_PORT` env var set, which will override the default ADB port. Or of course if you're happy with Android studio then that's all good too :smiley:

**Comment by pimterry** [comment]
Hi @TiagoXavi. HTTP Toolkit won't automatically load a `.env` file - you need to actually set it as an environment variable, in whatever environment launches HTTP Toolkit. How you do that depends on your system: on Windows you can do so in the system settings, on Linux you can do so by adding a line to your `.bashrc` or similar, etc.

Or you can just open a terminal, set the environment variable in that window (e.g. `export X=Y` in Bash) and then launch HTTP Toolkit from there.
