### ISSUE TITLE
Bug in script to start listening from existing terminal in Linux

### ISSUE THREAD

**Issue by toochevere** [httptoolkit/httptoolkit#148]
The script that hijacks a terminal to redirect to HttpToolkit has a bug that results in a bash error.

This line
`export NODE_OPTIONS="$NODE_OPTIONS --require "/opt/HTTP Toolkit/resources/httptoolkit-server/overrides/js/prepend-node.js""`
... is missing escaped quotes.  It should be: 
`export NODE_OPTIONS="$NODE_OPTIONS --require \"/opt/HTTP Toolkit/resources/httptoolkit-server/overrides/js/prepend-node.js\""`

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Ah, good catch! I'd missed this, since those quotes are only included when there's a space in the JS path.

Sorry about that, thanks for reporting this. I'll get a bug fix released ASAP.

**Comment by pimterry** [comment]
This is now [fixed](https://github.com/httptoolkit/httptoolkit-server/commit/4a18c888647d9dcc5920349f280dd57dd5bff326) and the new release is live. HTTP Toolkit will update in the background next time you use it, so the following time this should work correctly.

Thanks again for the report! Do let me know if you run into any other issues at all.
