### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by krishnaraj** [httptoolkit/httptoolkit#153]
Hi,

On Ubuntu ~~20.10~~ 21.04, launched a "Fresh Terminal" from httptoolkit and ran a simple nodejs program that uses 'unirest' to make some rest api calls (https)  but unfortunately nothing is being captured. It works fine on a Mac though. Are there any logs that I can attach to provide more information?

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @krishnaraj, thanks for reporting this.

Which terminal and nodejs version are you using?

HTTP Toolkit intercepts nodejs in terminals by starting the terminal on your machine with the `NODE_OPTIONS` env var set, to pass `--require <http toolkit script.js>` to node processes when they're launched, and that script then hooks a variety of APIs before the rest of the code runs, to ensure the proxy is used everywhere automatically.

Is `$NODE_OPTIONS` set inside your intercepted terminal?

**Comment by krishnaraj** [comment]
Hi @pimterry ,

I am using fish-shell and node version 12.21.0. 

After launching "Fresh Terminal" when I check `which node` it does point to `/opt/HTTP Toolkit/resources/httptoolkit-server/overrides/path/node`. Also even when executing `curl "google.com"` or `wget "google.com"` nothing is captured.

**Comment by pimterry** [comment]
Huh, that's very interesting. Do you see any kind of "Connection aborted" or "Certificate rejected" messages in HTTP Toolkit, or absolutely nothing at all? If the former, it's a certificate problem, if the latter than the proxy settings aren't being detect at all.

Either way this suggests some other env vars are missing I think. The full list is here: https://github.com/httptoolkit/httptoolkit-server/blob/92d705eb3d7a4c89a81e20c60ad81454c6ca0b8a/src/interceptors/terminal/terminal-env-overrides.ts#L36-L101

I think all that's required for curl is one of the HTTP_PROXY variables and SSL_CERT_FILE. Are those set in your environment? You can try `curl -v google.com` which should print more info, like so:

```
> curl -v google.com                   
* Uses proxy env variable http_proxy == 'http://127.0.0.1:8000'
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET http://google.com/ HTTP/1.1
> Host: google.com
> User-Agent: curl/7.68.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
...
```

**Comment by krishnaraj** [comment]
Yes, the proxy settings aren't detected, in fact `$http_proxy` is empty too. I'll dig a bit deeper and update.

**Comment by krishnaraj** [comment]
This is indeed an issue with how my shell starts. My terminal program starts "tmux" instead of "bash" and the proxy environment variables are not being set. It works fine if I use "bash".

**Comment by pimterry** [comment]
Is your tmux attaching to an already running shell? If so then this is expected (we can't change env vars on a running shell) but if not and tmux is spawning a shell when you start it, then it should work fine.

**Comment by krishnaraj** [comment]
Terminal is configured execute a custom command instead of default shell like below
![image](https://user-images.githubusercontent.com/141018/127742644-eed90650-1cf5-49ea-ba62-fc22419e791b.png)

and in my .tmux.conf I have `set-option -g default-shell /usr/bin/fish`
