### ISSUE TITLE
Certificate is installed and root access is requested and granted but System Trust is still disabled

### ISSUE THREAD

**Issue by ZeroPie** [httptoolkit/httptoolkit#154]
Certificate is installed and root access is requested and granted but System Trust is still disabled
Rooted OnePlus 3T
Running adb shell and then su root whoami //root
Running adb shell and then su -c whoami //root
Running adb root, then adb shell and then whoami //root

Tried Frieda and it works, but i cannot get httpToolkit to work

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hmm, that's unusual I'm not sure what's going on there.

How was the device rooted?

If you launch HTTP Toolkit from a command line, does it show any errors there during ADB setup?

**Comment by pimterry** [comment]
More info needed, so I'm going to close this for now, but if you can let me know the answers to the above questions I'm very happy to reopen and investigate further.

**Comment by kaustav07** [comment]
Same problem for me also..Oneplus 3 Rooted and also given root access to adb shell but system trust is disabled
