### ISSUE TITLE
Ability to hide menu bars.

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/httptoolkit#156]
Currently, they are just occupying verticle space like 5px and doing nothing useful at least to me.

Maybe we can add a hide menu bar in settings. Also, add a double alt key feature that toggles them. The double alt concept is used in firefox/vscode.

**Comment by pimterry** [comment]
This is a great idea! I'm not sure I want to hide them by default, but I'm totally open to adding tick-able option in the menu to enable autohiding it.

It looks like Electron has built-in support for this, so it should be easy to do: https://www.electronjs.org/docs/api/browser-window#winsetautohidemenubarhide.

If you're interested and you want to add that yourself, I'd happily accept a PR :smiley:. The electron code is over here: https://github.com/httptoolkit/httptoolkit-desktop/

**Comment by shirshak55** [comment]
@pimterry closing this.

Fixed by https://github.com/httptoolkit/httptoolkit-desktop/pull/28

**Comment by shirshak55** [comment]
@pimterry  Done so closing it.
