### ISSUE TITLE
It works out of the box

### ISSUE THREAD

**Issue by robert-dzikowski** [httptoolkit/httptoolkit#157]
Very good tool for mocking HTTP responses. I needed to test some chart in our web app which uses data that is difficult to generate, so I tried couple of tools that allow to mock HTTPS responses. I tried Fiddler free version, rather old tool and not easy to use. Next I tried Charles Proxy free version, I spent 2 hours on installing certificate and then on fighting with CORS errors, with no success. Finally I tried HTTP Toolkit free version, I installed it and after 10 minutes I was able to do my test. I didn't have to install any certificates, I didn't have to search the internet, I didn't have to read documentation, HTTP Toolkit simply works and is very intuitive.

**Comment by robert-dzikowski** [comment]
This is my review not bug report.

**Comment by pimterry** [comment]
:smile: Amazing! I wish all every issue posted here looked like this. Thanks for the positive feedback, I really appreciate it.

Glad to hear it's all working so well for you, and do feel free to get in touch if you have any problems or questions.
