### ISSUE TITLE
Time out (never respond)

### ISSUE THREAD

**Issue by robert-dzikowski** [httptoolkit/httptoolkit#160]
Hi.
I am using paid version, so my question should get higher priority :)
The mock response option "Time out (never respond)", what real situation it suppose to simulate?

**Comment by pimterry** [comment]
Hi Robert. That option simulates a server that accepts a TCP connection & HTTP(S) request, but never sends any kind of response. This is exactly what might happen with a server that's heavily overloaded, or extremely slow for some other reason (e.g. if the request is a very expensive query, or depends on some other slow connection elsewhere).

You might also see equivalent real-world behaviour in environments with very poor client connections, e.g. very high return packet loss on a mobile connection, such that the HTTP response is never successfully received by the client.

What HTTP Toolkit specifically does here is:
* Accept the TCP connection
* If HTTPS, complete normal HTTPS setup
* Wait for a HTTP request to be received
* If it matches a timeout rule: keep the TCP connection open, but never send any response data.

Notably this is testing application-level timeouts _not_ an initial TCP connect timeout, which might behave slightly differently in some applications. In most cases that won't matter though: either way, your client is waiting for a response indefinitely with no feedback.
