### ISSUE TITLE
Hooking chrome webdevtools?

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/httptoolkit#161]
is it possible to add an interface like chrome web dev tool frontend. If it sounds good I can work on that feature.

**Comment by pimterry** [comment]
I'm not sure exactly what this means... Can you share some more details about how users would use this, how it would work, and the kind of use cases that it would support?

**Comment by shirshak55** [comment]
@pimterry An alternative frontend using devtools so people familiar with devtools can use httptoolkit more effectively. Currently I am learning  how cdp and frontend integration works lets see.

**Comment by pimterry** [comment]
As, so you want to feed the collected data from HTTP Toolkit into the normal devtools UI? Sounds neat! Very interesting idea.

You could make a CDP server that wraps Mockttp and exposes the data to CDP clients, which the devtools can connect to directly... I guess that's what you're looking at already? You can probably already do basic things by just using the HAR export/import, to feed data directly across and analyse it there manually. Sounds difficult but it's an interesting way to expose a different UI and reuse Chrome's existing tooling.

**Comment by shirshak55** [comment]
@pimterry yep cdp is the way to go. I am not choosing HAR export/import even tho its easier because of perf.

**Comment by shirshak55** [comment]
@pimterry 

Ok, can you let me know if you accept it or not. It will look like this.

And yes you are correct we use mockttp and will hook it. 

![image](https://user-images.githubusercontent.com/8097377/141158473-855dfb57-24f3-4f18-b50a-fde0fbd9c465.png)

I will get rid of that initiator etc.

**Comment by pimterry** [comment]
That all makes sense, I see how that could work, definitely sounds possible.

I'm not sure what you mean by whether I'll "accept it"? I don't think this is something that would be integrated into the main HTTP Toolkit app, right? It seems like it's totally separate, it'd basically be a standalone frontend for Mockttp.

I don't object to it at all though, if that's what you mean? If you want to build it, go for it! :+1:

**Comment by shirshak55** [comment]
@pimterry yes in mockttp. Thanks.
