### ISSUE TITLE
Right Click feature?

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/httptoolkit#162]
The current view is a bit scrolly like I find myself scrolling up and down again and again. Maybe we can add right-click feature so that we can display helpful things like a copy as curl without too much hassle?

**Comment by pimterry** [comment]
A quick update on things that should be included when we get to this:

* Delete
* Pin
* Copy URL (by popular request: #134, #170)
* Pro-only:
  * Create mock rule from request (#69)
  * Copy as X (-> submenu with each of our supported export languages)
  * Copy everything as raw HTTP (request + response as raw HTTP, this has been a repeated popular request now)
  * Save as HAR

We might want to add keyboard shortcuts for those of these that don't have any yet too.

More suggestions welcome :smile:

**Comment by pimterry** [comment]
This is now live! All the context menu features listed above are now available by right clicking on requests in the list on the View page.

The new context menu here is HTML-based by default, in all current versions and on the web, but from the next desktop release, the same UI will automatically use native context menus everywhere.
