### ISSUE TITLE
Important features we need

### ISSUE THREAD

**Issue by Theraqa** [httptoolkit/httptoolkit#170]
Add header orders imediently (make it capture headers by correct order and not change order of any of header), also features like CTRL+U to copy selected requst URL, CTRL + X to clean requests, let as us view requests in raw text mode, let us craft our own request and execute it, these modes would be very helpfull, thanks <3

**Comment by pimterry** [comment]
Closing this for now - I think this is covered by #162, #48, #127 and #76
