### ISSUE TITLE
Font size should be resizable

### ISSUE THREAD

**Issue by BenedictP** [httptoolkit/httptoolkit#174]
For me the font size is way to big and I always need to scroll through the response to find the things I need. If I could change the font size would be really awesome!

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
It is possible to zoom the entire UI. Does that work for you? In the app menu: View -> Zoom In/Out.

Also, can you share a screenshot of the UI where the text is clearly way too big, and the details of the platform & device you're using? Screen scaling on some OSs means getting the font size just right everywhere is harder than it sounds.

**Comment by BenedictP** [comment]
Wow. Didn't know that i can resize the whole UI with View -> Zoom In/Out. For me this solution is fine, thanks. I'm someone how usually likes smaller font sizes everywhere ;) So I think it's not a general problem.
