### ISSUE TITLE
Support form urlencoded request/response bodies

### ISSUE THREAD

**Issue by BenedictP** [httptoolkit/httptoolkit#175]
Would be nice to have an option to URL encode a text request/response body in the UI.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Ah, you're talking about decoding bodies like `a=123&b=hello%21`?

I've thought about that before, but I've never been sure what format to decode them into. For example, I could easily transform that query string into pretty-printed JSON and show it like:

```json
{
    "a": 123,
    "b": "hello!"
}
```

But I don't want to confuse anybody into thinking it really is JSON. An easier option would be to decode just the raw characters & then add newlines between params, like:

```
a=123&
b=hello!
```

That helps, but then if you have encoded `&` values, `=` values or newlines inside the content it gets confusing & ambiguous. For example "param=ben%0A%26%0Ajerry%3D123&param2=other", as an extreme case, would become:

```
param=ben
&
jerry=123&
param2=other
```

(In JSON: `{ "param": "ben\n&\njerry=123", "param2": "other" }`)

Very confusing. Any ideas?

**Comment by BenedictP** [comment]
I would prefer the pretty-printed JSON but sometimes I have not a 100% valid JSON. More like some "normal" query params and one of the query param value is a JSON. With https://jsonformatter.curiousconcept.com/ the JSON part is pretty printed but the rest is still there "unformatted" this would be fine I would say.
Currently I use this website: https://dencode.com/en/string to take a look how the "URL Encoding" result looks like.

When this is an option in the dropdown menu besides "Text" and "hex" I think the user shouldn't be confused.

**Comment by pimterry** [comment]
Ok, this is now supported! It's currently read-only (so when editing, this is still shown as raw text) but you can now view clear formatted query parameters in request and response bodies.

In practice, that means that this:

![Screenshot from 2022-02-25 17-38-21](https://user-images.githubusercontent.com/1526883/155752917-c96f89a2-b64e-4862-9373-4e2e4ede7a8b.png)

becomes this:

![Screenshot from 2022-02-25 17-38-07](https://user-images.githubusercontent.com/1526883/155752962-ed4e1cbf-d467-4545-a4a2-a8b9113162a5.png)

(but you can still pick 'Text' from the dropdown to see the raw form, if you want to).

There's more potential improvements here that I'll work on in future, but I suspect this captures 90% of the need for now, so I'm going to close this. Feel free to open new issues if there's specific things that you're looking for from this that aren't yet supported.
