### ISSUE TITLE
No indicator that the request was mocked

### ISSUE THREAD

**Issue by egi-gjevori** [httptoolkit/httptoolkit#176]
Great tool, awesome UI.

My issue is that in case a request was mocked it does not have an indicator just to differ from the other requests. Would be great if the mocked requests had a highlight on them.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Good idea! This data (the id of the rule which handled each request) is actually available internally in the UI for every item already, it's just not shown, so this is easy in theory. Just a matter of working out how to show this.

Any ideas how you'd like this info to appear?

**Comment by shirshak55** [comment]
Or we can use Get (M) M meaning Mocked which should show "Mocked" on hover?

**Comment by roschaefer** [comment]
I agree with @shirshak55: Create an extra column in the table with an indicator.

![image](https://user-images.githubusercontent.com/2110676/159022441-b2aa90ec-5abd-42a6-9c29-776da18da962.png)

**Comment by pimterry** [comment]
This is now live! Enjoy:

![image](https://user-images.githubusercontent.com/1526883/220716345-e140c269-8415-486d-811b-ea3cd0b07a3e.png)

![Screenshot from 2023-02-22 18-56-03](https://user-images.githubusercontent.com/1526883/220715515-6abdb190-c98f-42d7-8110-d5aa5fc326e4.png)
