### ISSUE TITLE
Mocking an existing request does not copy query parameters

### ISSUE THREAD

**Issue by egi-gjevori** [httptoolkit/httptoolkit#178]
For some more explanation:
Clicking on the mock button under an existing request, will not pass the query parameters automatically in the mock data.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by jayesh83** [comment]
+1 needed feature

**Comment by pimterry** [comment]
This is now fixed! There's a new query parameter matcher, which can precisely match individual params within a query string:

![Screenshot from 2022-01-06 20-32-58](https://user-images.githubusercontent.com/1526883/148440501-d230cfa2-8a09-4467-8fc2-d8b9dbd03428.png)

When you create a mock rule from a request with query parameters, this matcher is now automatically created and populated with the list of parameters from that request.
