### ISSUE TITLE
feature request: ability to edit a request and repeat it

### ISSUE THREAD

**Issue by egi-gjevori** [httptoolkit/httptoolkit#179]
Can you add the ability to edit an existing request and repeat it?

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I think this is already covered by #48. Good suggestion, totally agree, but I'm going to close this issue to track this feature over there instead.
