### ISSUE TITLE
adb device is connected but not showing on httptoolkit.

### ISSUE THREAD

**Issue by vikasg603** [httptoolkit/httptoolkit#180]
The output for "ADB devices":
List of devices attached
emulator-5554	device

As we can see, the device is connected, but in the HTTP toolkit, it's showing not available.
I can connect the device with the QR Code method, but again the setup is manual, and since the device is rooted, I am wanted to install a certificate system-wise.

Is there any look around for the issue?

Note:  It worked for me for the last month, but I got this issue after I created 2nd user account on my MacBook air.

**Comment by pimterry** [comment]
Hmm, that's very unusual. Internally HTTP Toolkit just connects to ADB, and then [filters](https://github.com/httptoolkit/httptoolkit-server/blob/3386bf577d215c7e73b06b61cb29f3c4363e8384/src/interceptors/android/adb-commands.ts#L55-L60) out unauthorized/offline devices.

Is it possible that you have two ADB servers running locally for your two users, and your emulator isn't connect to the same one as HTTP Toolkit? What happens if you run `adb -P 5037 devices`? That's the default port that HTTP Toolkit will connect to if the `ANDROID_ADB_SERVER_PORT` env var isn't set to override it.

**Comment by vikasg603** [comment]
vikas@Vikass-MacBook-Air ~ % adb -P 5037 devices
List of devices attached
192.168.59.101:5555	device

this is the output when run the command.

**Comment by vikasg603** [comment]
and this is when tried printing ANDROID_ADB_SERVER_PORT
echo $ANDROID_ADB_SERVER_PORT

vikas@Vikass-MacBook-Air ~ % 
It's empty.

**Comment by pimterry** [comment]
Hmm, very strange. If you completely close HTTP Toolkit, and then launch it again from the command line, does it show anything interesting in its output there?

On Mac, you can do that by running `"/Applications/HTTP Toolkit.app/Contents/MacOS/httptoolkit"` in a terminal.

**Comment by vikasg603** [comment]
Okay @pimterry, I was able to resolve the issue while debugging the HTTP toolkit server.
export const getConnectedDevices = batchCalls(async (adbClient: adb.AdbClient) => {
    try {
        const devices = await adbClient.listDevices();
        const activeDevices = devices
            .filter(d =>
                d.type !== 'offline' &&
                d.type !== 'unauthorized' &&
                !d.type.startsWith("no permissions")
            ).map(d => d.id);
        console.log(activeDevices);
        return activeDevices;
    } catch (e) {
        console.log(e);
        
        
 In your filter method, the console.log(e) was printing Node.js error: getaddrinfo ENOTFOUND localhost.
 I guess it was because of my invalid /etc/hosts
 
 this resolved the issue, https://blog.andrewmmc.com/node-js-error-getaddrinfo-enotfound-localhost-b7ee35e1bb60
 
 But I will suggest you add this DNS exception in your code, too, so that this can help others in the future.

**Comment by vikasg603** [comment]
> Ah, ok! Yes that'll do it, I'll look into fixes for that.
> 
> You should definitely keep that /etc/hosts entry for the future though - loads of developer tools will assume that `localhost` works, and to be honest I'm a bit surprised HTTP Toolkit works at all without that.
> 
> Do you have any idea why it wasn't there before? Is that the default on your Mac, or something related to your 2nd user, or did you remove it some time maybe?

actually i was working with some tool SwitchHosts and the tool, by mistake, removed all entries for localhost.

So you can assume the issue was from my side only; Mac was not responsible for that, but debugging problems like this is very tough if, by mistake, someone did that.

That's why I told; it's always better to attach exceptions if we know that can happen.

**Comment by pimterry** [comment]
Ah, got it, makes sense! Thanks for the context. Sounds like this is all sorted for now, but feel free to get in touch in future if you have more issues.
