### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Official-Husko** [httptoolkit/httptoolkit#183]
I think a dark mode or making it by default dark would be a great enhancement. Its much better for the eyes to look at and makes working with it great for longer periods of time

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @Official-Husko! Thanks for the suggestion. Dark mode is actually supported already, but it's a Pro feature.

If you have HTTP Toolkit Pro, you can find it in the Settings, at the bottom under 'Themes'.

If you don't have Pro, I'd highly recommend it :-). Signing up for Pro also helps fund the project to support more development and additional features in future. Alternatively, Pro totally free for all open-source contributors to the project, so PRs and other contributions are very welcome too!

**Comment by Official-Husko** [comment]
> 
> 
> Hi @Official-Husko! Thanks for the suggestion. Dark mode is actually supported already, but it's a Pro feature.
> 
> If you have HTTP Toolkit Pro, you can find it in the Settings, at the bottom under 'Themes'.
> 
> If you don't have Pro, I'd highly recommend it :-). Signing up for Pro also helps fund the project to support more development and additional features in future. Alternatively, Pro totally free for all open-source contributors to the project, so PRs and other contributions are very welcome too!

i can completely see the pro part but i think something like a dark mode shouldn't be hidden behind a paywall. Im not trying to sound rude or anything i just think this is something that should be included regardless of free or pro due to persons who actually have problems with their eyes regarding a bright application and also for everybody else that wants to protect their eyes a bit with darker colors. I hope you can take this feedback in consideration for the future. Regardless thanks for your tool and keep up the work!
