### ISSUE TITLE
Inside HTTP Toolkit on your computer, do you see many blank rows like "Connection aborted" or "Certificate rejected"?,,

### ISSUE THREAD

**Issue by pogrametricwise** [httptoolkit/httptoolkit#187]
Inside HTTP Toolkit on your computer, do you see many blank rows like "Connection aborted" or "Certificate rejected"?,,
**yes**

Assuming you're using an official OS, are you using a Google Play, Google APIs or Vanilla emulator OS build?
**Yes using official tools**

Does the HTTP Toolkit android app show system certificates as enabled?
**How can i check?**

System certificate interception is necessary for intercepting 3rd party apps, if you can't rebuild them with debug features enabled. System certificates can't be added on "Google Play" Android emulators since they don't allow root access, but they are enabled automatically on other emulator versions and on rooted devices. There's more details in this emulator interception tutorial and in the Android docs.
**How can i check?**

If system interception is enabled then most apps should be intercepted successfully totally automatically. You may find one or two extra-secure apps (high-profile apps like Twitter/Facebook, and sensitive apps like banking) where certificate pinning is used, which requires some additional manual steps.

_Originally posted by @pogrametricwise in https://github.com/httptoolkit/httptoolkit/issues/181#issuecomment-928972045_

**Comment by pogrametricwise** [comment]
Please reply.

**Comment by pimterry** [comment]
(Continuing on #181)
