### ISSUE TITLE
Feature Request - Filter out request based on the content type

### ISSUE THREAD

**Issue by vikasg603** [httptoolkit/httptoolkit#188]
Hey team, For the last three months, I have been using the HTTP toolkit for our use, but one crucial thing missing from the HTTP toolkit is filtering out requests based on the content types.

For example, I want to see all requests which are not javascript or not images.
There is no way to filter out in our current version.

**Comment by vikasg603** [comment]
That would also be great.
adding something like not(category=js)

Or what if we can add something in UI to filter out content based on what we want and don't.

**Comment by pimterry** [comment]
> Or what if we can add something in UI to filter out content based on what we want and don't.

This sounds interesting, but I'm not sure I understand. How would that work, and when would you use it?

**Comment by vikasg603** [comment]
This is what is available on the chrome dev tool.
I was looking for something similar UI-based but with the added feature of not having that content type or color.
Currently, Chrome doesn't support similar to like showing all results which are not images.
or showing all results which are not script/stylesheets.

<img width="666" alt="Screenshot 2021-10-04 at 6 53 31 PM" src="https://user-images.githubusercontent.com/25488833/135859240-0ff12108-a771-4e09-8495-a9d380ebd0a4.png">

**Comment by vikasg603** [comment]
Here I can select JS if wanted to see only javascript requests or can select Fetch/XHR if wanted to see API requests.
Now the problem is, in applications we can't predict if the request is Fetch/XHR so what I can do from my side is to show only those requests which are not images and which are not javascript, and which are not styles.

**Comment by pimterry** [comment]
This was quick and easy, so I've done it ([here](https://github.com/httptoolkit/httptoolkit-ui/commit/a9dbf9508d9b3f446c3de5a2c6e7e63a03580a89)). You can now filter with `category=...` to easily find exchanges by their general type:

![Screenshot from 2021-10-05 13-13-04](https://user-images.githubusercontent.com/1526883/136013115-5c4a6b1d-df67-4267-81a7-e7e0f5f3e3f7.png)

There's a couple of other small improvements to categorization I ran into along the way too, which should ensure this covers even more cases.

Next time you open the app, it'll update in the background within 30 seconds or so, the subsequent time you should be able to test this out. Let me know if it works for you!

**Comment by vikasg603** [comment]
what a great solution not involving much UI change 😂
