### ISSUE TITLE
Export wire representation

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit#198]
Is it possible to export the wire format of a request? Like this:

~~~
GET / HTTP/1.1
Host: example.com
~~~

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Yes, it is: go to the 'Export' section for the request, and select 'HTTP/1.1' as the export format. Does that work for you?

**Comment by 89z** [comment]
Im not sure where that is. I only see EXPORT at the bottom, and it has options for cURL and Go and others, but not HTTP

**Comment by 89z** [comment]
Oh I see it now, but looks like needs the Pro version.

**Comment by pimterry** [comment]
It should be in the list there, like so:

![Screenshot from 2021-11-11 14-18-45](https://user-images.githubusercontent.com/1526883/141305050-1a8b5f72-50d6-49ec-a32b-6f18772975ab.png)

Does that not appear? There's no special logic here, everybody should always have the same list all the time.

**Comment by 89z** [comment]
Oh I see it now, but looks like needs the Pro version.

**Comment by pimterry** [comment]
Gotcha, hit a race condition there :smile:. Yes - export features for all formats require Pro.

I should note that Pro is totally free for all contributors to the project, even for the tiniest improvements ([more detail](https://httptoolkit.tech/blog/free-as-in-beer/#new-decade-resolutions)), so if you're not interested in subscribing then you're welcome to get involved instead.

**Comment by 89z** [comment]
I dont have a job now, so cant put any money on it :(

but if anything Ive done qualifies (bug reporting, etc), then that would be good. Otherwise no hard feelings.

**Comment by pimterry** [comment]
Ah, sure, you've been getting involved, why not. I've added a month to srpen6@gmail.com (from your GH profile). You can log in via Get Pro -> Log into existing account, it'll send you a code. Hope that's useful!

**Comment by 89z** [comment]
Thank you!
