### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit#200]
Is it possible to monitor the Google Play app itself?

I am using Android Virtual Device, if I choose a "Google Play" target, then I cant install the system certificate. If I choose a "Google APIs" target, then Google Play is not included, and I cant seem to install it. If I try the APK from here [1], I get this message:

~~~
APK Installer
---------------------------
The APK failed to install.<br/> Error: INSTALL_FAILED_UPDATE_INCOMPATIBLE:
Package com.android.vending signatures do not match the previously installed
version; ignoring!
~~~

I thought I did this before, but I cant remember how, and I cant seem to get it working now.

1. https://apkmirror.com/apk/google-inc/google-play-store

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by 89z** [comment]
looks like I was overthinking it - looks like you can just use a User certificate, rather than System certificate

**Comment by pimterry** [comment]
Just for reference, the conclusion here is: you didn't find a way to manually install Google Play in a rooted emulator, but you found that you could intercept it on a non-rooted device, is that right? That all makes sense, just confirming.

In the past, I have had success manually installing it using https://opengapps.org/ but only on rooted physical devices, for some reason I can't remember that didn't seem to work on an emulator.

**Comment by 89z** [comment]
> Just for reference, the conclusion here is: you didn't find a way to manually install Google Play in a rooted emulator, but you found that you could intercept it on a non-rooted device, is that right? That all makes sense, just confirming.

Correct. Life went easy on me for once :)

> In the past, I have had success manually installing it using https://opengapps.org/ but only on rooted physical devices, for some reason I can't remember that didn't seem to work on an emulator.

Good to know - I might try that in the future. Since you seem to maybe have some experience monitoring this app, I will ask: do you know of any way to get the version history of an app? I have a program that is able to download any version of an APK, but you have to provide the version number. I cant seem to find an API call that returns the version history. The calls Ive seen only return the latest version. Thats kind of the last step separating my tool from something like apkpure.com

**Comment by pimterry** [comment]
> do you know of any way to get the version history of an app?

No idea, sorry

**Comment by 89z** [comment]
Hm, actually it doesnt seem to work with API 25 or higher

**Comment by 89z** [comment]
Using Android Studio, I click Create Virtual Device, then choose this image:

API Level | Target
----------|----------------------------
25        | Android 7.1.1 (Google Play)

Then everything works up until after you sign in to Google Play on the device. After you sign in, you just get a screen on the device that says:

~~~
Try again
Retry
~~~

So you are able to capture the login process, but nothing else, such as searching or installing an app from the Google Play. If I set up another device under API 24, everything works as expected. This is not ideal, as some apps wont show up in Google Play, if you are using an older device.

**Comment by pimterry** [comment]
Ok, I think that's expected. 'Google Play' images are not rootable, so you can't install a system certificate. For Android versions 24+, without a system certificate all 3rd party apps that don't explicitly opt into user-installed certificates aren't interceptable, including Google Play but also everything else. This is an Android restriction, and there's nothing HTTP Toolkit (or anybody else but Google) can do about it. The only way to intercept an app on such devices is to edit the APK to tell it to trust user-installed certificates.

If you do want to intercept apps on an official emulator, you need to use a Vanilla AOSP version or a 'Google Services' version. In both cases you won't have Google Play app available, but you can either install it manually or install APKs manually instead.

On rooted devices that do have Google Play installed, as far as I'm aware everything should work correctly - I have a rooted physical test device with Google Play installed via https://opengapps.org/ and it works fine.

**Comment by 89z** [comment]
> On rooted devices that do have Google Play installed, as far as I'm aware everything should work correctly - I have a rooted physical test device with Google Play installed via https://opengapps.org/ and it works fine.

See, this is exactly the problem. My normal process is, that I create a device using "Google APIs" Target, which does not come with Google Play, but does allow root access. However if the APK I am wanting to monitor is Google Play itself, my process does not work, as the device does not have Google Play, and it doesnt seem possible to install it.

If you know some way to create a Virtual Device that is rooted and also has Google Play, then that would solve the problem.

**Comment by pimterry** [comment]
This guide looks promising: https://proandroiddev.com/install-google-play-store-in-an-android-emulator-82cd183fefed

Alternatively, it's probably possible to pull the APK from a compatible emulator that does have the play store installed with `adb pull` (more details: https://stackoverflow.com/questions/4032960/how-do-i-get-an-apk-file-from-an-android-device) and then you should be able to install it manually elsewhere using that APK directly.

**Comment by 89z** [comment]
> Alternatively, it's probably possible to pull the APK from a compatible emulator that does have the play store installed with `adb pull` (more details: https://stackoverflow.com/questions/4032960/how-do-i-get-an-apk-file-from-an-android-device) and then you should be able to install it manually elsewhere using that APK directly.

Getting the Google APK has never been a problem, as different sites offer it for download. However when I tried to install Google Play on a rooted emulator, I would always get an error about version mismatch. This is confusing because it seems that Google Play is not installed in a way that is usuable, as it doesnt show up on the home screen or apps list. But it seems that Google Play is installed enough that it prevents installing from other sources because of version conflict.

> This guide looks promising: https://proandroiddev.com/install-google-play-store-in-an-android-emulator-82cd183fefed

Thanks, that does look good. I have to admit, since I reopened this issue, I managed to get the information I need another way. However I do think it would still be useful for people to be able to capture from Google Play.

**Comment by 89z** [comment]
I finally tried this:

https://proandroiddev.com/install-google-play-store-in-an-android-emulator-82cd183fefed

but I dont think it works anymore. I tried all these:

~~~
open_gapps-x86-5.1-pico-20220215
open_gapps-x86-6.0-pico-20220215
open_gapps-x86-7.0-pico-20220215
open_gapps-x86-7.1-pico-20220215
open_gapps-x86-8.0-pico-20220215
open_gapps-x86-8.1-pico-20220215
open_gapps-x86-9.0-pico-20220215
~~~

and I always get one of these errors:

~~~
Unfortunately, Google Services Framework has stopped.

The APK failed to install.<br/> Error: INSTALL_PARSE_FAILED_NO_CERTIFICATES:
Failed to collect certificates from /data/app/vmdl846773082.tmp/base.apk:
META-INF/CERT.SF indicates /data/app/vmdl846773082.tmp/base.apk is signed using
APK Signature Scheme v2, but no such signature was found. Signature stripped?
~~~

**Comment by 89z** [comment]
OMG I got it working! I used this page:

https://multigesture.net/articles/inspecting-https-network-traffic-of-any-android-app

I will post more information soon

**Comment by 89z** [comment]
OK if youre interested, I put a writeup here:

https://github.com/89z/googleplay/blob/v1.7.5/docs/play-store.md

I think I covered all the gotchas. I think this can be closed now. If you have any questions, let me know.

**Comment by 89z** [comment]
sure, sounds great! If you wouldnt mind just linking to https://github.com/89z somewhere, that would be cool

**Comment by 89z** [comment]
FYI I found a better method for this using GenyMotion. I can provide more info if any interest
