### ISSUE TITLE
How to replace response payload with file?

### ISSUE THREAD

**Issue by gjws** [httptoolkit/httptoolkit#202]
I'm re-writting a very old web app for a customer that no longer has the source code . When a certainURL is hit, the server returns a file to the client. If I view the response in HEX I can export it via a HEX editor and see that it is a zip file. I need to respond with an alternative zip file, but as you can't edit the response in HEX I can't work out the best way to achieve this. What would be the best approach here? Thank you.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
You can add a 'from file' rule to do this, like so:

![Screenshot from 2021-11-26 14-33-35](https://user-images.githubusercontent.com/1526883/143588849-df20eea7-5b65-4436-84c2-604c89434b01.png)

Does that work for you?

**Comment by pimterry** [comment]
I take it from the :tada: that you're all sorted here! Glad to hear it! :smiley: I'll close this now, feel free to open a new issue if there's anything else I can do to help you out.
