### ISSUE TITLE
how to set up proxy to check device?

### ISSUE THREAD

**Issue by vanvietquocanh** [httptoolkit/httptoolkit#203]
I need to change the ip address of my mobile device during testing can you guide how to change the device ip address without affecting httptoolkit

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
@vanvietquocanh HTTP Toolkit isn't concerned about the IP address of your mobile device. You can change that IP address any way you like, depending on your network setup, and that won't affect HTTP Toolkit.

The only requirement is that your mobile device can still connect to HTTP Toolkit. If you want to change your IP by switching onto a totally different network, where it's not possible to connect directly to your computer that's running HTTP Toolkit, then HTTP Toolkit cannot be used.

Note that when you use ADB setup, ADB itself acts as a network between your computer and your device, tunnelling traffic. This might allow you to retain network connectivity via USB, even if the device is no longer on the same wifi as your computer.

Does that help clarify the situation? If not, can you please explain exactly what you're trying to do and why?

**Comment by vanvietquocanh** [comment]
i tried using httptoolkit via adb but the VPN is started making the proxy not working properly

**Comment by vanvietquocanh** [comment]
please reply email

**Comment by pimterry** [comment]
(Replied by email, so I'll close this, but just for reference later: it sounds like this is a case of needing to chain HTTP Toolkit with another proxy. To do so, use the 'Upstream Proxy' setting in HTTP Toolkit on the _computer_, not on the phone, so that traffic goes phone -> computer -> other proxy -> real target)
