### ISSUE TITLE
Devices outside network

### ISSUE THREAD

**Issue by FeSade1** [httptoolkit/httptoolkit#205]
Is there somehow to foward another networks requests to mine? I mean like, instead of the toolkit open the server in my internal network ip, do it on the external IP, so for exemple I could set up my IP as an proxy in other PC (like 179.176.xxx.xx:8000) and than see all the traffic of the other machine

**Comment by pimterry** [comment]
Hi @FeSade1. This is possible, but HTTP Toolkit can't do it for you, it's something you need to configure on your network.

On a normal home/small office network, to do this you just need to configure the router to forward an external port (any port you like) to port 8000 on your computer's local IP. When you do that, incoming connections your external IP address on that external port will be received and proxied by HTTP Toolkit. Does that make sense?

**Comment by FeSade1** [comment]
For sure, thanks a lot! I was trying to do that, but I did opened the 8002 port instead of 8000 (cause I tought it was already open), thats why it wasn't working lol
