### ISSUE TITLE
Android ADB interception not available

### ISSUE THREAD

**Issue by FeSade1** [httptoolkit/httptoolkit#206]
In the Intercept menu, there are a few functions that are marked as Not Available, is that an client side configuration or server sided? I want to use the intercept for android with ADB (cause of the CA certificate) but it seems blocked, and I saw an print in twitter of a guy with this option enabled

Device(S8) is connect and with depuration active

**Comment by pimterry** [comment]
Hi @FeSade1. The availability of each interception option is just decided by what HTTP Toolkit can detect on your machine.

For ADB specifically, that option is available if HTTP Toolkit can connect to ADB, and if you currently currently have a device connected there. Those are the only requirements.

What's the output if you run `adb devices` on the command line?
