### ISSUE TITLE
Intercepting encrypted Firebase database websocket connection

### ISSUE THREAD

**Issue by adityaketkar** [httptoolkit/httptoolkit#207]
Hi!

I was using HttpTookit on an android app.
I can see most of the https requests going through the phone on my mac, except for a couple of websocket requests made by firebase database. 

I think this is because firebase does not respect the proxy settings of the phone. I can see the request being made in Packet Capture app, but the payload is encrypted there. The connection does not show up in HttpToolkit, probably because firebase will ignore the phone-wide proxy and make the request directly to the destination server.

Is there any way I can intercept and decode the websocket message payload? 

TIA

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @adityaketkar. This is a general websocket limitation right now I'm afraid (see #36). Websocket traffic is proxied successfully, but it's not visible in HTTP Toolkit.

That's come right up to the top of my priority list in the last few weeks though, and I'm actively working on it as we speak! It's going to take a while, but I'm hoping to have a first release available in the next few months.

> The connection does not show up in HttpToolkit, probably because firebase will ignore the phone-wide proxy and make the request directly to the destination server.

Just FYI, you don't have to worry about this happening in general - HTTP Toolkit's Android app doesn't just set the proxy settings, it runs a full VPN that controls and rewrites all packets on standard ports (you can configure the ports redirected from within the app itself). Even if an app actively ignores proxy settings, if it uses any common HTTP/HTTPS port then the traffic will still go to HTTP Toolkit regardless. If you're interested in the details, I wrote them all up here: https://httptoolkit.tech/blog/inspecting-android-http/

Anyway, thanks for reporting this. I'm afraid your options for workarounds right now are limited, but keep an eye on #36 and once that's available you will be able to see the content of all your websocket messages in HTTP Toolkit. I'm going to close this for now, and we can track that over there.
