### ISSUE TITLE
Mmssn

### ISSUE THREAD

**Issue by mmishaal** [httptoolkit/httptoolkit#210]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @mmishaal, I'm not sure what this means!

I'm going to close this issue, but feel free to share some more details about your issue/question/feedback, and I'll reopen it.
