### ISSUE TITLE
Support right-click -> copy from response body

### ISSUE THREAD

**Issue by intari** [httptoolkit/httptoolkit#212]
Windows 11 (also happen with Windows10)
When I select 'response' block - I can copy via right click->copy.
When I select text in Response body block - I can't copy - I should save file, open it in some other editor and only later I can select and copy it (to paste in mock control system).
Can this be fixed?

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hmm, good point, thanks for reporting this. It's a bit tricky to handle unfortunately (there's some complicated interactions between Monaco providing the editor internally, and Electron providing context menu hooks elsewhere) but I'll keep an eye out for ways to improve that.

In the meantime, you can copy text from the body editors by simply selecting it and pressing Ctrl+C. Does that work for you, or is there a reason the context menu is better?

Also, just FYI, you might be interested in the 'Create a mock rule from a request' button in the bottom footer when a request is selected. It looks like :performing_arts:. If you click that, it will create a new rule that automatically includes the details & body of the response by default.

**Comment by intari** [comment]
Ctrl+C appears to work (it's slighlty worse for me due to my work setup with Logitech multi-device keyboard but it works. thanks for advice). 
'Create a mock' doesn't applicable for my use-case. copied json will go to external systems anyway.

**Comment by pimterry** [comment]
This is now done! There's now a new context menu available that supports the standard copy/cut/paste options within all embedded editors throughout the tool.

Next time you run HTTP Toolkit it'll update in the background, and the following time this should work correctly. Thanks for reporting this! Do let me know if you have any other issues or feedback.
