### ISSUE TITLE
Interception support for Powershell terminals

### ISSUE THREAD

**Issue by eabase** [httptoolkit/httptoolkit#214]
Hi! 
I want to use this tool with `curl` under either Powershell core or Cygwin, on Win10, but I don't see any info on how to do that here.

Specifically and normally I am using:
- a VPN
- no proxy

Some working curl examples and HTK config instructions would be much appreciated.

(Slightly related to #117 ?)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I think if using a VPN without a proxy should work just fine. HTTP Toolkit's outgoing traffic will just get automatically routed via the VPN.

The Powershell/Cygwin part is a little more complicated. On Windows, HTTP Toolkit can automatically launch & intercept `cmd` and `git-bash` terminals, but right now that's it.

Terminal interception works primarily by setting various environment variables as part of launching the target terminal. Environmental variables are inherited though, so as a quick workaround, you can probably click 'Fresh Terminal' to open a `cmd` window, and then launch cygwin or powershell from there to get an intercepted terminal of any kind you like.

Does that work for you?

If it does, and you have a command that successfully launches an intercepted powershell or cygwin terminal, then it should be very easy to add to HTTP Toolkit itself to give that terminal first-class support. The code behind this is here: https://github.com/httptoolkit/httptoolkit-server/blob/master/src/interceptors/terminal/fresh-terminal-interceptor.ts#L42-L50. PRs very welcome, and note that all HTTP Toolkit contributors get [free HTTP Toolkit Pro](https://github.com/httptoolkit/httptoolkit/#contributing-directly).

**Comment by pimterry** [comment]
I'm going to close this in favour of #77, which is tracking Powershell terminal support specifically. That's not available yet, but it's coming very very soon - watch this space!
