### ISSUE TITLE
not quite sure what's up, followed all instructions but it still says system trust disabled on android emulator

### ISSUE THREAD

**Issue by silvacarl2** [httptoolkit/httptoolkit#217]
---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by t33v33b0x** [comment]
connecting via adb? did you adb root?

**Comment by shirshak55** [comment]
@pimterry I think the desktop app should notify the user that it was unable to do ADB root and if possible HTTP toolkit UI should do adb root if possible? And warn user should explicitly install the certificate? I think the current UX is kinda confusing?

**Comment by pimterry** [comment]
> HTTP toolkit UI should do adb root if possible

HTTP Toolkit does already do `adb root` on all devices where `su` isn't sufficient. That happens [here](https://github.com/httptoolkit/httptoolkit-server/blob/69475d581feb8f2b4797641aac8ec79859ac3d28/src/interceptors/android/adb-commands.ts#L134-L161). 

> warn user should explicitly install the certificate

The Android app does tell you whether it was possible to install the certificate, and explain how to do it manually - that's what the system/user certificate UI is for, and the user certificate install prompt that appears on the device during setup. We could move those instructions into the desktop UI instead, but I'm not sure that would help much...

It is important to note that many users aren't using rooted devices though, so they don't want loud warnings if root setup doesn't work. Looking at the Android stats, it seems about 50% of Android users are using non-rooted devices. I think those people are probably either testing their own Android apps during development (where it's better to test with normal non-rooted devices, and change cert config in their app debug builds) or debugging HTTP traffic for web apps on mobile (where Chrome and most other browsers trust user certs automatically even without root).

I'm open to improvements, but I don't really want to show big warnings that make the UX worse for those use cases. I'd rather focus on fixing any bugs that break setup for real rooted devices (like https://github.com/httptoolkit/httptoolkit-android/issues/8). If there are cases we can't handle manually I'm happy to try and detect those and add extra info and/or docs for users to cover that case, but I'm hopeful that everything can be automated.

Really the main thing I'd love is a way to automate non-root certificate setup. There's an open & assigned bug with Google to look into this for future Android versions (https://issuetracker.google.com/issues/168169729) but there's not much visible progress there yet. Any suggestions for ways to work around that in the meantime would be very very welcome :smile:.

Anyway, we're on a bit of a tangent here. Back on the original issue:

> followed all instructions but it still says system trust disabled on android emulator

@silvacarl2 can you share more details about your device? If you could let us know what OS version you're running and how it was rooted, that might offer some clues about what's going on here. It would also be useful to know the output of running:

* `adb shell` and then `su root whoami`
* `adb shell` and then `su -c whoami`
* `adb root`, `adb shell` and then `whoami`

Those are the three methods HTTP Toolkit tests when looking for root access on a connected device. If there are issues there, that might offer some clues.
