### ISSUE TITLE
can't get it working anymore it worked fine for 3 weeks now it looks like it doesn't work anymore with memu play

### ISSUE THREAD

**Issue by thisisluc** [httptoolkit/httptoolkit#219]

**Comment by pimterry** [comment]
Hi @thisisluc. It appears there was a brief issue around the new year which caused issues with certificate generation, but everything should be working again today. Can you check if everything is working correctly for you now?

If not, and you're still seeing issues today, then it would be helpful if you can share screenshots of any errors that you're seeing and the contents of the 'View' page in HTTP Toolkit when interception fails.

**Comment by thisisluc** [comment]
it works fine again thanks
