### ISSUE TITLE
Hello How to Enable System Trust Disabled

### ISSUE THREAD

**Issue by tonmooy** [httptoolkit/httptoolkit#223]
Hello How to Enable System Trust Disabled on Android Device

User Trust Enabled but System Trust is not enabled on Non Rooted Device. help me how can i enable it

**Comment by pimterry** [comment]
It's not possible to enable system trust on a non-rooted device, sorry. That's a limitation of Android which HTTP Toolkit can't work around unfortunately.

If you don't have a rooted device, I recommend using an emulator instead. There's a detailed guide to the whole process here: https://httptoolkit.tech/blog/inspect-any-android-apps-http/

**Comment by alexrintt** [comment]
(Note for those that fell here and that are using Android Studio emulators)

Android Studio emulators are rooted by default, except by emulators with Google Play enabled.
