### ISSUE TITLE
[Feature] Test Request Again ? 

### ISSUE THREAD

**Issue by m7mdcc** [httptoolkit/httptoolkit#234]
Hi , 

I'm asking for feature on requests to simulate request again to see the response , like try this request again ..

What do you think?

**Comment by pimterry** [comment]
Yes, totally agree! This is actually tracked already in #48. I'm going to close this issue to avoid duplicating that, but you can add a :+1: there to vote for that issue or subscribe to it via GitHub notifications to hear when this feature is available.
