### ISSUE TITLE
Rules aren't restored in the UI

### ISSUE THREAD

**Issue by krishnaraj** [httptoolkit/httptoolkit#236]
After adding a rule (under 'Mock') if you click on another tab (say View) and then come back to the rule, the UI doesn't show the rule but it still works.

![httptoolkit-bug](https://user-images.githubusercontent.com/141018/151982342-06cef305-0874-47e1-9265-4cc8d64e110c.png)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
After you enter a URL, did you click the '+' button there on the right? You have to press that to add the match condition to the rule. If you don't, it's not saved, and it will disappear if you go to another page.

I know the UX here is a bit confusing, sorry! PRs to improve this or add a warning for unsaved data in this editor would be very welcome.

**Comment by krishnaraj** [comment]
That was one quick reply!

Clicking the '+' does indeed work. I thought it was only to add more rules.

**Comment by pimterry** [comment]
Great! Glad to hear this is working for you now, do let me know if you run into any other issues.
