### ISSUE TITLE
Server shutdown unexpectedly with code 3221225785 on Windows 7

### ISSUE THREAD

**Issue by jigyasulab** [httptoolkit/httptoolkit#243]
![Uploading 16451083418835519325997418749274.jpg…]() Please solve this problem

Server shutdown unexpectedly with code 3221225785

**Comment by pimterry** [comment]
Hi @Devender9050, can you share some more information?

What version of Windows are you using?
Do you have any anti-virus installed?

Also it looks like you posted this before your image finished uploading. Can you try to post that image again please?
