### ISSUE TITLE
Mac version of the app isn't working on MacBook Air (M1)

### ISSUE THREAD

**Issue by RSuraj** [httptoolkit/httptoolkit#245]
Every time the app is opened, It says - 

This is taking longer than normal...
If this persists or happens often please [file an issue](https://github.com/httptoolkit/httptoolkit/issues/new) and help make HTTP Toolkit faster.

---
<img width="1440" alt="Screenshot 2022-02-21 at 11 34 57 AM" src="https://user-images.githubusercontent.com/10010462/154898326-7109e536-bf9a-4084-835b-eedf07daa96b.png">

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @RSuraj, thanks for reporting this, that's very unusual.

What's happening here is that HTTP Toolkit is starting an internal proxy server and connecting to it. For some reason that's not possible: either the server isn't starting properly, or the server is starting but isn't accessible for some reason.

Can you open the developer tools in the app (View -> Toggle Developer Tools), go to the console tab, and then share all the output shown there here? That might have some clues.

Another possibility here would be some firewall on your machine that blocks connections to local servers (`127.0.0.1:45456` in this case). Are you using anything like that?

**Comment by heswell** [comment]
I just tried installing on a new MacBook Air (M2). When I open the app I see nothing but a blank window. There are no messages in the devtools console. I do not have firewall on

**Comment by pimterry** [comment]
I'm actually going to close this entirely, since it's been inactive for a while.

@RSuraj if you are still seeing this issue (or anybody else has the same problem, where the progress bar loads but never completes at all) please share your logs here - you can find them in the menu under Help -> View HTTP Toolkit Logs.
