### ISSUE TITLE
HTTP Toolkit hit an error(code 3221225785)

### ISSUE THREAD

**Issue by N-X-T** [httptoolkit/httptoolkit#247]
I got this error. First, this error with code 1, then i reinstall and get code 3221225785.
What should I do next? Thanks for reading.
![image](https://user-images.githubusercontent.com/49335931/155252512-e308f976-82b3-4793-bcf8-089df668346d.png)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @N-X-T! See #243 - this means that your version of Windows is no longer supported I'm afraid.

On Windows, HTTP Toolkit only supports version 8.1 or newer. Older versions of Windows are no longer supported even by Microsoft, and have not been for many years.
