### ISSUE TITLE
Bug: NodeJS proxy changes HTTP POST request body

### ISSUE THREAD

**Issue by roschaefer** [httptoolkit/httptoolkit#255]
Sometimes, the request body is different when running NodeJS from a proxied terminal vs. when you don't use the proxy.

![image](https://user-images.githubusercontent.com/2110676/159058070-3637cf0e-e65b-4857-aa2a-18d96fa26388.png)

![image](https://user-images.githubusercontent.com/2110676/159057469-d561953e-b96b-4eab-8e60-fbeb90fb22d3.png)

This caused me a lot of frustration because I assumed the problem is my own code at first.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by shirshak55** [comment]
I think this is because node js and browser are encoding in a different ways. Is there a way to reproduce it?

**Comment by pimterry** [comment]
Just spotted this issue again - we've had some separate discussions elsewhere but I'm not sure if this was ever resolved?

I'm going to close this for now since it's very stale, but happy to reopen & investigate further if this is still an issue, if you can share a demo so I can reproduce this.
