### ISSUE TITLE
HTTP Toolkit crashes on startup

### ISSUE THREAD

**Issue by bosscube** [httptoolkit/httptoolkit#261]
When starting the application, it fails each time with the error message: "**Server shutdown unexpectedly with code 3221225785.**"

OS: Windows 7 Ultimate (64-bit)

I tried running as admin and restarting the PC before running as admin.

![image](https://user-images.githubusercontent.com/1063283/160253936-f8d4a73a-fa1f-455c-9312-0e16dc515658.png)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by bosscube** [comment]
https://github.com/httptoolkit/httptoolkit/issues/243#issuecomment-1043063207

**Comment by bosscube** [comment]
FYI: For anyone who is getting this error and needs to still use Windows 7 - yes we all know it's unsupported - you can simply download the Node 14.5+ (up to 14.6.1) binary and replace the server binary with it.

E.g. your server binary might reside at: C:\Users\**Your Username**\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bin\**node.exe**

Just replace node.exe with the older version you downloaded (E.g. https://nodejs.org/dist/v14.16.1/win-x64/node.exe) and voila.

**Comment by JasonBall34** [comment]
I got this same problem (crashes on startup, using Windows 7) with the same error message popup, except it says code 1 and not that long string of numbers. My node.exe was already an old version. Any other workarounds? Yes, I understand Win7 has security vulnerabilities but I don't really understand why that means that perfectly good working programs have to stop working all of a sudden. I loved this tool, it was a fantastic way for me to see my phone's network traffic, and now I just can't? Unless I upgrade my Windows? Kinda bummed about this. I didn't realize this tool wasn't an offline program that would work in perpetuity. Hoping there's another workaround possible.
