### ISSUE TITLE
Intercepts Templates for Chrome & Safari showing as disabled

### ISSUE THREAD

**Issue by jwareley** [httptoolkit/httptoolkit#262]
I have subscribed to the HTTP Toolkit Pro subscription but the Chrome & Safari templates are still disabled.

Please advise as I have restarted the app several times but it still shows as disabled options.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Fixed by email - this was resolved by enabling Spotlight indexing.

Spotlight was disabled, so Chrome etc couldn't be found, and the fallback search of /Applications couldn't find it either for some reason (TBC).
