### ISSUE TITLE
Auto scroll

### ISSUE THREAD

**Issue by mainsean435** [httptoolkit/httptoolkit#263]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @mainsean435, I'm not sure what this means. HTTP Toolkit does have auto-scroll: on the View page, if you scroll to the bottom of the list or click the :arrow_down: in the bottom footer, it will follow new traffic as it comes in until you scroll away.

Is that not working for you? If so, could you please share more details about what you're doing, what OS you're using, and a quick video of what you're seeing?
