### ISSUE TITLE
[Question] Is it possible for a website to see that I'm using HTTP Toolkit?

### ISSUE THREAD

**Issue by devilHorns13** [httptoolkit/httptoolkit#265]

**Comment by pimterry** [comment]
Good question! It is possible, yes, but it's not easy.

In general the content of the request should be identical, so any normal analysis of that won't show any clues, and should appear to be real traffic from the original client. For any typical API checks or manual investigation that's all that matters.

However, some advanced tools analyse tiny extra details, which can be used to spot small implementation differences, and thereby recognize types of client independent of the request content.

TLS fingerprints are the best example of this: https://httptoolkit.tech/blog/tls-fingerprinting-node-js/. HTTP Toolkit's TLS fingerprint is unavoidably different to your original HTTP client's, and this can be recognised to spot requests sent via HTTP Toolkit. This is not common though - a few very very large CDNs (Akamai, CloudFlare) use similar techniques to detect bot traffic, but its difficult to do in most environments, and I'm not aware of any end services themselves storing or analysing this data.

Does that answer your question? Is there a specific scenario you're interested in?

**Comment by devilHorns13** [comment]
@pimterry Thanks.
