### ISSUE TITLE
Http Toolkit not working, not starting... 

### ISSUE THREAD

**Issue by mkajnar** [httptoolkit/httptoolkit#269]
Http Toolkit not working, not starting... 
Freezing

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @mkajnar, sorry to hear that. Can you share some more information?

* What OS are you using, and what version?
* What are you trying to intercept?
* When does HTTP Toolkit freeze? Right at the start before you've done anything, or some time later?
* If you look at your OS system/activity monitor, does it show anything unusual? For example, is HTTP Toolkit using all your CPU, or have you , or anything else?
* Can you share a screenshot or short video of the app failing?

**Comment by mkajnar** [comment]
Hello, It was caused by a paid version of Nod32 antivirus. Even when I put your program in exceptions, it ignored them. So it went off the PC and I refused to pay them (I won't use such software that goes against development tools at all). Thanks. Milan
