### ISSUE TITLE
not 

### ISSUE THREAD

**Issue by rdsrwj** [httptoolkit/httptoolkit#270]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi, I'm not sure what's going on here! I'm going to close this but feel free to reply with more information and I'll reopen it.
