### ISSUE TITLE
Not able to Intercept Instagram Reel Feeds

### ISSUE THREAD

**Issue by ashusingh1** [httptoolkit/httptoolkit#277]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @ashusingh1, can you share more details? What device are you using, with that OS (and rooting setup)? How are you intercepting it? How exactly is this failing? Anything you can share would be very helpful, especially screenshots of any errors you're seeing.

Are you using the Frida script for certificate unpinning? See https://httptoolkit.tech/blog/frida-certificate-pinning/ for more info.
