### ISSUE TITLE
Allow disabling proxy in mock request

### ISSUE THREAD

**Issue by vikasg603** [httptoolkit/httptoolkit#278]
Hey team, I am doing some experiments where I am adding proxies to change my IP.
but for 1 specific request, I am mocking that request and sending that to localhost.
But the proxy in the middle not allowing me to send that to my local host.

Is there any way I can disable proxy while mocking the request?

**Comment by pimterry** [comment]
This isn't possible with the normal proxy settings in HTTP Toolkit I'm afraid - upstream proxies are all or nothing right now.

For these kind of advanced rule setups, you generally need to start using Mockttp manually. There's a guide to setting up Mockttp here: https://httptoolkit.tech/blog/javascript-mitm-proxy-mockttp/. Using Mockttp, you can define a proxy with custom rules with arbitrary parameters that work any way you like, including configuring an upstream proxy only for certain passthrough rules that match very specific traffic.

You can still use this alongside HTTP Toolkit at the same time. To do so, you'd need to create your Mockttp proxy, and then set that as your upstream proxy in HTTP Toolkit, and trust its certificate. That way, all proxied traffic will go to the Mockttp proxy, which can then proxy  traffic further according to your custom rules - redirecting some to localhost or using an upstream proxy or anything else you'd like at all.

Does that make sense?

**Comment by pimterry** [comment]
Oh wait, there is one option: is there any chance your special request is the only one that goes to a different host? There is an option to configure the proxy by hostname, on the Settings page.

If it's just one host, you could add it there and then all traffic for that host won't be proxied. Would that work for you?

**Comment by vikasg603** [comment]
Ohh wait, I just saw I can add localhost in NON-PROXIED HOSTS, sorry I should have checked this before.

**Comment by pimterry** [comment]
Perfect! Glad we got that sorted out :+1:
