### ISSUE TITLE
Keep getting 403 on launch, why cant i access it

### ISSUE THREAD

**Issue by NoahGdev** [httptoolkit/httptoolkit#283]
Startup failed: "Server XHR error during getVersion, status 403 Forbidden"

**Comment by pimterry** [comment]
Can you share some more info?

* What OS & OS version are you using?
* Is this the first time you've used HTTP Toolkit, or have you used it successfully before?
* Is there anything unusual about how you're running HTTP Toolkit, or anything else unusual about your computer setup?
