### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wandoelmo** [httptoolkit/httptoolkit#296]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @wandoelmo, can you share some more information? I'm happy to help, but this isn't a very useful bug report. Can you explain exactly what you're trying to do, and where it's going wrong? If you could share screenshots of the error you're seeing that would also be very helpful.
