### ISSUE TITLE
Report network errors more accurately

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#3]
Currently these appear as 502s, if the proxy fails to connect upstream, but we could more closely emulate real errors, and show that in the UI more clearly.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by ristomatti** [comment]
I used HTTP Toolkit today while doing a code review. I wanted to test if/how the server side request errors are logged. I noticed no stack traces were logged when I used a non-existing hostname and commented on this. Only after my team mate said he cannot reproduce the behavior I realized it's actually HTTP Toolkit responding the 502 status I was seeing.

The requests were sent by Axios on the server side of a Next.js app. When using HTTP Toolkit's proxy, a non-existing hostname would result in a 502 response, while acually a "No response" error was thrown when using a direct connection.

**Comment by pimterry** [comment]
Ahh, interesting. Yes, that's a good example of where we could fail more strictly. We can't reject the connection with a DNS error or reject the TCP handshake or similar (because we need to fully receive the connection & request to know what you want to send in the first place) but we could explicitly drop the connection at that point.

That would at least result in a 'Connection reset' error instead of a 502 response, which would probably trigger similar behaviours. I'll have a quick look into it and see what I can do.

**Comment by pimterry** [comment]
This is now live :rocket:

Next time you open HTTP Toolkit it'll update in the background, and the following time everything should work as expected - with connection failures (i.e. any failures at the TCP/DNS/TLS level) triggering TCP connection resets, which should far more closely simulate real-world non-intercepted behaviour.

There's also a little more info now included in the UI for connection errors like this, so they remain easy to debug even without the message in the response body.

Thanks for the nudge on this, good suggestion!
