### ISSUE TITLE
httptoolkit

### ISSUE THREAD

**Issue by Rahf195** [httptoolkit/httptoolkit#303]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @Rahf195, I'm happy to help, but this issue doesn't tell me anything about the problems you're facing or what you're looking for.

I'm going to close this for now, but if you have a specific problem or you're looking for a feature, please [open a new ticket](https://github.com/httptoolkit/httptoolkit/issues/new) with more information so I can help you out!
