### ISSUE TITLE
intercept traffic 

### ISSUE THREAD

**Issue by eluancardoso** [httptoolkit/httptoolkit#304]
traffic work ok in emulator, but in my real device not work, get wrong certificate and my device are rooted and i give SU permission forever for httptoolkit

**Comment by pimterry** [comment]
Hi @eluancardoso. In the HTTP Toolkit app on Android, what does it show for 'user' & 'system' interception? Can you share a screenshot?

Can you also please share a screenshot of the certificate error you're seeing in Android app, and the traffic that's shown on the 'View' page of HTTP Toolkit on your computer?
