### ISSUE TITLE
[Bug]: Impossible to start httptoolkit

### ISSUE THREAD

**Issue by ziedtabesto** [httptoolkit/httptoolkit#306]
### Repro steps

Hello,
httptoolkit refuse to start systematically, you find attached a screenshot showing the problem.

Can you check please?

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

<img width="282" alt="image" src="https://user-images.githubusercontent.com/99667329/177568296-d0fbde73-21b2-4890-afd5-3a4f718729dc.png">

**Comment by pimterry** [comment]
I see, thanks for reporting this! I haven't seen that before myself, this is very unusual.

Have you used HTTP Toolkit successfully in the past? Did this work before for you back then?

The devtools console screenshot is very helpful info, thank you! Most of that is not too unusual, but there's some interesting clues I think.

More generally though, when you say "httptoolkit refuses to start" - what does the main UI actually show? Does it get stuck on the progress bar, or does it show an error there, or does it load but not work, or something else?

Can you open the developer tools immediately when the app opens, and then share a screenshot of the 'network' tab there once everything has failed?
