### ISSUE TITLE
[Bug]: HTTP TOOLKIT start slow and don't work

### ISSUE THREAD

**Issue by jhillo** [httptoolkit/httptoolkit#320]
### Repro steps

Open desktop app

### How often does this bug happen?

Every time

### The desktop OS you're using

WIN 10 pro

### Details of other apps/devices

Java Temurin-11.0.14.1+1

### Error screenshot

no

### Any other info?

I removed it and instal again several veresion, but it was not works  (start but thats it)

**Comment by pimterry** [comment]
Hi @jhillo, can you share some more information? When you say it doesn't work - what happens exactly?

Is it that the app never shows any content or buttons at all, or there's something specific you're looking at or clicking on that fails?

**Comment by jhillo** [comment]
IT, s ok now. Maby it reserve some needed port and not release it when app
shut down. Anyway. when I retsrart my PC everything works.

BR. Jouni Sirkiä

pe 19. elok. 2022 klo 18.11 Tim Perry ***@***.***> kirjoitti:
