### ISSUE TITLE
[Bug]: Failed intercepting websocket traffic from android WebView

### ISSUE THREAD

**Issue by asurabots** [httptoolkit/httptoolkit#324]
### Repro steps

Failed intercepting websocket traffic that comes from a game that is using webview.

APK: https://apkpure.com/pirates-war/com.ttgame.paw

Normal http requests are working fine i can see them all except websocket traffic

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

Memu Emulator

**Comment by pimterry** [comment]
If you can't see the websocket traffic, how do you know there is websocket traffic missing?

Are there errors shown anywhere, either in the app or in HTTP Toolkit? If so, please share a screenshot.

**Comment by asurabots** [comment]
> 

there are no errors in the app it just works like it normally does, i know theres websocket traffic because it's an online game and to play you need to join a server. One of the http requests returns all the available servers and the websocket url to connect to.

Also from the http traffic i got the javascript source code it was running and found it: 
![image](https://user-images.githubusercontent.com/97172767/187516738-24fb1f38-63f8-4a35-8977-297bb580b059.png)

and to make sure i visited the url the app was visiting via weburl and managed to connect to socket and see the request via browser

**Comment by asurabots** [comment]
this seems to be fixed
