### ISSUE TITLE
[Bug]: ERR_Ceritificate_Transparency_Required on Android

### ISSUE THREAD

**Issue by pb36** [httptoolkit/httptoolkit#325]
### Repro steps

Open the Desktop App
Android Device via ADB (Device is rooted)
Click on Test Interception.

### How often does this bug happen?

Every time

### The desktop OS you're using

Android 9

### Details of other apps/devices

Chrome Version : 105.0.5195.77

### Error screenshot

![Screenshot_20220905-233713](https://user-images.githubusercontent.com/33996614/188498889-897b472b-3731-432f-acc4-6438e9363a2b.jpg)
![Screenshot_20220905-233724](https://user-images.githubusercontent.com/33996614/188498896-c800cb1d-d968-4714-ac31-d04dbfe271e3.jpg)
![Screenshot_20220905-233731](https://user-images.githubusercontent.com/33996614/188498897-4f47172f-024a-45b3-9a85-96c6242e3d8b.jpg)
![Screenshot_20220905-233543](https://user-images.githubusercontent.com/33996614/188498900-d7c0d4d3-e7b0-4ec3-a06b-3c083673aff6.jpg)

### Any other info?

Some apps can send requests, but chrome and apps using web view cannot move forward due to this issue. saying ERR_Ceritificate_Transparency_Required

**Comment by pimterry** [comment]
Hi @pb36, thanks for reporting this, that's very interesting.

This is a known problem, but there is a fix deployed, and I thought this was resolved everywhere that I've tested. There's more context & info on the work so far to fix this here: https://httptoolkit.tech/blog/chrome-android-certificate-transparency/

In your case, that's clearly not working for some reason. Can you please:

* Within an `adb shell` session, run `cat /data/local/chrome-command-line` and `cat /data/local/tmp/chrome-command-line`, and share the output here
* Within Chrome, go to `chrome://version` and share a screenshot of the full details there (the 'command line' section especially)
* Hover over the 'HTTP' logo in the HTTP Toolkit desktop app, and share the versions that are shown there here.
* After reproducing the issue, share your desktop app's last-run log file. You can find it in the menu: Help -> View HTTP Toolkit logs.

**Comment by pb36** [comment]
```
OnePlus5:/ # cat /data/local/chrome-command-line
cat /data/local/chrome-command-line
chrome --ignore-certificate-errors-spki-list=U5t8YKiwgHsRGq/tZo0ab/STEh2YPqZ7y7JSiyxZwHY=
OnePlus5:/ # cat /data/local/tmp/chrome-command-line
cat /data/local/tmp/chrome-command-line
chrome --ignore-certificate-errors-spki-list=U5t8YKiwgHsRGq/tZo0ab/STEh2YPqZ7y7JSiyxZwHY=
```
HttpToolkit Version
![image](https://user-images.githubusercontent.com/33996614/188628700-6f0b8765-1369-4011-8b8f-49d8185d004e.png)

Chrome Details
![Chrome Screenshot](https://user-images.githubusercontent.com/33996614/188628744-e609c641-a428-4aa0-872e-fba4252e6d37.jpg)

[last-run.log](https://github.com/httptoolkit/httptoolkit/files/9496642/last-run.log)

**Comment by pimterry** [comment]
Thanks that's very helpful: this is the latest version which includes the patch, and the patch process does seem to be running successfully (i.e. it's adding all the right files with the right data) but still for some reason Chrome is ignoring the settings.

Unfortunately though, I don't know why that might happen! Is there anything unusual about this device? Did this ever work for you in the past?

Chrome themselves have docs for alternate ways to set flags here: https://www.chromium.org/developers/how-tos/run-chromium-with-flags/#android. If you can use those to successfully launch Chrome with that `--ignore-certificate-errors-spki-list=U5t8YKiwgHsRGq/tZo0ab/STEh2YPqZ7y7JSiyxZwHY=` flag set then everything should work correctly.

**Comment by pimterry** [comment]
Ah, in fact that leads me to a good idea: can you try going to `chrome://flags`, changing "Enable command line on non-rooted devices" to "Enabled", and then pressing restart Chrome? Pressing the "Relaunch" button apparently isn't enough - you'll may need to kill and reopen it.

If you do that, does it then show the flag correctly on `chrome://version`?

If so, that means that this is a rooted device, but for some reason Chrome doesn't believe it, and so it's using the locked-down settings for production devices. I haven't seen this myself, but it makes sense. If that is the case, everything should work for you with this flag enabled, and I can investigate ways to handle that better in future.

**Comment by pb36** [comment]
Hi, @pimterry. I got it working by enabling the `Enable Command line on non-rooted devices` Flag. Thanks for sorting it out this fast.

**Comment by pimterry** [comment]
Great, thanks for letting me know :+1:. That means this was indeed what I thought above: it's a rooted device, but Chrome doesn't realise, so it's acting like a production version that ignores these flags.

I will see what I can do about that, so that this flag isn't necessary. Out of interest, how was this device rooted? Is it some kind of emulator, or is it a real device?

**Comment by pb36** [comment]
Device: Oneplus 5 (Real device)
OS: Android 9
I rooted it using Magisk.

**Comment by pimterry** [comment]
Perfect, that's very helpful, thanks :+1:
