### ISSUE TITLE
Support for WSA adb connection - no more manual connection

### ISSUE THREAD

**Issue by eirikc** [httptoolkit/httptoolkit#327]
If you have a rooted instance of Windows Subsystem for Android (WSA), it works flawlessly with the "Android device via ADB" option in HTTP Toolkit. I've found it's possible to connect WSA to adb by connecting to the localhost address 127.0.0.1 on port 58526. After you've connected the device, HTTP Toolkit will recognize this connection and make the "Android device via ADB" option available. That's awesome!

However it's a hassle having to manually "adb connect 127.0.0.1:58526" each time before using HTTP Toolkit in order to use it with WSA. It would be really useful to have HTTP Toolkit remember this address or something similar, so that I don't have to manually connect to the device each time I use HTTP Toolkit. Pretty small feature to add, but would make the user experience for WSA users a lot better :)

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by eirikc** [comment]
It's possible to connect to WSA with either:
127.0.0.1:58526
{IPV4 address}:58526
localhost:58526

![Screenshot 2022-09-07 160024](https://user-images.githubusercontent.com/73201653/188898608-3b6d423b-0294-4b98-9245-71bcb5ff5920.png)

**Comment by pimterry** [comment]
Interesting ok, so that's enabled by default with WSA? It's just `adb connect 127.0.0.1:58526`, with no other special setup at all?

It's interesting because normal Android devices do also support ADB connection over the network, but they all seem to require a separate pairing step first, which needs manual setup anyway. If that's not required though, and the port is constant, then yes I'm sure it'd be easy to automatically connect to this where it's available.

**Comment by eirikc** [comment]
Here's an[ official guide from Microsoft](https://docs.microsoft.com/en-us/windows/android/wsa/#connect-to-the-windows-subsystem-for-android-for-debugging) mentioning the local host address and the port in question. You might need to enable developer mode in the settings. [Here's another guide](https://docs.microsoft.com/en-us/windows/android/wsa/#connect-to-the-windows-subsystem-for-android-for-debugging) that is a bit more detailed. No pairing setup, you just have to allow the connection on the device just like any other adb connection.

Of course, for HTTP Toolkit to work properly you will need root permission on the emulated device. For WSA this can be done with [this method](https://github.com/LSPosed/MagiskOnWSALocal). 😄

**Comment by pimterry** [comment]
An experimental version of this shipped yesterday :smile:. Next time you start HTTP Toolkit it'll update in the background, and then the following run it should auto-connect to WSA if it's available at startup.

Thanks for the suggestion!
