### ISSUE TITLE
Certificate pinning failed!

### ISSUE THREAD

**Issue by jerson-arch** [httptoolkit/httptoolkit#328]
I was intercepting some Android apps, and ran into the error message "Certificate pinning failed!" in the Uber Eats app.
I am trying in many ways but I am not able to intercept the API.
any solution to this would be great...!
Thanks.

**Comment by pimterry** [comment]
Hi @jerson-arch, this likely means that they're using certificate pinning in the app to explicitly ignore your phone's certificate configuration. This complicates things, but it's usually possible to disable it, typically by using Frida.

Have you seen https://httptoolkit.tech/blog/frida-certificate-pinning/? That will walk you through the process. Let me know if you've tried that and you're still having trouble.
