### ISSUE TITLE
[Bug]: Will not open a Fresh Chrome window if you close the first one

### ISSUE THREAD

**Issue by ellierider** [httptoolkit/httptoolkit#330]
### Repro steps

1. Open Desktop App 
2. Click "Chrome" and see a Chrome window open, allow it to load a site
3. Close "Chrome" browser
4. On Intercept tab, notice "Chrome" says "Activated"
5. Click "Chrome" again. It takes you to the View tab, but no Chrome window is available.

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS Version 12.6 (21G115)

### Error screenshot

[Screenshot](https://share.cleanshot.com/6dYD3U)

**Comment by ellierider** [comment]
This also happens for Firefox. Maybe I am missing a way to open a new window?

**Comment by pimterry** [comment]
Are you completely closing the browser process, or just closing all the browser windows? On Mac those are independent, and closing all windows but not the entire application would cause this behaviour.

If you command+tab while this is happening, does it still show Chrome/Firefox as running?

**Comment by ellierider** [comment]
I'm just closing the single Chrome window that was launched after I clicked
the Chrome box. I can successfully command+tab back and forth prior to
doing this.

I think my expectation was that if I closed the Chrome window, httptoolkit
would know it was disconnected and allow me to start a fresh session.

(My original goal was to start a "fresh" instance for testing purposes.
Would it have been better to clear history in that Chrome window instead?)

**Comment by pimterry** [comment]
> I'm just closing the single Chrome window that was launched after I clicked the Chrome box. I can successfully command+tab back and forth prior to doing this.

After you close the window though, can you still command+tab back to Chrome? If so then the process hasn't been closed, even if the window has gone. You can also check the activity monitor to see if it's still running.

If that process is still running, HTTP Toolkit can't start a new one. You need to fully quit the browser process (Cmd+Q) and then it should work correctly.

If it is running then this is certainly a bug, and for some reason HTTP Toolkit isn't detecting the process exiting. I've never seen that myself though, while I am sure that the Mac process not-really-quitting behaviour would trigger what you're describing (and I've fallen into that trap myself too).

> (My original goal was to start a "fresh" instance for testing purposes. Would it have been better to clear history in that Chrome window instead?)

Up to you! Either is fine and effectively equivalent.

**Comment by ellierider** [comment]
Ah, ok I see now! I was just clicking "close" on the single Chrome window,
but the process was still running and I could click it in my Dock to open a
new window. When I truly quit the Chrome process then HTTP Toolkit will
start a fresh one the next time I click "Intercept a fresh independent
Chrome window".  This will work for me moving forward.

However, I do want to note that "Connected Sources" still says it is
connected to Chrome after quitting the Chrome process. Not a blocker for me
though. Thanks for your help, I really find this product useful.

**Comment by pimterry** [comment]
That makes sense, glad this is working for you now.

Yes, the 'Connected Source' pane is perhaps misnamed, it really shows all the clients that have currently sent traffic, i.e. the sources of all the traffic on the View page. There's no possible way to tell who's actually connected unambiguously (you can correctly manually configure any client to proxy all traffic through HTTP Toolkit, but we won't actually know until they send a request, and we won't know when they stop either) but it's the next best thing.

I will look into the Chrome behaviour though, I think it should be possible to allow re-activation to open a new window in the existing process without too much trouble, and that would probably make more sense that just ignoring the click entirely.

**Comment by pimterry** [comment]
A quick update: this behaviour is now changed, so this confusing UX shouldn't happen any more. If you try to launch Chrome (or any other Chromium-based browser) and it's already running, it'll just open a new window in the existing process, so it will always become visible.

Your HTTP Toolkit will update in the background next time it's opened, and the following time everything should work nicely. Thanks for reporting this, and do feel free to open more issues if you run into other bugs or confusing behaviour in future :smile:
