### ISSUE TITLE
![bug](https://user-images.githubusercontent.com/1395704/192087127-d459d747-d0be-4bea-bfdd-6b185f0954ee.JPG)

### ISSUE THREAD

**Issue by lulavc** [httptoolkit/httptoolkit#336]
![bug](https://user-images.githubusercontent.com/1395704/192087127-d459d747-d0be-4bea-bfdd-6b185f0954ee.JPG)

Same here. Every time it launches shows that same screen just like buddy issue mentioned on previous post.

Windows 10 Pro - 21H1 - 19043.1021

--- Launching HTTP Toolkit desktop v1.10.1 ---
INFO: Initialising UI (version a38d9e6daa6ea5856876bf0a38362b75b176cef3)
INFO: Account store created
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
(node:8452) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
    Error: The specified module could not be found.
    \\?\C:\Users\lula\AppData\Local\httptoolkit-server\client\1.10.2\node_modu
    les\node-datachannel\build\Release\node_datachannel.node
    Code: ERR_DLOPEN_FAILED

_Originally posted by @lulavc in https://github.com/httptoolkit/httptoolkit/issues/335#issuecomment-1256906053_

**Comment by Alokkumar8** [comment]
same problem here. I'm also getting specified module could not be found error.

**Comment by pimterry** [comment]
This was due to a server update that seems to have had some issues on Windows, sorry about that!

I've now rolled back the release, I think that should resolve this, but if you've updated already and you're still hitting this error, you can delete the server update directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.
