### ISSUE TITLE
[Bug]:  HTTP Toolkit hit an error "Server crashed with 'Error: The specified module could not be found (1) "

### ISSUE THREAD

**Issue by sauravh** [httptoolkit/httptoolkit#338]
### Repro steps

My HTTP Toolkit stopped working today. it's saying HTTP Toolkit hit an error "Server crashed with 'Error: The specified module could not be found (1) ". Please take a look error on this screenshot 

https://paste.pics/59df3017010ed6eedcc78be790a57701

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Details of other apps/devices

Windows 11

### Error screenshot

![Screenshot 2022-09-24 210541](https://user-images.githubusercontent.com/1650170/192106666-f6345ef2-7541-44c0-8147-333765da6ee5.png)

**Comment by CookiesNIce** [comment]
I am having same exact problem. I hope developers can fix it as soon as possible.

**Comment by akari-dogman** [comment]
Had this same problem, looked at the closed issues and found this fix that worked for me:
> This was due to a server update that seems to have had some issues on Windows, sorry about that!
> 
> I've now rolled back the release, I think that should resolve this, but if you've updated already and you're still hitting this error, you can delete the server update directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.

https://github.com/httptoolkit/httptoolkit/issues/337#issuecomment-1256941021
