### ISSUE TITLE
[Bug]: Server Crashed with' error: The specified module could not found.' (1).

### ISSUE THREAD

**Issue by cjakashh** [httptoolkit/httptoolkit#339]
### Repro steps

See the screenshot

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

https://prnt.sc/pERd9rlb7W-q

**Comment by akari-dogman** [comment]
Had this same problem, looked at the closed issues and found this fix that worked for me:
> This was due to a server update that seems to have had some issues on Windows, sorry about that!
> 
> I've now rolled back the release, I think that should resolve this, but if you've updated already and you're still hitting this error, you can delete the server update directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.

https://github.com/httptoolkit/httptoolkit/issues/337#issuecomment-1256941021
