### ISSUE TITLE
[Bug]: The specified module could not be found

### ISSUE THREAD

**Issue by ItsZeusX** [httptoolkit/httptoolkit#340]
### Repro steps

Every time i open up the application i get that message

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![image](https://user-images.githubusercontent.com/83469994/192117610-9767dfcc-1bde-4e3d-a9a6-6a997fb3c7b9.png)

### Any other info?

I tried older versions but it seems like its a problem with the servers

**Comment by akari-dogman** [comment]
Had this same problem, looked at the closed issues and found this fix that worked for me:
> This was due to a server update that seems to have had some issues on Windows, sorry about that!
> 
> I've now rolled back the release, I think that should resolve this, but if you've updated already and you're still hitting this error, you can delete the server update directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.
https://github.com/httptoolkit/httptoolkit/issues/337#issuecomment-1256941021

**Comment by Alokkumar8** [comment]
ah finally. it worked

> Had this same problem, looked at the closed issues and found this fix that worked for me:
> 
> > This was due to a server update that seems to have had some issues on Windows, sorry about that!
> > I've now rolled back the release, I think that should resolve this, but if you've updated already and you're still hitting this error, you can delete the server update directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.
> > [#337 (comment)](https://github.com/httptoolkit/httptoolkit/issues/337#issuecomment-1256941021)
