### ISSUE TITLE
Allow parameters in GET requests

### ISSUE THREAD

**Issue by MakeShiftArtist** [httptoolkit/httptoolkit#344]
I have an API that accepts parameters in a GET request to filter results, but I can't add parameters without manually entering them in the request url. I'm not sure why this is disabled unless it causes bugs in GET requests.

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @MakeShiftArtist. HTTP Toolkit definitely supports query parameters, they're very widely used.

Can you provide a detailed steps so I can reproduce the issue you're seeing? You can use https://httpbin.org/anything to see what exactly is being sent - that site will echo the full details of the request back to you, and you can see the query params in both the `url` and `args` properties (for example: https://httpbin.org/anything?testParam=testValue)

**Comment by MakeShiftArtist** [comment]
Request Body / Parameters is grayed out and says "Not applicable for GET", unless there's something I'm missing

**Comment by pimterry** [comment]
Can you please share a screenshot of the error you're describing, and the steps to reproduce this?

**Comment by pimterry** [comment]
Happy to investigate this further, but please share a screenshot of the error you're describing. In this case that error doesn't sound like it's coming from HTTP Toolkit at all.

In general, request bodies shouldn't be used with GET requests at all - they're technically parseable, but the RFC defines them as semantically meaningless, and in many tools they will break or be treated incorrectly. They are supported by HTTP Toolkit, but it's very possible that some other tool you're using is refusing the send them in this case.

**Comment by MakeShiftArtist** [comment]
I just realized I posted this on the wrong repo, I'm so sorry 😭

**Comment by pimterry** [comment]
Ok, that makes sense then :smile:. No worries!
