### ISSUE TITLE
Auto saves logs

### ISSUE THREAD

**Issue by nhokpro** [httptoolkit/httptoolkit#346]
Add auto-save logs setting for pro members.

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by nhokpro** [comment]
auto save har file when matching condiction, or auto-save in time

**Comment by pimterry** [comment]
Hi @nhokpro, thanks for filing this! I think this is the a very similar request to https://github.com/httptoolkit/httptoolkit/issues/342, is that right?

In that case, the proposed fix would be a type of rule you can create on the Mock page, where you could add a step/setting where all traffic matching that rule would be logged to a HAR file on disk. Would that work for you?

Assuming it's the same, I'm going to close this issue and track that there instead (feel free to :+1: that issue to vote for it) but do let me know here if that wouldn't work well for your case for some reason.

**Comment by nhokpro** [comment]
Hello, how can I set things up, as I don't find the option to save it as a file?

**Comment by nhokpro** [comment]
In the mock page, i don't find any Match -> Then
In then option i don't see any related to save as har file

**Comment by pimterry** [comment]
Yes, this does not exist yet, sorry! #342 is still open, it's a proposal for a possible _future_ solution.
