### ISSUE TITLE
Disable page refresh in main window

### ISSUE THREAD

**Issue by MaximSidorchenko** [httptoolkit/httptoolkit#347]
Working with chome instance is totaly a pain. I refresh chrome page, but sometimes httptoolkit window is occasionally focused and you press `cmd(ctrl) + r` it does refreshes httptoolkit's window and all saved setting are cleared - mocks, etc.  
Feels very frustraiting 

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Ah, that makes sense! Very good point, done: https://github.com/httptoolkit/httptoolkit-desktop/commit/e0bdc72b560257311ca594b4e7fa87bae24907dd. That'll be in the next desktop release, I'll close this issue once that's live.

**Comment by pimterry** [comment]
This was fixed last week in the latest release - v1.12.0. This is part of the desktop wrapper, which _doesn't_ auto-update, so you'll need to download the new version manually, but then everything should work nicely. Thanks for the suggestion, this is a good improvement!
