### ISSUE TITLE
[Bug]: All configured authentication methods failed.

### ISSUE THREAD

**Issue by ValerioZ** [httptoolkit/httptoolkit#348]
### Repro steps

At start of the app this pop up come out:
[Window Title] Error
[Main Instruction] HTTP Toolkit hit an error
[Content] Server crashed with 'Error: All configured authentication methods failed' (1).
Please file an issue at github.com/httptoolkit/httptoolkit.

Nome SO	Microsoft Windows 11 Pro
Versione	        10.0.22621 build 22621
Modello sistema	HP ZBook 14u G6
Tipo sistema	PC basato su x64
Processore	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 2112 Mhz, 4 core, 8 processori logici
Versione/data BIOS	HP R70 Ver. 01.21.01, 27/07/2022
Versione SMBIOS	3.1
Versione controller integrato	82.110

### How often does this bug happen?

Every time

### The desktop OS you're using

Microsoft Windows 11 Pro 10.0.22621 build 22621

### Details of other apps/devices

jdk-11.0.10-19

### Error screenshot

[Window Title]
Error

[Main Instruction]
HTTP Toolkit hit an error

[Content]
Server crashed with 'Error: All configured authentication methods failed' (1).

Please file an issue at github.com/httptoolkit/httptoolkit.

[OK]

**Comment by pimterry** [comment]
That's very interesting! Do you have a DOCKER_HOST or any other Docker env vars configured on this machine?

I haven't seen this before, but my best guess is that the Docker library we use has detected from your config that you have Docker running over SSH somewhere, and it's connecting to the engine so it can check if you launch any Docker containers with interception enabled, but the authentication there is failing and we're not handling it.

**Comment by pimterry** [comment]
I did some testing myself, and some SSH URLs were indeed capable of crashing HTTP Toolkit at startup if they were set in the `DOCKER_HOST` env var.

HTTP Toolkit's current Docker interception doesn't actually work with remote engines over SSH yet anyway, so for now host configuration like this will now be ignored entirely. In the latest release, this should be resolved. I'll close this now, but do let me know if you're still having issues.
