### ISSUE TITLE
Blank window at startup

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#349]
> I just tried installing on a new MacBook Air (M2). When I open the app I see nothing but a blank window. There are no messages in the devtools console. I do not have firewall on

_Originally posted by @heswell in https://github.com/httptoolkit/httptoolkit/issues/245#issuecomment-1285240543_

**Comment by pimterry** [comment]
@heswell can you reproduce this and then share your logs? There available in the menu, from Help -> View HTTP Toolkit Logs.

My best guess is that this is happening because you don't have connectivity to `app.httptoolkit.tech`, which will block the app UI from loading on the first startup (you don't need connectivity later, but you do on first run).

**Comment by heswell** [comment]
you're right about the cause. I wasn't online, didn't realize it was necessary. . Now its fine.

**Comment by pimterry** [comment]
Ok, great! Yes, initial network connectivity is required. It's rarely a problem, since it's a networking tool and so for most use cases it's not useful when you're not online, but I'm sure there's cases where that's not necessarily true or you only have local network connectivity or similar.

I've added a proper warning message when this happens in https://github.com/httptoolkit/httptoolkit-desktop/commit/e55b377fdb36d571b6f313a73a291d04f701c18d that should make it clearer why this is happening in future.
