### ISSUE TITLE
[Bug]: Failing to load with 'Server shutdown unexpectedly with code 1

### ISSUE THREAD

**Issue by timeades** [httptoolkit/httptoolkit#351]
### Repro steps

1. Open desktop app

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS Ventura 13 (22A380)

### Details of other apps/devices

Other apps open:

Brave
Chrome
Safari
VSCode
Teams
Outlook
Terminal

I have tried closing everything and trying to launch but have the same issue

### Error screenshot

<img width="271" alt="Screenshot 2022-10-28 at 11 01 33" src="https://user-images.githubusercontent.com/13002711/198561196-19ed20ab-8090-4f15-ac88-3339bb011227.png">

### Any other info?

Everything was working fine before the upgrade to MacOS 13

**Comment by pimterry** [comment]
Is it possible to access the menu when this crashes, before the app exits? If so, can you share the logs? They're available in Help -> View HTTP Toolkit Logs. That should provide some clues about what's going on here.

**Comment by timeades** [comment]
@pimterry I'll try and grab them in the meantime I just got a better crash screen 
<img width="1467" alt="Screenshot 2022-10-28 at 11 13 22" src="https://user-images.githubusercontent.com/13002711/198563602-96a49423-07b7-4431-a565-a2fa75898b9f.png">

**Comment by timeades** [comment]
I deleted the app and downloaded latest and all is working again

**Comment by pimterry** [comment]
Huh, ok. That's very odd. I'll close this for now then, since it's resolved for you & there's no more we can do in the meantime. If anybody else hits this issue in future though, do please share the logs from the failing app here so we can investigate it further!
