### ISSUE TITLE
[Bug]: Your connection is insecure

### ISSUE THREAD

**Issue by AshishP1112** [httptoolkit/httptoolkit#368]
### Repro steps

Whenever I tried to find the API from application using HTTP toolkit then getting error. this issue happening due to certificate or what don't know. There is no any issue in app because of when I disconnect the HTPP toolkit then I will get data in APP and app will be work. So, May I know what is exact issue in this ? 

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/112385154/207051776-c57ce351-5084-489b-8eaf-dea677b92064.png">

![image](https://user-images.githubusercontent.com/112385154/207054725-5e7a426c-70c1-4700-a929-188de5913568.png)

### How often does this bug happen?

Every time

### The desktop OS you're using

Window 11

### Details of other apps/devices

I am using memu play emulator to open the App in window system.

### Error screenshot

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/112385154/207052390-03ea4e4f-db0e-4fc7-8e6b-912268f7cb05.png">

**Comment by pimterry** [comment]
If you look at the HTTP Toolkit Android app, while it is connected, does it show system interception as being enabled?

It should look like this:

![image](https://user-images.githubusercontent.com/1526883/207063940-c0bd6870-ccbc-425e-8d87-b25a57be4bd5.png)

If system interception isn't enabled, then you'll need to either enable that (usually this means allowing root access to the emulator and using setup via ADB) or you'll need to modify the app to trust your certificates regardless (see docs [here](https://httptoolkit.com/docs/guides/android/#if-you-dont-have-a-custom-network-security-config)).

If system interception is enabled, then this usually means that the app is using certificate pinning. There's a guide to this here: https://httptoolkit.com/blog/frida-certificate-pinning/.

If you have more questions, I'd suggest taking a close look through the [Android guide](https://httptoolkit.com/docs/guides/android/) which should cover all of this. There's also a complete walkthrough on the blog here: https://httptoolkit.com/blog/inspect-any-android-apps-http/
