### ISSUE TITLE
[Bug]: cannot update or uninstall on Windows

### ISSUE THREAD

**Issue by jeffrson** [httptoolkit/httptoolkit#373]
### Repro steps

I installed v1.12.0 - now I cannot update or uninstall it.

The uninstaller (run via "all programs" or directly from installation directory) keeps saying that Http Toolkit is running and needs to be stopped manually. However, it is not running at all.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![image](https://user-images.githubusercontent.com/9551280/210177551-7e2ac05e-3c20-4a0d-946b-089ddaefc93c.png)

![image](https://user-images.githubusercontent.com/9551280/210177563-b86d770f-9d39-4cfd-afce-9488d5dff906.png)

**Comment by pimterry** [comment]
Hmmm, that's very unusual. I haven't seen this before, thanks for reporting the issue!

Are you sure there's no Httptoolkit.exe process running at all? There's also a separate server node.exe process, maybe that's been left running somehow? This error message isn't shown by HTTP Toolkit directly, so it must either be coming from our installation framework or the OS itself.

I assume if you reboot the computer, this goes away?

**Comment by jeffrson** [comment]
It happened with 1.12.0, even after reboot. When I removed it manually (I had to stop node.exe, indeed) I cannot reproduce it with 1.12.2 anymore.

I did not retry with 1.12.0 though (does not make much sense).

As far as I'm concerned this issue may be closed.
