### ISSUE TITLE
Angelkrejcu2


### ISSUE THREAD

**Issue by AdminIT-arch** [httptoolkit/httptoolkit#375]
---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @AdminIT-arch, I have no idea what this means. Can you share more information about what you're looking for or what issues you're having?
