### ISSUE TITLE
Grouping and naming mock rules

### ISSUE THREAD

**Issue by ptrckSTL** [httptoolkit/httptoolkit#382]
It would be helpful if I could group my own rules together in the same way that the "Default rules" are grouped together. Additionally, it would be nice if I could give rules a custom name so I could identify them without inspecting their properties.

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
This is not documented (I'll look at that shortly too) but it is supported: drag one rule on top of another and they'll form a group. You can also repeat to create subgroups (to arbitrary depths) and use the buttons shown on hover to enable, disable, clone or delete groups en masse.

You can't name individual rules, but you can name groups (a pen icon appears next to the name on hover). Does that work for your case, or is it that you want to specifically name each individual rule?
