### ISSUE TITLE
[Bug]: spawn C:\Program Files\OpenSSL-Win64\bin ENOENT

### ISSUE THREAD

**Issue by bribes** [httptoolkit/httptoolkit#386]
### Repro steps

1. Open app
2. Then it errors `spawn C:\Program Files\OpenSSL-Win64\bin ENOENT`

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Details of other apps/devices

- 64 Bit Operating System

### Error screenshot

![image](https://user-images.githubusercontent.com/52789876/216827098-fd9a87a9-1fb8-4457-a83e-b193c160c6e7.png)

**Comment by pimterry** [comment]
Interesting! Yeah that's a weird one. I suspect this is coming from an unusual environment variable configuration, which for some reason is affecting how HTTP Toolkit starts its server internally.

For reference, the failing code must be [here](https://github.com/httptoolkit/httptoolkit-desktop/blob/f962d0d18893f89cfbd6be1bbb4664bd7b489ea0/src/index.ts#L381-L402) though that doesn't show me any obvious clues.

It would be useful to check your environment variable configuration. Can you please open a Windows command line, and run `SET > env-vars.txt`? That will save all your environment variables into that file. Please check there's nothing sensitive in that env-vars.txt file (there shouldn't be, but it's worth checking for yourself) and then share it here, hopefully that will have some clues.

**Comment by shirshak55** [comment]
@pimterry maybe if he runs httptoolkit from command line it will give more useful informations?

**Comment by pimterry** [comment]
Yep, certainly worth a shot! You can also check the logs, they're visible in the menu under Help -> View HTTP Toolkit logs.

**Comment by bribes** [comment]
> Interesting! Yeah that's a weird one. I suspect this is coming from an unusual environment variable configuration, which for some reason is affecting how HTTP Toolkit starts its server internally.
> 
> For reference, the failing code must be [here](https://github.com/httptoolkit/httptoolkit-desktop/blob/f962d0d18893f89cfbd6be1bbb4664bd7b489ea0/src/index.ts#L381-L402) though that doesn't show me any obvious clues.
> 
> It would be useful to check your environment variable configuration. Can you please open a Windows command line, and run `SET > env-vars.txt`? That will save all your environment variables into that file. Please check there's nothing sensitive in that env-vars.txt file (there shouldn't be, but it's worth checking for yourself) and then share it here, hopefully that will have some clues.

```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\REDACTED\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=REDACTED
ComSpec=C:\Program Files\OpenSSL-Win64\bin
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\REDACTED
JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot
LOCALAPPDATA=C:\Users\REDACTED\AppData\Local
LOGONSERVER=\\REDACTED
NUMBER_OF_PROCESSORS=16
OneDrive=C:\Users\REDACTED\OneDrive
OneDriveConsumer=C:\Users\REDACTED\OneDrive
OS=Windows_NT
Path=C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Process Lasso\;C:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps;C:\Users\REDACTED\AppData\Roaming\npm;C:\Program Files\heroku\bin;C:\Users\REDACTED\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Process Lasso\;C:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps;C:\Users\REDACTED\AppData\Roaming\npm;C:\Program Files\heroku\bin;C:\Users\REDACTED\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Nmap
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 104 Stepping 1, AuthenticAMD
PROCESSOR_LEVEL=23
PROCESSOR_REVISION=6801
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\REDACTED\AppData\Local\Temp
TMP=C:\Users\REDACTED\AppData\Local\Temp
USERDOMAIN=REDACTED
USERDOMAIN_ROAMINGPROFILE=REDACTED
USERNAME=REDACTED
USERPROFILE=C:\Users\REDACTED
VBOX_HWVIRTEX_IGNORE_SVM_IN_USE=1
windir=C:\Windows
```

**Comment by pimterry** [comment]
The problem is that `ComSpec` variable. [COMSPEC](https://en.wikipedia.org/wiki/COMSPEC) defines the path to your shell, which should normally be something like `%SystemRoot%\system32\cmd.exe`. In your case, it appears to point to a folder, which is almost certainly wrong. Internally HTTP Toolkit is attempting to launch a shell subprocess, and this is why that's failing.

I've checked and on a default install (for Windows 11 at least) it comes set to `C:\Windows\system32\cmd.exe`. If you change that in your system environment variables settings and restart HTTP Toolkit then everything should work correctly.

If for some reason you do need that existing value (though I can't see why you would - I think that is broken in all cases, since it's not a full path to a binary) then you'll need to launch HTTP Toolkit without that env var set, e.g. by opening a terminal, resetting the variable there, and then running HTTP Toolkit directly from that terminal.

Does that work for you?

**Comment by bribes** [comment]
> The problem is that `ComSpec` variable. [COMSPEC](https://en.wikipedia.org/wiki/COMSPEC) defines the path to your shell, which should normally be something like `%SystemRoot%\system32\cmd.exe`. In your case, it appears to point to a folder, which is almost certainly wrong. Internally HTTP Toolkit is attempting to launch a shell subprocess, and this is why that's failing.
> 
> I've checked and on a default install (for Windows 11 at least) it comes set to `C:\Windows\system32\cmd.exe`. If you change that in your system environment variables settings and restart HTTP Toolkit then everything should work correctly.
> 
> If for some reason you do need that existing value (though I can't see why you would - I think that is broken in all cases, since it's not a full path to a binary) then you'll need to launch HTTP Toolkit without that env var set, e.g. by opening a terminal, resetting the variable there, and then running HTTP Toolkit directly from that terminal.
> 
> Does that work for you?

Thank you! This worked I have zero clue why this variable was set to this and it also fixed a lot of other problems I had, Thank you so much.
