### ISSUE TITLE
[Bug]: Server crashed with Error listen EADDRINUSE address in use 127.0.0.1:454

### ISSUE THREAD

**Issue by amjadmoh** [httptoolkit/httptoolkit#390]
### Repro steps

Server crashed with Error listen EADDRINUSE address in use 127.0.0.1:454

### How often does this bug happen?

Every time

### The desktop OS you're using

windows 10

### Details of other apps/devices

using andriod apps
chrome browsers

### Error screenshot

https://ibb.co/Dfftsyc
https://ibb.co/WpbXDmn

**Comment by pimterry** [comment]
Hi @amjadmoh. This means that something is running on your machine and using this port. Usually, this is HTTP Toolkit's internal server, which has not been correctly shut down for some reason. Did HTTP Toolkit crash the last time you ran it?

To fix this, you need to kill the process that's using this port. If you look in process explorer, it may appear under HTTP Toolkit, or as a Node.exe process. Alternatively you can just reboot, which will stop everything. Once that process has closed, HTTP Toolkit will be able to start up successfully again.

**Comment by amjadmoh** [comment]
> Hi @amjadmoh. This means that something is running on your machine and using this port. Usually, this is HTTP Toolkit's internal server, which has not been correctly shut down for some reason. Did HTTP Toolkit crash the last time you ran it?
> 
> To fix this, you need to kill the process that's using this port. If you look in process explorer, it may appear under HTTP Toolkit, or as a Node.exe process. Alternatively you can just reboot, which will stop everything. Once that process has closed, HTTP Toolkit will be able to start up successfully again.

bro iam restarted my server + uninstall http and install it again there is alot of requests

can you plz explaim how to fix it

**Comment by pimterry** [comment]
Oh, sorry, I was just talking about the error message. I don't know where the requests are coming from, that is something else on your machine or in your network that is trying to send traffic to HTTP Toolkit for some reason.

If you have a device that you have configured to send traffic to HTTP Toolkit (e.g. an Android phone that is currently running the HTTP Toolkit Android app, or how the proxy manually configured, or any other computer or device where you've changed the proxy settings) then it will keep sending traffic to your computer until you stop that or change the settings. You need to disable any configuration you enabled on other devices/apps for sending traffic through HTTP Toolkit.

It's not obvious from the traffic there where this is coming from though, as there's a big mix of very different clients, which is quite unusual.

Are you exposing your proxy port on the internet? That could cause this, and you will probably want to disable that ASAP (i.e. you should block access to port 8000 on your computer from the public internet). If you do not then you may find random attackers forwarding traffic through your proxy, which could look like this.

**Comment by abdullah48786** [comment]
> ou can just reboot, which will stop everything. Once that process has closed, HTTP Toolkit will be able to start up successfully again.

How to kill the process?

**Comment by pimterry** [comment]
Hi @abdullah48786, it depends on your system. On Windows, you just need to find the process in Task Manager (look for anything like 'HTTP Toolkit' or 'node.exe') and then right click and choose 'End Task' (or similar, the specific text might depend on your Windows version)
