### ISSUE TITLE
Feature Request - Bulk Export

### ISSUE THREAD

**Issue by Samreay** [httptoolkit/httptoolkit#393]
Right now me and my team are trying to use HTTP Toolkit to effectively mock different data providers. Right now, our code base testing looks like the following:

1. Collect the 500 different endpoints we have to test
2. Download historical data from each of them
3. Validate that our data processing code is compatible with the responses and produces specific output.

Step two can often take a minute per endpoint, and no one wants to spend an hour waiting for unit tests to download the same thing over and over. Enter HTTP Toolkit. By running the tests in a monitored shell, I can collect the urls and responses, and thus use a mocked version of requests to simulate hitting the endpoints with blazing speed.

This is possible right now, but only by manually going through each request, grabbing the path and query, and exporting the result.

It would be great to be able to select mutiple requests (or all of them in one go), and do a bulk export that maps the URL query (keyed on that or a generated UUID) to the response.

**Comment by pimterry** [comment]
Have you tried exporting your traffic as one big HAR? There's a button next to the search bar (the floppy disk/save icon) that bulk exports everything matching your currently entered filters as a single file.

HAR data is just JSON internally, and includes all the details of each request & response. I think with just a tiny bit of scripting you should be able to automatically turn a HAR file into a request path+query -> response map directly. The HAR spec is at http://www.softwareishard.com/blog/har-12-spec/.

Does that work for you?

**Comment by Samreay** [comment]
I did not realise I could dig into a HAR file, this should work perfectly, thanks mate!

**Comment by pimterry** [comment]
Great! Ok, I'm going to close this then, but do feel free to reply here or open a new issue if you're still having trouble.
