### ISSUE TITLE
Feature request - Display response time and size as columns in the request list

### ISSUE THREAD

**Issue by ristomatti** [httptoolkit/httptoolkit#395]
It would be of great help to see the metrics data that's already collected by HTTP Toolkit directly on the list of requests. I'm currently trying to debug occasional slow responses from various backend services but it's quite tedious to peek inside them to see this information as there's quickly hundreds of requests on the list.

Just to be precise, I'm hoping for the data I can already see if I save a HAR file and import to Chrome DevTools:

![image](https://user-images.githubusercontent.com/9029939/226689151-c61738e4-08fd-432f-a3a4-0bd844b5ff01.png)

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @ristomatti, good suggestion! The Chrome dev tools are a useful example as well, thanks.

That said, I am going to close this though, as configurable columns in general are already tracked in https://github.com/httptoolkit/httptoolkit/issues/222, and columns for request timing specifically are tracked in https://github.com/httptoolkit/httptoolkit/issues/90.

I'd definitely like to do this in future anyway, the challenge is that moving from a fixed set of columns to fully flexible configuration isn't as easy as it sounds, and so there's quite a bit of work required there to make this possible! If you'd like to help this move forwards, PRs in this direction are very welcome, the contribution guide is here: https://github.com/httptoolkit/httptoolkit/#contributing-directly

**Comment by ristomatti** [comment]
Sorry I failed to find the existing one, I've upvoted it instead. Great to hear this is planned!

While it would be interesting to give this a shot, realistically it'd take too much of your time answering all the questions I'd have for it to actually be a contribution. :smile:
