### ISSUE TITLE
[Bug] UI Crashes when intercepting large requests

### ISSUE THREAD

**Issue by tcaram** [httptoolkit/httptoolkit#396]
### Repro steps

I'm attempting to intercept a 24MB Javascript file, but upon triggering the breakpoint, the UI becomes unresponsive. Although the UI eventually recovers, any attempt to modify the response results in a crash.

I suspect it might be due to the file being too large, but 24MB should be easily manageable by a machine with 32GB of RAM.

Below is the last-run log:

--- Launching HTTP Toolkit desktop v1.12.3 ---
INFO: Initialising UI (version 3bfc66957c5e0dd017a0df4fad60036580e247a4)
INFO: Account store created
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
(node:21224) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Config checked in 7 ms
Certificates setup in 6 ms
Standalone server started in 5 ms
Server started in 16 ms
Total startup took 34 ms
(node:21224) Warning: Using insecure HTTP parsing
Mock session started, http on port 8000, webrtc enabled
Updating all Docker network aliases...
Connected to Docker
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.12.3)
INFO: Rules store initialized
INFO: Events store initialized
INFO: Interceptor store initialized
INFO: App started, rendering
Webextension installed at C:\Users\tomas\AppData\Local\Temp\httptoolkit-webextension
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.3
Browser cache updated
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.3
INFO: Previous server version was 1.12.3
[4032:9148:0322/104104.897:ERROR:interface_endpoint_client.cc(695)] Message 0 rejected by interface blink.mojom.WidgetHost
Failed to handle request: socket hang up
[4032:9148:0322/104106.753:ERROR:device_event_log_impl.cc(222)] [10:41:06.753] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
[4032:9148:0322/104106.754:ERROR:device_event_log_impl.cc(222)] [10:41:06.754] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[4032:9148:0322/104106.755:ERROR:device_event_log_impl.cc(222)] [10:41:06.755] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
ALERT: UI crashed: The HTTP Toolkit UI stopped unexpected.

Please file an issue at github.com/httptoolkit/httptoolkit.
INFO: Initialising UI (version 3bfc66957c5e0dd017a0df4fad60036580e247a4)
INFO: Account store created
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
Mock session started, http on port 8001, webrtc enabled
Updating all Docker network aliases...
Connected to Docker
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8001
INFO: Proxy store initialized (server version 1.12.3)
INFO: Interceptor store initialized
INFO: Rules store initialized
INFO: Events store initialized
INFO: App started, rendering
INFO: Reporting error: Monaco editor failed to load [object Object]
INFO: Reporting error: Monaco editor failed to load [object Object]
INFO: Reporting error: Monaco editor failed to load [object Object]
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.3
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.3
INFO: Previous server version was 1.12.3
Shutting down after API call...
Uninstalling webextension from C:\Users\tomas\AppData\Local\Temp\httptoolkit-webextension

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

**Comment by pimterry** [comment]
Is it possible to share the specific URL that's triggering this? Or any other public URL you can find that hits the same issue if your specific case is sensitive.

> 24MB should be easily manageable by a machine with 32GB of RAM

Yes, but the likely problem is not storing the response itself - it's the work of processing it. The editor automatically formats all JS code to unminimize it, fully parses it and infers all types recursively for debugging support, and adds corresponding syntax highlighting & error checking etc etc etc. All that comes out of the box from [Monaco](https://microsoft.github.io/monaco-editor/) (the same editor internals as VS Code) and it's very convenient for normal JS, but I wouldn't be surprised if there are parts that scale exponentially in response sizes for both memory and processing in some cases, which would cause this.

If you can share a repro that would be very helpful. I suspect the solution is probably to fall back somehow (e.g. "always treat bodies >X MB as plain text") but concrete examples to confirm where exactly it's failing and test fixes are useful.

**Comment by tcaram** [comment]
> Is it possible to share the specific URL that's triggering this? Or any other public URL you can find that hits the same issue if your specific case is sensitive.

Sure, here's the link (will last for 1 week): https://pastebin.com/mFWev2We

> Yes, but the likely problem is not storing the response itself - it's the work of processing it. The editor automatically formats all JS code to unminimize it, fully parses it and infers all types recursively for debugging support, and adds corresponding syntax highlighting & error checking etc etc etc. All that comes out of the box from [Monaco](https://microsoft.github.io/monaco-editor/) (the same editor internals as VS Code) and it's very convenient for normal JS, but I wouldn't be surprised if there are parts that scale exponentially in response sizes for both memory and processing in some cases, which would cause this.

That would be really nice!

**Comment by tcaram** [comment]
Thank you so much! :-)
