### ISSUE TITLE
[Bug]: Httptoolkit Unexpected behavior and multiple source connection

### ISSUE THREAD

**Issue by spacex97** [httptoolkit/httptoolkit#397]
### Repro steps

1. Open Desktop app

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

Did not start any intercepting

### Error screenshot

![1](https://user-images.githubusercontent.com/56607642/227596427-6f432e77-c18f-4492-b3b4-a8b2aa56ed7c.png)
![2](https://user-images.githubusercontent.com/56607642/227596436-08f23392-2af7-4b6e-8f72-8e68fb25356e.png)

### Any other info?

Hi
I am facing strange issue when running httptoolkit, I have not starting intercepting anything but it starts connecting to multiple dummy source and start using high CPU.
Please check why this is happening and situation is  still worse even after reinstalling app.

**Comment by pimterry** [comment]
This means some clients are genuinely sending traffic through your computer.

Are you exposing your HTTP Toolkit proxy port publicly on the internet? If you're directly connected to the internet (e.g. without a router that blocks incoming connections) then 3rd parties may detect that you're offering a public proxy, and forward their traffic through you (generally for malicious purposes).

You almost certainly don't want to do this - you should not expose your proxy port to the internet without any other security mechanisms.

**Comment by spacex97** [comment]
Thanks for the information I just enabled firewall and its working fine now
