### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Phillip-Dunstall** [httptoolkit/httptoolkit#411]
### Repro steps

It take Too long  load once click on httptoolkit app

### How often does this bug happen?

Every time

### The desktop OS you're using

Ubuntu 23.04 development branch

### Details of other apps/devices

N/A

### Error screenshot

![Screenshot from 2023-04-16 18-52-19](https://user-images.githubusercontent.com/3252950/232332009-e5cf8236-fa30-443e-ba8b-af8a00ac82af.png)

### Any other info?

OS: Xubuntu 23.04 x86_64 
    `yyyyyyyyyyyyyyyyyyyy::yyyyyyyy`       Host: ASUSTeK COMPUTER INC. PRIME B5 
   .yyyyyyyyyyy/+:yyyyyyydsyyy+yyyyy.      Kernel: 6.2.11-060211-generic 
  yyyyyyy:o/yydMMM+yyyyy/M+y:hM+yyyyyy     Uptime: 4 mins 
 yyyyyyy+MMMyymMMMhyyyyyyM::mM+yyyyyyyy    Packages: 2013 (dpkg), 7 (flatpak) 
`yyyyyyy+MMMMysMMMdyyyyydh:mN+yyyyyyyyy`   Shell: bash 5.2.15 
yyyyyyyy:NMMMMmMMMMmmdhyy+/y:yyyyyyyyyyy   Resolution: 1920x1080 
yyyyyyyy+MMMMMMMMMMMMMMMMMMNho:yyyyyyyyy   DE: Xfce 4.18 
yyyyyyyymMMMMMMMMMMMMMMMMMMMMMMyyyyyyyyy   WM: Xfwm4 
yyyyyyy+MMMMMMMMMMMMMMMMMMMMMMMM/yyyyyyy   WM Theme: Yaru-dark 
`yyyyyysMMMMMMMMMMMMMMMMMMMMMMmoyyyyyyy`   Theme: Yaru-purple-dark [GTK2], Yaru 
 yyyyyyoMMMMMMMMMMMMMMMMMMMmy+yyyyyyyyy    Icons: Yaru-purple-dark [GTK2], elem 
  yyyyy:mMMMMMMMMMMMMMMNho/yyyyyyyyyyy     Terminal: xfce4-terminal 
   .yyyy:yNMMMMMMMNdyo:yyyyyyyyyyyyy.      Terminal Font: Fira Code weight 
    `yyyyyy:/++/::yyyyyyyyyyyyyyyyy`       CPU: AMD Ryzen 5 3500X (6) @ 3.600GH 
      `yyyyyyyyyyyyyyyyyyyyyyyyyy`         GPU: NVIDIA GeForce GT 730 
        `.yyyyyyyyyyyyyyyyyyyy.`           Memory: 3181MiB / 31996MiB 
           `.:/oosyyyysso/:.`

**Comment by pimterry** [comment]
Hi @Phillip-Dunstall, can you reproduce this issue and share your logs? You can find them from the menu, under Help -> View HTTP Toolkit logs. That should explain what's blocking startup here.
