### ISSUE TITLE
[Bug]: spawn c:\windows\system32\drivers\etc ENOENT

### ISSUE THREAD

**Issue by C-Hulleman** [httptoolkit/httptoolkit#414]
### Repro steps

1 open on desktop
2 get error message saying:
http toolkit hit an error
spawn c:\windows\system32\drivers\etc ENOENT 
please file an issue at github.com/httptoolkit/httptoolkit
![Screenshot 2023-04-24 172145](https://user-images.githubusercontent.com/123212132/234042057-793bd4a3-4d74-48f6-b7b6-1905c1667597.png)

### How often does this bug happen?

Every time

### The desktop OS you're using

windows 10

### Error screenshot

![Screenshot 2023-04-24 172145](https://user-images.githubusercontent.com/123212132/234042240-90a2eb14-e8ef-4ded-a740-6abf415ccaf5.png)

### Any other info?

deleted it redownloaded it nothing works

**Comment by pimterry** [comment]
Hi @collin05702, this generally means your [COMSPEC](https://en.wikipedia.org/wiki/COMSPEC) environment variable is set incorrectly. Can you check that? On most machines this should be set to something like `C:\Windows\system32\cmd.exe`.

If you change that in your system environment variables settings and restart HTTP Toolkit then everything should work correctly. Having this set wrong may well have broken various other parts of your system too, so it's worth fixing.

See https://github.com/httptoolkit/httptoolkit/issues/386 for more context.

**Comment by pimterry** [comment]
Yes, I think that confirms what I'm saying above. When you try to run `%comspec%`, it tries to run `c:\windows\system32\drivers\etc` which is not a program and is definitely not the correct COMSPEC value.

This is a general configuration issue with your computer - you need to change COMSPEC in your system environment variables to point to `C:\Windows\system32\cmd.exe` and then HTTP Toolkit (and many other things) will work correctly.

**Comment by collin05702** [comment]
I think this is weird cuz wen i do ``set comspec=C:\Windows\system32\cmd.exe`` it will update and then i do ``set comspect`` it wil say this: ``C:\WINDOWS\system32>set %comspec%
Environment variable C:\Windows\system32\cmd.exe not defined```but when i do ``%comspec%`` it wil say ``C:\WINDOWS\system32>%comspec%
Microsoft Windows [Version 10.0.22000.1455]
(c) Microsoft Corporation. All rights reserved.`` af that i will startup my httptoolkit but still get this see screenshot
![Screenshot 2023-04-24 175425](https://user-images.githubusercontent.com/123212132/234050670-20a63cf3-a8e7-44b4-a800-a7dfc03fad38.png)

**Comment by collin05702** [comment]
yes it worked that you for the link i really could not find it thank you so much<3
