### ISSUE TITLE
[Bug]: android - ERR_PROXY_CONNECTION_FAILED on every websites

### ISSUE THREAD

**Issue by MOL0** [httptoolkit/httptoolkit#418]
### Repro steps

1. Start HTTP Toolkit on Android
2. Start chrome and navigate to a website
3. I have ERR_PROXY_CONNECTION_FAILED on all websites

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

I have Android v10 not rooted and on my mobile I use chrome v113.0.5672.77

**Comment by pimterry** [comment]
Hi, can you collect the logs from your device via ADB and share the relevant HTTP Toolkit parts here? You can capture those by running `adb log at -T 1`.
