### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by RORAKUS** [httptoolkit/httptoolkit#427]
Yeah, just add darkmode bruh

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @RORAKUS, thanks for the suggestion. Dark mode is supported already, but it's a Pro feature.

If you already have HTTP Toolkit Pro, you can find it in the Settings, at the bottom under 'Themes'.

If you don't have Pro, do consider signing up to help support the project and fund maintenance & development of more features in future. Pro is also totally free for all open-source contributors to the project, so PRs and other contributions are very welcome too.
