### ISSUE TITLE
need capture an Intercept for specific exe app

### ISSUE THREAD

**Issue by mastiel12** [httptoolkit/httptoolkit#429]
need add function capture and Intercept for specific exe app

**Comment by pimterry** [comment]
Hi @mastiel12. Unfortunately it's not possible to intercept a single exe, but it is possible to intercept your entire computer, and that's probably what you want to do in these kinds of cases.  This will capture all applications, including the one you're interested in. This takes just a few quick manual configuration steps:

To do this in Windows:

- Go to the Intercept page in HTTP Toolkit
- Click the 'Anything' option
- Export your CA certificate using the button shown there
- Change your Windows proxy settings to manually point to HTTP Toolkit, using the instructions here: https://support.microsoft.com/en-us/windows/use-a-proxy-server-in-windows-03096c53-0554-4ffe-b6ab-8b1deee8dae1. The address depends on the port you're using which may vary. This will be shown in the 'Anything' option, and should be http://localhost:8000 by default.
- Tell Windows to trust the CA certificate you exported, by following the steps shown here: https://thomas-leister.de/en/how-to-import-ca-root-certificate/#windows


Once that's done, all Windows traffic will go through HTTP Toolkit, and you'll see everything.

**Remember to disable the proxy setting again when you're done!** If you don't then your internet connection won't work when you close HTTP Toolkit.

Does that work for you?
