### ISSUE TITLE
[Bug]: PHP:  syntax error, unexpected '(' in php-httptoolkit-override.ini on line 9

### ISSUE THREAD

**Issue by kyletaylored** [httptoolkit/httptoolkit#433]
### Repro steps

1. Open desktop app
2. Open Fresh Terminal
3. When opening iTerm2, an initial error shows up in the terminal

```
PHP:  syntax error, unexpected '(' in ~/.local/share/httptoolkit-server/client/1.12.6/overrides/php/php-httptoolkit-override.ini on line 9
```

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS 12.6.3 (M1)

### Details of other apps/devices

Happens every time I open a fresh terminal. I have tried deleting the folder that stores the php.ini override file, and HTTP Toolkit will recreate the file and the error still shows up.

### Error screenshot

<img width="795" alt="image" src="https://github.com/httptoolkit/httptoolkit/assets/1759794/8d9f90b5-154d-4363-b38e-6f815ef96abb">

### Any other info?

There is this block of text that is commented out, and that is where the error line shows. If I delete the comment text, the error goes away (the memory error still persists, but that is a different issue).

**Comment by pimterry** [comment]
Oh, interesting, according to https://www.php.net/manual/en/function.parse-ini-file.php it looks like we're using the wrong comment syntax here - those hashes should be `;`. Very odd! Not sure why that's failing for this specific PHP version and not elsewhere, this definitely works in others.

Regardless though, we should fix it. If you just replace every leading `#` with a `;`, does everything work correctly?

**Comment by kyletaylored** [comment]
Yep! I actually just opened a PR for that 😅
