### ISSUE TITLE
[Bug]: App never loads - GetVSyncParametersIfAvailable() failed for 3 times!

### ISSUE THREAD

**Issue by marcinjahn** [httptoolkit/httptoolkit#435]
### Repro steps

1. Download the Linux version ZIP (https://httptoolkit.com/download/linux-standalone/)
2. Run from terminal with `./httptoolkit`

### How often does this bug happen?

Every time

### The desktop OS you're using

Fedora 38

### Details of other apps/devices

Just launching the app for the first time

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/10273406/a7c9a50b-4c2e-48ca-818b-7069017e573b)

### Any other info?
The app starts just fine when just clicking `httptoolkit` binary in file explorer.

I tried starting the app two times, the log can be seen in the screenshot, or below:

```
❯ ./httptoolkit 
(node:51349) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Config checked in 3 ms
Certificates setup in 73 ms
Standalone server started in 4 ms
Server started in 12 ms
Total startup took 92 ms
(node:51349) Warning: Using insecure HTTP parsing
Mock session started, http on port 8000, webrtc enabled
Webextension installed at /tmp/httptoolkit-webextension
[51341:0614/145612.975422:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[51341:0614/145612.978755:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Browser cache updated
[51341:0614/145614.584450:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.6
^CShutting down after API call...
Uninstalling webextension from /tmp/httptoolkit-webextension

~/Downloads/HttpToolkit-linux-x64-1.12.6 
❯ ./httptoolkit
(node:51735) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Config checked in 3 ms
Certificates setup in 5 ms
Standalone server started in 4 ms
Server started in 17 ms
Total startup took 30 ms
(node:51735) Warning: Using insecure HTTP parsing
Mock session started, http on port 8000, webrtc enabled
Webextension installed at /tmp/httptoolkit-webextension
Browser cache updated
[51726:0614/145738.708979:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.6
[51726:0614/145744.974447:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[51726:0614/145744.978157:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.12.6
```

**Comment by pimterry** [comment]
Is there anything shown in the UI developer console? That's available under View -> Toggle developer tools -> console. For a healthy startup you should see something like:

```
Initialising UI (version 2ffe44f5a589dba97bbeccd5b045b9ae99fd32c6)
Account store initialized
UI store initialized
Proxy settings loaded

Failed to load resource: net::ERR_CONNECTION_REFUSED
Server initialization failed TypeError: Failed to fetch

API store initialized

Failed to load resource: net::ERR_CONNECTION_REFUSED
Server initialization failed TypeError: Failed to fetch

Server started
Config loaded
Server started on port 8000
Proxy store initialized (server version 1.12.6)
Rules store initialized
Events store initialized
Interceptor store initialized
App started, rendering
Service worker loaded
```

I.e. a series of components all initializing, and probably "Server initialization failed" a couple of times until "Server started" appears.

**Comment by marcinjahn** [comment]
I see the following:

```
Initialising UI (version 2ffe44f5a589dba97bbeccd5b045b9ae99fd32c6)
index.js:3529 Account store initialized
index.js:3529 UI store initialized
index.js:3529 Proxy settings loaded
127.0.0.1:45456/start:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
index.js:3529 Server initialization failed TypeError: Failed to fetch
    at admin-client.js:79:30
    at Generator.next (<anonymous>)
    at admin-client.js:8:71
    at new Promise (<anonymous>)
    at admin-client.js:4:12
    at E (admin-client.js:75:12)
    at S.<anonymous> (admin-client.js:332:51)
    at Generator.next (<anonymous>)
    at i (admin-client.js:5:58)
index.js:3529 API store initialized
127.0.0.1:45456/start:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
index.js:3529 Server initialization failed TypeError: Failed to fetch
    at admin-client.js:79:30
    at Generator.next (<anonymous>)
    at admin-client.js:8:71
    at new Promise (<anonymous>)
    at admin-client.js:4:12
    at E (admin-client.js:75:12)
    at S.<anonymous> (admin-client.js:332:51)
    at Generator.next (<anonymous>)
    at i (admin-client.js:5:58)
index.js:3529 Server started
index.js:3529 Config loaded
index.js:3529 Server started on port 8000
index.js:3529 Proxy store initialized (server version 1.12.6)
index.js:3529 Rules store initialized
index.js:3529 Events store initialized
index.js:3529 Service worker loaded
index.js:3529 Previous server version was 1.12.6
index.js:3529 Reporting error: Error: Failed to initialize application
    at index.tsx:148:13
    at Generator.next (<anonymous>)
    at a (app.js?__WB_REVISION__=d10c5d8699fb147567c565a7103f9df9:3419:1034) Object
index.js:3529 Service worker server status: auth-required
```

**Comment by pimterry** [comment]
Ok, so notably "Interceptor store initialized" never appears here - this almost certainly means we're hanging waiting to detect some possible interception target somewhere...

Do you have Docker installed? Any chance it's running but not responsive? That would cause this and I have seen it once before - there's a fix for that ready but not yet released which should resolve this. I was actually planning to cut a release later today anyway, so this might be a very quick fix, if that is indeed the issue.

**Comment by pimterry** [comment]
Ah, ok. I haven't tested with Podman, it's quite possible we'll run into some issues there due to minor differences to Docker, even if it's otherwise working correctly.

HTTP Toolkit tries to connect to Docker by looking for a DOCKER_HOST variable, or for `/var/run/docker.sock` (on Linux) if it's not set. Do either of those point to Podman? It'd be helpful if you could share what Podman version you're using and how it's set up, so I can reproduce and investigate Podman compatibility further.

As a quick fix, you can probably fix startup by breaking that detection explicitly, e.g. with `export DOCKER_HOST=tcp://0.0.0.0:0`.

**Comment by pimterry** [comment]
A new update went out last night, which should resolve this. HTTP Toolkit will pick up the update in the background next time it runs (even if it doesn't start - watch the "httptoolkit-server: Updating CLI..." step) and the subsequent time you shouldn't see this issue.

That will allow you to use HTTP Toolkit itself and all other features, but (assuming the assumptions above are correct) won't allow you to use Docker interception with Podman, because it's not yet supported. That might be possible, I haven't yet investigated it. If that's something you'd interested in, I've created a separate ticket to track demand for the feature that you can :+1: here: https://github.com/httptoolkit/httptoolkit/issues/436

**Comment by marcinjahn** [comment]
It started to work, thanks :)
