### ISSUE TITLE
Libcurl in PHP shows doubled status line

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#442]
_Originally posted by @lkrms in https://github.com/httptoolkit/httptoolkit/issues/420#issuecomment-1603773017_

It may not be relevant, but maybe showing the raw headers would illuminate why I'm seeing headers like this from libcurl in PHP, but only when HTTP Toolkit is intercepting traffic:

1. `"HTTP/1.1 200 OK
"`
2. `"
"`
3. `"HTTP/1.1 200 OK
"`
4. ... then the usual headers.

**Comment by pimterry** [comment]
@lkrms I think this is independent of that other issue, so I've pulled it out - raw header formatting aside, that behaviour definitely sounds weird! Servers shouldn't be able to return multiple 200 responses to a single request, since that's not valid HTTP. Is it possible to share a quick demo so I can reproduce this?

One possibility is that this is libcurl appears to behave weirdly just because it's using a proxy - when proxying traffic, clients send an initial proxy tunneling request (depends on the details, but probably something like `CONNECT real-server:443`), then receive a 200 OK confirming that the tunnel to that server is working, and then send the real request they're interested in (`GET /whatever`) and gets a 200 OK back from that. That would be correct behaviour for HTTP proxying in general, but it certainly shouldn't be reported as a double response to the original request so it's worth checking what's going on here.

**Comment by lkrms** [comment]
Sorry I dropped the ball on this one, @pimterry. I did some digging at the time to check on the particulars of multiple responses per request, including this in the [libcurl documentation] (not mentioned in PHP's documentation):

> It's important to note that the callback will be invoked for the headers of all responses received after initiating a request and not just the final response. This includes all responses which occur during authentication negotiation. If you need to operate on only the headers from the final response, you will need to collect headers in the callback yourself and use HTTP status lines, for example, to delimit response boundaries.

I take this to mean proxy negotiation headers are surfaced along with headers from the final response, so nothing untoward is happening. I've updated my code to discard all but the last set of headers 🙂

[libcurl documentation]: https://curl.se/libcurl/c/CURLOPT_HEADERFUNCTION.html

**Comment by pimterry** [comment]
Ah, that'll do it! Sounds quite unusual, but I supposed it makes sense when using libcurl directly like this.

If you really want to intercept your app with HTTP Toolkit but avoid this issue, you may be able to do so by just redirecting traffic there directly, instead of using it as an explicit proxy. That's unusual, but it's possible, e.g. it's how Android interception works under the hood (redirecting traffic to HTTP Toolkit by rewriting TCP packets directly). You could do that by modifying your source to set the address & host header separately, resolving your target host to HTTP Toolkit's IP & port, or you could do so with iptables trickery, or probably various other advanced setups. HTTP Toolkit will happily intercept & proxy traffic from both explicit proxy tunnels (as here) and transparently, receiving redirected traffic with no such wrappers, and in the transparent case there's definitely only a single status & headers returned.

Or of course, if updating your code like this to just ignore those headers works for you, then that's great too :smile:.

I'll close this now anyway, since it's not an HTTP Toolkit issue. Glad you worked that out, thanks for letting me know.

**Comment by lkrms** [comment]
Thanks for clarifying all of the options! Excellent work as always 😄
