### ISSUE TITLE
Billing is down resulting in disabled pro features

### ISSUE THREAD

**Issue by wongcain** [httptoolkit/httptoolkit#448]
### Repro steps

1. Open the app.
2. Pro features are disabled even though I have an active subscription
3. Clicking on "Get Pro" results in an error

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS Ventura

### Error screenshot

<img width="1478" alt="Screenshot 2023-07-12 at 1 22 46 PM" src="https://github.com/httptoolkit/httptoolkit/assets/6285147/12d60b1c-4dd0-424b-a131-ca27d0487f2a">

**Comment by pimterry** [comment]
Handled by email - this was due to unexpected downtime of the accounts API, now resolved.
