### ISSUE TITLE
[Bug]: Timeout for ADB command on android 8

### ISSUE THREAD

**Issue by btwonion** [httptoolkit/httptoolkit#454]
### Repro steps

1. Open desktop app
2. start intercepting via adb

### How often does this bug happen?

Every time

### The desktop OS you're using

Fedora 38

### Details of other apps/devices

- using samsung galaxy a5 with android 8

### Error screenshot

```--- Launching HTTP Toolkit desktop v1.13.0 ---
INFO: Initialising UI (version 8382e6099859be1a70c2a1576ca531a360cfe080)
INFO: Account store initialized
INFO: Send store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: Server initialization failed TypeError: Failed to fetch
INFO: API store initialized
INFO: Server initialization failed TypeError: Failed to fetch
(node:10087) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
INFO: Server initialization failed TypeError: Failed to fetch
Config checked in 27 ms
Certificates setup in 13 ms
Standalone server started in 10 ms
Server started in 27 ms
Total startup took 78 ms
(node:10087) Warning: Using insecure HTTP parsing
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT /var/run/docker.sock
INFO: Server started
Webextension installed at /tmp/httptoolkit-webextension
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.13.0)
INFO: Rules store initialized
INFO: Events store initialized
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.13.0
Browser cache updated
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.13.0
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
INFO: Previous server version was 1.13.0
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
    at /home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:19689
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async Promise.all (index 3)
    at async A.getRootCommand (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:21574)
    at async A.AndroidAdbInterceptor.injectSystemCertIfPossible (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:27950)
    at async A.AndroidAdbInterceptor.activate (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:25775)
    at async A.ApiModel.activateInterceptor (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:890:747881)
    at async /home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:3505
    at async /home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:2191
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
    at /home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:19689
    at async Promise.all (index 4)
    at async A.getRootCommand (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:21574)
    at async A.AndroidAdbInterceptor.injectSystemCertIfPossible (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:27950)
    at async A.AndroidAdbInterceptor.activate (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:25775)
    at async A.ApiModel.activateInterceptor (/home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:890:747881)
    at async /home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:3505
    at async /home/onion/Downloads/HttpToolkit-linux-x64-1.13.0/resources/httptoolkit-server/bundle/index.js:944:2191
Cert already installed, nothing to do
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ` `

### Any other info?

_No response_

**Comment by pimterry** [comment]
Hi @btwonion. The errors there aren't a problem - those are tests to work out the correct root access mechanism for your device, and if some of them time out it's fine (because two of them do work - they return `root` in the lines above).

After this happens, are you having any specific problems in practice? Or were you just concerned about seeing timeouts in the log files?

**Comment by btwonion** [comment]
no i have the issue that some requests are aborted. i configured my pc and the rooted android phone   as described in the docs.

**Comment by btwonion** [comment]
![image](https://github.com/httptoolkit/httptoolkit/assets/79146501/e36e567b-9f54-4bc8-93f1-e32bf699ad01)
thats what it suggests me

**Comment by pimterry** [comment]
Ok, if system interception is enabled but requests are aborted, that means there's some kind of certificate pinning in place. There's a guide to this here: https://httptoolkit.com/blog/frida-certificate-pinning/

**Comment by btwonion** [comment]
i tried this now, but it doesn't completely solve my problem. the "certificate rejected" is solved, but the login process i want to debug is still not working. 
![image](https://github.com/httptoolkit/httptoolkit/assets/79146501/cec158e8-ce62-447c-9c2c-5056e2584c23)
here you can see how often it retries. normally it should work first try

**Comment by pimterry** [comment]
Hard to say what's going on here I'm afraid. The requests are clearly being intercepted and forwarded correctly now, so everything is working from an HTTP point of view. It's possible the app has other protections in place, in which case you'll need to reverse engineer that further.

There's a guide to reverse engineering in general here: https://httptoolkit.com/blog/android-reverse-engineering/. You may be able to find more clues about what's going on and where to start looking in the Android device logs, you can see this by running `adb logcat -T1` and then triggering the issue.

**Comment by btwonion** [comment]
is it possible, that the server does check for a specific certificate too? because it looks like the request is sent successfully, but look at this response. is there a way to replicate the certificate the app is using? 
![image](https://github.com/httptoolkit/httptoolkit/assets/79146501/5a171700-4616-4415-9e90-565e208ba3ea)

**Comment by pimterry** [comment]
> is it possible, that the server does check for a specific certificate too?

It is possible, but it's hard to know if that's happening. Regardless it's fairly unlikely though - most servers who use certificates for authentication would reject an unrecognized client explicitly with an error when it connected, without sending a full response at all.

That data looks like binary data, but it's not encrypted or anything, because you can clearly read values within it. Unfortunately it's hard to say more, you'll need to work out what format it is and then decode it accordingly somehow.

**Comment by btwonion** [comment]
the accept encoding header says gzip. i tried to put it into an encoder earlier but it didnt work because of special characters.

**Comment by pimterry** [comment]
The accept header tells the server what the client supports, but not what the actual data is - the server is free to return whatever formats it likes.

The response headers should tell you what the data is, although not all servers are helpful about that. HTTP Toolkit will automatically handling encodings (i.e. compression) for you when properly set in the `content-encoding` header, i.e. if the data is gzipped with the correct header, you'll see the ungzipped data in the body here automatically, not the compressed data. HTTP Toolkit won't do anything particularly special with content formats though, as set in the `content-type` header - all that does is add formatting & highlighting for recognized types like JSON/XML etc, but still shows you the same data.

If there's no clues in the headers, I'd recommend viewing the body as hex, and then comparing the first bytes to the list here: https://en.wikipedia.org/wiki/List_of_file_signatures. That may give you clues for most common formats, e.g. gzipped data (that hasn't already been unwrapped automatically) will always start with `1F 8B`.

**Comment by btwonion** [comment]
the request and response doesn't match any of the signatures named in the list. maybe it's simply bytecode...
