### ISSUE TITLE
[Bug]: Websocket messages not saved in HAR file

### ISSUE THREAD

**Issue by mdp901** [httptoolkit/httptoolkit#461]
### Repro steps

1. Open the Desktop App
2. Intercept Websocket traffic
3. Click Save to export changes as a HAR file.

The websocket messages are not saved to the HAR file.

Saving messages for each websocket connection does work, but that can be quite tedious when there are many websocket connections.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

**Comment by pimterry** [comment]
Good point! This should be quick to add I think. What tool are you using elsewhere to access this info? By default I'd follow Chrome's export format (poorly documented, but discussed here: https://developer.chrome.com/blog/new-in-devtools-76/#websocket) but it would be useful to test that with whatever else might integrate with this.

**Comment by mdp901** [comment]
Chrome's export format would be fine.

**Comment by pimterry** [comment]
> Chrome's export format would be fine.

Great! That's now live - both import & export.

Next time you run HTTP Toolkit it'll update in the background within 30 seconds or so, and then following time this should all work correctly. Thanks for reporting this! Do let me know if you have any other issues or feedback.
