### ISSUE TITLE
Need a way to multi select requests to mock

### ISSUE THREAD

**Issue by arpitbatra123** [httptoolkit/httptoolkit#469]
I am working for data-entry on a website that is poorly coded and has a very long frustrating response times for all it's assets. 
I am using HTTP toolkit here as a caching proxy.
I want to add multiple assets ( images, js etc.) into the mock rules, therefore I need a way to multi select and add them to the mocking menu at once.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Totally agree this is a good idea. I think this is already covered by https://github.com/httptoolkit/httptoolkit/issues/76 though, so I'm going to close this as a duplicate for now. You're welcome to :+1: to vote for that issue, or subscribe to it via GitHub to hear once that's available.
