### ISSUE TITLE
[Bug]: HTTP Toolkit hit an error

### ISSUE THREAD

**Issue by bittarr** [httptoolkit/httptoolkit#471]
### Repro steps

Server crashed with '    Error: listen EADDRINUSE: address already in use 127.0.0.1:45456' (1).

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS 12

**Comment by pimterry** [comment]
Hi @bittarr, this means that something is running on your computer and using the port that HTTP Toolkit needs.

To fix this, you need to stop that program running. There's two possibilities: it could be some other unrelated program, or it could be that HTTP Toolkit's internal server didn't shut down correctly the last time you ran HTTP Toolkit.

To find out which process is using the port, you can run `lsof -i tcp:45456` on the command line. Then you can shut that down either from the activity monitor or directly with `kill <pid>` (or `kill -9 <pid>` if that doesn't work and you want to force the program to _immediately_ shut down).
