### ISSUE TITLE
Add tools for sending & resending HTTP requests

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#48]
Would be useful to have something like Postman built-in, so you can send requests (intercepted & recorded automatically). Useful for resending other intercepted requests, and manually testing out API queries for yourself too.

Lots of potential more complex options here (post any ideas below!) but a simple initial version plus a "rerun request" button next to intercepted traffic should be easy & immediately useful.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Feedback by email: once this is available, it would be really useful to be able to re-send requests with the absolute minimum friction for quick testing, e.g. with a single keyboard shortcut when a request is selected. Fiddler uses 'R'.

**Comment by pimterry** [comment]
A useful reference UI, from another issue (#367) suggesting this:

![Screenshot of a dropdown showing the resend option](https://user-images.githubusercontent.com/1526883/207065361-40c974d3-922e-4cda-b53f-2e6aad11097c.png)

**Comment by m7mdcc** [comment]
Any update ?

**Comment by pimterry** [comment]
Not yet I'm afraid.

Adding :+1:s to the issue to vote for this are helpful to manage prioritization, and if you're interested in accelerating this then PRs towards it are very welcome. I think the first step is adding a "send HTTP request" API to [the server](https://github.com/httptoolkit/httptoolkit-server/).

**Comment by shirshak55** [comment]
I, currently,use httptoolkit copy as curl and post it in postman. It would be nice if it was easy.

**Comment by pimterry** [comment]
This is now live! Check out the new Send tab to start writing & sending your own HTTP requests directly, or click the Resend icon in the footer (or press Ctrl/Cmd + R) when any request is selected on the View page to edit and resend requests from intercepted traffic.
