### ISSUE TITLE
[Bug]: Error: API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config

### ISSUE THREAD

**Issue by LaserSlime** [httptoolkit/httptoolkit#480]
### Repro steps

HTTP Toolkit refuses to start with this error message. If I reinstall httptoolkit and manually delete all leftover files it seems to be fixed at first but as soon as I restart httptoolkit, it happens again. I noticed that one of the node.exe processes continues running in task manager after closing it, not sure if that's intentional. All I know is that manually killing it doesnt help. Restarting my entire pc also didnt fix it. 
I think this started happening after I installed a bunch of other http proxies. I did this because for some reason httptoolkit would prevent the app I was intercepting from downloading some files. The downloads would just get stuck, so I tried other random programs like burp, charles, mitmproxy and requestly. I have uninstalled all of them now since I couldnt get any of them to work, but the fact that this seems to have happened only after I installed them I feel like it could be related.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10 22H2

### Error screenshot

![Screenshot 2023-10-04 201843](https://github.com/httptoolkit/httptoolkit/assets/76707643/84c18279-276e-401f-b9e7-1c9ec0001fcc)

### Any other info?

The strange part is that everything works fine on my laptop. Httptoolkit starts properly and files download correctly. Only my pc is cursed. This is why I believe the other proxies are potentially a cause since I only tried those on my pc.

Btw here are the logs:
```
--- Launching HTTP Toolkit desktop v1.14.3 ---
INFO: Initialising UI (version 504213ce08f02af2c7faec2e9681e7dbabf3874d)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
Config checked in 31 ms
Certificates setup in 7 ms
Standalone server started in 5 ms
Server started in 15 ms
Total startup took 58 ms
(node:3764) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT //./pipe/docker_engine
INFO: Server started
ERROR: [object Object],[object Object]
INFO: Reporting error: Error: API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config [object Object]
Webextension installed at C:\Users\User\AppData\Local\Temp\httptoolkit-webextension
ERROR: Uncaught (in promise) Error: API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config
ERROR: Uncaught (in promise) Error: API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.4
INFO: Previous server version was 1.14.3
Shutting down after API call...
Uninstalling webextension from C:\Users\User\AppData\Local\Temp\httptoolkit-webextension
```

**Comment by ristomatti** [comment]
Same issue. Tried clearing the cache dirs under `~/.cache/` as well. It worked fine an hour ago.

**Comment by ristomatti** [comment]
@LaserSlime See #481.

**Comment by ristomatti** [comment]
Solution https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1747460991.

**Comment by LaserSlime** [comment]
> Solution [#481 (comment)](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1747460991).

None of those folder exist for me. I'm on windows.
