### ISSUE TITLE
[Bug]: Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

### ISSUE THREAD

**Issue by ChiefG** [httptoolkit/httptoolkit#498]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open Httptoolkit

( Windows )
after:
"Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"
Please [file an issue](https://github.com/httptoolkit/httptoolkit/issues/new), and we'll get this fixed ASAP"

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![grafik](https://github.com/httptoolkit/httptoolkit/assets/16936132/183fdf17-83db-402f-8841-e803caec253a)

**Comment by daniel-kehlibarov** [comment]
Got the same in Ubuntu, latest version. Tried downgrade, no luck.
