### ISSUE TITLE
[Bug]:When my pc shut down due to power loss I was Debugging but when I restarted my pc HTTPTOOLKIT has damaged I tried uninstalling and then reinstallled.

### ISSUE THREAD

**Issue by allcpu** [httptoolkit/httptoolkit#499]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

While debugging if pc is stop due to power loss the HTTPToolkit seam to get damaged
I even tried uninstalling and re installing
The error is : Server shutdown unexpectedly with code 1.

### How often does this bug happen?

Every time

### The desktop OS you're using

windows 7

### Details of other apps/devices

I was debuging my apk for api request on samsung j7 max by using QR code

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/83278718/470ce534-9e17-4fdf-953a-26599f8d7ec1)

### Any other info?

Please provide me some solution

**Comment by pimterry** [comment]
Can you share your logs after this error? They've available from Help -> View HTTP Toolkit logs, by default they're stored on disk at `C:\Users\<username>\AppData\Roaming\httptoolkit\logs\last-run.log`. That should have more clues about what's failing here.

**Comment by allcpu** [comment]
I Have resolved the problem by doing this changes : 
 1) Uninstalled HTTPtoolkit
 2) Manually delete HTTPtoolkit folders in the appdata ( 3 folders )
 3) Uninstalled the Nodejs
 4) Used HTTPtoolkit portable version (zip).
Problem was resolved after I uninstalled nodejs and deleted the folders of HTTPtoolkit in appdata.
