### ISSUE TITLE
Filter Frame Resize

### ISSUE THREAD

**Issue by drekbad** [httptoolkit/httptoolkit#506]
A simple request, I believe, just to add a resize option to the filtering window in View. After accumulating a mass of hostnames to remove from visibility, the window grows into the space of the actual requests which should be the prominent portion of the UI.

Currently, this can only be achieved by changing the entire application window size or by sliding the requests window on the right, but then further squeezing its space. If a resize option existed for the REQ/RESP frame, this would be less of an issue.

Thank you kindly!
---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Ah, interesting point.

What if the box just only expanded when focused? So it expands as you type, but then when you click away it becomes a single row again, and then re-expands so you can see everything when you next focus it.

> If a resize option existed for the REQ/RESP frame, this would be less of an issue.

You mean the individual sections in the right pane? You can collapse those, which should give you quite a bit more space. Does that not work for you?

**Comment by drekbad** [comment]
Perfecto! That is a great idea, and honestly more efficient than what I was trying to describe. And I did know about collapsing, but if I'm taking screenshots, for example to fit both the REQ and RESP in the same window, it's just easier than taking two separate ones. But it's not a big thing, especially with being able to minimize them. Ideally, a way to have them pop into a side by side panel would be great for screens, but again, it's so easy to just take multiple screenshots that it's not a big deal.

Thank you for the quick response!
