### ISSUE TITLE
More versatile "clear" functionality

### ISSUE THREAD

**Issue by ncovercash** [httptoolkit/httptoolkit#508]
I'd love a way to clear only some rows, rather than all, from the view pane!  Something as simple as "clear all rows above" in the right-click menu would be great; I frequently run into cases with hundreds or thousands of requests and, once I find the section I want to focus on, it can sometimes be difficult to focus on it with all the other requests there.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @ncovercash thanks for the suggestion. If it was possible to do multiselection and batch deleting (#76) with standard shortcuts, would that work for you?

E.g. you could click a row, hold shift-up to select multiple rows (or shift-pageup to select bigger groups, or maybe shift-home to select right to the start) and then you could delete those in one go.

**Comment by ncovercash** [comment]
> Hi @ncovercash thanks for the suggestion. If it was possible to do multiselection and batch deleting (#76) with standard shortcuts, would that work for you?
> 
> 
> 
> E.g. you could click a row, hold shift-up to select multiple rows (or shift-pageup to select bigger groups, or maybe shift-home to select right to the start) and then you could delete those in one go.

Sure! That sounds good

**Comment by pimterry** [comment]
Thanks! I've left a note covering this explicitly on that other issue.

I'm going to close this for now, and track batch deletion improvements there as part of multi-selection in general. You can subscribe to that issue for updates once this is available.
