### ISSUE TITLE
Open the packet capture app and there is no internet connection

### ISSUE THREAD

**Issue by wanghongenpin** [httptoolkit/httptoolkit#512]
https://www.zhihu.com/app/
Hello, other apps can catch it, but when this app opens, it prompts that there is no network. I have already installed the system certificate

**Comment by pimterry** [comment]
Hi @wanghongenpin. Do you see anything in the View page within HTTP Toolkit?

If there are messages there like "Certificate rejected" and "Connection reset" then this probably means that your traffic is being captured, but the app doesn't trust your certificate. Assuming that you do see 'System interception enabled' within the HTTP Toolkit Android app, this most likely means that the app is using certificate pinning. There's more information and solutions to that available here: https://httptoolkit.com/blog/frida-certificate-pinning/. Does that work for you?
