### ISSUE TITLE
[Bug]: Browser is not being detected in Linux

### ISSUE THREAD

**Issue by zyrouge** [httptoolkit/httptoolkit#515]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open HTTPToolkit.
2. Notice that browsers that are loaded in through shell configs (like `~/.profile`) are not loaded.

### How often does this bug happen?

Every time

### The desktop OS you're using

Fedora 38

### Any other info?

I did check `@httptoolkit/browser-launcher`'s command check. The `spawn()` call does have `shell` option set to `true`. Enabling it would run the command in `/bin/sh`. I can make a PR if you are okay with this.

**Comment by pimterry** [comment]
Very interesting! I hadn't thought about that, but yes if you're manually adding to PATH for certain browsers then that would be required, that makes sense.

I'd be happy to accept PRs for this. Do bear in mind that you'll need to make that work without breaking other OSs (I think I've seen Windows particularly do weird things when enabling the shell option). I think if we just use that for detection, then as long as `browser-launcher` is returning absolute paths everything from there on should work nicely as-is.

**Comment by zyrouge** [comment]
I did find the issue and it was because of how non-interactive shells work. They don't invoke `~/.bashrc`. In my case, ZSH invoked `~/.zprofile`. Changing it fixed it. Thanks for your concern though.

**Comment by pimterry** [comment]
Ah, ok, great! Glad that that's working for you now then. Thanks for sharing the explanation here, hopefully that'll help any others who run into the same issue :+1:
