### ISSUE TITLE
[Bug]: Installer and standalone versions do nothing in Windows

### ISSUE THREAD

**Issue by amcsi** [httptoolkit/httptoolkit#517]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Go to httptoolkit.com
2. Click "Download free now" to download HttpToolkit-installer-1.14.7.exe
3. After it's downloaded, double click the file to open the installer.

Nothing happens.

1. Go to httptoolkit.com
2. Click the dropdown next to "Download free now" and choose Windows Standalone Zip to download HttpToolkit-win-x64-1.14.7.zip
3. After it's downloaded, double click the file to open the zip file.
4. Unzip all the files to a new directory.
5. Go to that directory and double click on HTTP Toolkit.exe

Nothing happens.

I'm on Windows 11. There are no error messages or anything.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

https://github.com/httptoolkit/httptoolkit/assets/116494/2c3e713b-4398-4937-b82b-05cd2ede3592

**Comment by pimterry** [comment]
Hmm, hard to say I'm afraid! That installer has been published for a month, and it's used successfully on Windows thousands of times a day, so there must be something strange about your setup here, though it's hard to tell what from the info here.

Do you have any extra security restrictions on your machine? For example enterprise management settings enabled, if this is a work computer?

Is there anything else unusual about this machine?

If you run the installer or the standalone exe from the command line, you might get more info about what's going on here.

**Comment by amcsi** [comment]
Nothing enterprise, it's my home machine.

...that's weird. When launching it from CLI, both the installer and the standalone exe file run properly as one would expect.
And after installing, now it just works if I launch Http Toolkit from the Start Menu.

Anyway, it's good for now.

**Comment by pimterry** [comment]
Huh. That makes no sense, but sure! Glad it's working for you. If you do ever work out what caused this, I'd love to hear about it.
