### ISSUE TITLE
[Bug]: Unable to attach to a JVM

### ISSUE THREAD

**Issue by miroslavvojtus** [httptoolkit/httptoolkit#519]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

I tried both runing from terminal and attaching via attach to JVM.

The target application is running Java 17
JDKs tried: corretto-17.0.9, temurin-17.0.9

I have started HTTPToolkit from terminal where JAVA_HOME is set to one of above JDKs.

 

### How often does this bug happen?

Every time

### The desktop OS you're using

Widnwos 10

### Details of other apps/devices

- intercepting Java 17
- running with Java 17

### Error screenshot

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentLoadException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:670)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:652)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 7 more

Error: Failed to attach to JVM, exit code 1
    at e.JvmInterceptor.activate (C:\Users\z003rt0k\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:82478)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.ApiModel.activateInterceptor (C:\Users\z003rt0k\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:890:742102)
    at async C:\Users\z003rt0k\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:3509
    at async C:\Users\z003rt0k\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:2198
[17380:1114/095738.973:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id 
```

**Comment by pimterry** [comment]
Hmm, that's interesting. I've seen that error before, but normally only when using a much older JDK that doesn't support attachment.

The agent JAR that powers this lives here: https://github.com/httptoolkit/jvm-http-proxy-agent.

Can you test your Java setups against the agent JAR directly? You can download the JAR from the releases in that repo, and then test it by using your JVM of choice to run this command: https://github.com/httptoolkit/jvm-http-proxy-agent#testing-attachment-capabilities.

If that works, HTTP Toolkit should be able to attach to target processes, and something (either HTTP Toolkit or the target app) must be using some other wrong Java somewhere. If that doesn't work then your JVM can't do attachment, and you'll need to use a different JVM that does.

One other option is to skip attachment entirely, and instead open an intercepted terminal, and just launch your process from there. In quite a few environments this is supported while attachment is not.

**Comment by miroslavvojtus** [comment]
I have tried:
```
PS> & "C:\.jdks\temurin-17.0.9\bin\java.exe" "-Djdk.attach.allowAttachSelf=true" -jar ./http-proxy-agent-1.3.4-dist.jar self-test
Agent attach test successful
```

Seems the test passed.

In regards to 

> One other option is to skip attachment entirely, and instead open an intercepted terminal, and just launch your process from there. In quite a few environments this is supported while attachment is not.

At the start of the applicaiton via configured terminal I receive several logs `HTTP Toolkit interception active`. Also the java options seem to be recognized containing the `C:\<APPDATA_LOCAL>\Programs\httptoolkit\resources\httptoolkit-server\overrides\java-agent.jar`. But when I open view of the httptoolkit UI i can see no interceptions. I am sure some endpoints have been hit.

The application is based on _SpringBoot v3_ and running from jar build by _bootJar_ gradle task.

**Comment by pimterry** [comment]
Hmm, that's odd. If it says interception active, that means the agent is injected correctly and it thinks it's capturing the traffic already...

Unfortunately there's no single central way to force a Java process to redirect all HTTP requests, so the JVM agent works by setting every possible central setting, and then hooking each recognized individual HTTP library that's present, to manually add configuration required. There's a list of the supported libraries at the top of the README: https://github.com/httptoolkit/jvm-http-proxy-agent#jvm-http-proxy-agent.

In your case, I assume you're using Spring WebClient to send your requests?

Is it possible to share the target app, so I can run it myself and take a closer look?

**Comment by miroslavvojtus** [comment]
I am not sending requests out from the server. 
I thought httptoolkit captures also incomming traffic.
Am I wrong?

**Comment by pimterry** [comment]
Ah, no, that's not really correct. HTTP Toolkit itself a proxy, which you can use for incoming traffic in theory, but all the automated setup methods are designed to target a client, and capture their outgoing requests.

If you want to see the incoming traffic, you'll generally need to intercept the clients with HTTP Toolkit. Alternatively, you can try manually configuring HTTP Toolkit as a reverse proxy: you'd need to configure clients to use the proxy address instead of the server address, and to trust HTTP Toolkit's CA certificate (if you're using HTTPS) and then add a rule forwarding all received traffic to the real server.

Personally, I'd recommend intercepting clients instead, that's almost always the better approach, and for most cases it's very easy to do.

**Comment by miroslavvojtus** [comment]
We need som way to intercept all incoming traffic on server as we have some unexpected requests and would like to see whats going on. We will find another way around.
Thanks for clarification.

**Comment by pimterry** [comment]
Fair enough! If you do find a good solution, let me know, I'd be interested to hear about approaches that work well here.

For now, I've opened a separate ticket to track intercepting incoming traffic as a possible feature: https://github.com/httptoolkit/httptoolkit/issues/520. I'll keep an eye on the votes that gets, I think it should be possible as an addition in future. Thanks for the idea!
