### ISSUE TITLE
Could you add a Feature that can filter response content

### ISSUE THREAD

**Issue by ddddshop** [httptoolkit/httptoolkit#534]
---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Can you explain a bit more detail about what you mean and how you'd use this?

Note that it is possible to search all responses for specific content, if that's what you're looking for. Take a look at the filtering docs here for more information: https://httptoolkit.com/docs/reference/view-page/#filtering-intercepted-traffic
