### ISSUE TITLE
[Bug]: http://amiusing.httptoolkit.tech/certificate 404 Error - File Not Found

### ISSUE THREAD

**Issue by xilla420** [httptoolkit/httptoolkit#537]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Unable to download certs specifically for iOS device, due to 404 error.
http://amiusing.httptoolkit.tech/certificate

### How often does this bug happen?

Every time

### The desktop OS you're using

All OS

**Comment by pimterry** [comment]
This usually means that you've modified the rules in a way that overrides this request. The rules on the Mock page are evaluated top to bottom, and the injecting your certificate into the intercepted traffic is handled in one of the default rules, in the 'Default Rules' group at the bottom. If you put a rule above it which matches this request, that will take priority. 

Alternatively, if you've deleted the rule that does this then you'll see the same effect.

You can fix this by disabling any other rules that might conflict with this request, or by clicking the trashcan icon in the top right, which will reset the rules completely to the defaults.

One other possibility is that you're not being intercepted at all, in which case this request will indeed fail. You can confirm this by looking at the View page - if your iOS device is being intercepted then you should see the request appear there. If not, you need to check that you've configured the proxy settings on your iOS device before sending the request.

Does that work for you?

**Comment by jendungan** [comment]
This has nothing to do with the interception... the problem is that the location to download the certificate so it can be installed on the devices missing. I am having the same problem... I am following the instructions on https://httptoolkit.com/docs/guides/ios/ and I cannot proceed because I cannot download the certificate to install it to my device.

**Comment by pimterry** [comment]
> This has nothing to do with the interception...

That's not correct @jendungan. This URL is _only_ available when your device is being intercepted, i.e. when it's proxying all its traffic via HTTP Toolkit on your computer.

The certificate is not something you can download from the internet. It's unique to your computer, generated from scratch when HTTP Toolkit is installed, and must be downloaded from your HTTP Toolkit instance to your phone. The `amiusing.httptoolkit.tech/certificate` address is not a real URL on the internet - it's a URL that HTTP Toolkit on your computer can recognize to inject the certificate into the response to send it to you, as long as it's intercepting your traffic at the time.

If that URL isn't loading, it means your proxy settings aren't sending your traffic via HTTP Toolkit. In the iOS case, that probably means you haven't completed the previous step (step 4 on https://httptoolkit.com/docs/guides/ios/ - where you configure your device's proxy settings).
