### ISSUE TITLE
[Bug]: No warning shown when saving a snippet with encoded request body (content-encoding present)

### ISSUE THREAD

**Issue by zb3** [httptoolkit/httptoolkit#546]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Intercept a request which has gzipped body and the content-encoding header present
2. Copy snippet as cURL
3. Observe that the replayed request doesn't have the body gzipped, yet the content-encoding header is there and no warning is shown..

### How often does this bug happen?

Every time

### The desktop OS you're using

Linux

### Details of other apps/devices

This is platform-agnostic

### Any other info?

So yes... I'm a pirate, but if you have any ideas on how I could help resolve this issue, let me know, I'll try to help..

**Comment by zb3** [comment]
Oh, I see this is not a curl-specific issue, it looks like request body encoding isn't supported when copying the snippet but is supported when decoding the request

**Comment by zb3** [comment]
Unfortunately the attached HAR doesn't indicate encoding in any way other than the header which didn't even need to be included (I mean in the adversarial context).
The only way to prove the original request was encoded is to observe that without encoding it, the request fails.
  
Actually, for me, the most important aspect of this was the information that the body should be encoded, because without this I didn't know why the request was failing and I suspected some tls-level protections present which also means I'd spend a lot of time on that if I didn't notice the encoding header..

I mean, since the HTTPToolkit __knows__ that the request was encoded (also notice that this is NOT the same information as the presence of the encoding header(!)), so it should somehow aid the user, and with this comment, I see the reasonable choice 'd be to send the body unencoded, removing the header if it was present.
IMO, sending the encoded body but in a way it's not editable is not only harder, but inferior to your first solution assuming that what people mean by "replay request" is usually "edit and replay" and then it 'd not be obvious how to edit the data returned in the snippet..

To reiterate, I'd not report this bug if the snippet contained a comment about this.

> Lol - yep, that's fine, it's open source, there more-or-less no such thing as piracy in the traditional sense
Oh, it's more than that.. it's kind of art.. as this is probably the first app I can think of that can be (temporarily) cracked from within the user interface without installing anything :D

Of course, I'm not expecting any additional support. The free version is already indispensable, especially the android app which is so easy to setup. Big thanks for that!

Attached HAR: (not redacted but I don't care)
[POST adx.ads.vungle.com.zip](https://github.com/httptoolkit/httptoolkit/files/13976964/POST.adx.ads.vungle.com.zip)

**Comment by pimterry** [comment]
This is now fixed! Next time you run HTTP Toolkit it'll update in the background, and the following time `content-encoding` headers will be automatically omitted from code snippets (i.e. code snippets will always send request body content in decoded format). I briefly looked into actually encoding, but once you start thinking beyond just gzip it gets extremely complicated to do even in just a subset of the different targets, and sending decoded seems like much nicer UX than creating snippets with pre-encoded base64 data or something.

Anyway, this'll do for now and if it causes any issues for people later on we can re-evaluate.

Thanks for reporting this! Glad to get it sorted :+1:
