### ISSUE TITLE
Add script to Mock

### ISSUE THREAD

**Issue by Pbmatch** [httptoolkit/httptoolkit#548]
Hello. It would be nice if you could add a script to handle connections via mock. That is, according to a certain request, a body should come to me. And when it arrives, my script changes it the way I want. You have implemented a pause so that you can edit it, but the connection closes after 10 seconds and during this time you cannot manually change the request. To receive and to send. That is, it would look something like this:
if(url.contains"example1.com")
        {
            List<String> headers = request.getHeaders();
            headers = ...
            request.setHeaders(header);
            String body= request.getBody();
            if(body.contains"text")
            {
            body = .......
            request.setBody(body);
            }

        }
        return request;

**Comment by pimterry** [comment]
It's a good suggestion! I think it's already covered by #37 though, so I'll close this in favour of that (you're welcome to add a :+1: to vote for that, or subscribe via GitHub for notifications once that's available).

In the meantime, it is possible to do your own scripted traffic transformations by:

* Creating a small mock proxy script using [Mockttp](https://github.com/httptoolkit/mockttp/) with rules there defining your custom logic
* Running that proxy server locally
* Configuring the address of that server as your upstream proxy in HTTP Toolkit's settings

Mockttp is the core of HTTP Toolkit's traffic interception & modification, usable as a standalone library designed for scripting use cases. There's a getting started guide here: https://httptoolkit.com/blog/javascript-mitm-proxy-mockttp/
