### ISSUE TITLE
[Bug]: Can't user the pro features anymore 

### ISSUE THREAD

**Issue by buildizer** [httptoolkit/httptoolkit#549]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

While using the desktop application I can't use the pro features it seems that the account information API always returned empty responses for more than 2 weeks now 

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOs

### Error screenshot

<img width="1512" alt="Screenshot 2024-02-06 at 11 36 35 PM" src="https://github.com/httptoolkit/httptoolkit/assets/243731/558de963-ee9f-4cbf-8d8b-4e7b309c5239">

**Comment by pimterry** [comment]
Hi @buildizer, sorry about this issue. I'm not totally sure what's failing here, but I've replied to your separate message by email with more details & questions. I'll close this now, but we can investigate the issue further and work out what's going on by email directly.
