### ISSUE TITLE
Manual setup required on Android 14 (non root).

### ISSUE THREAD

**Issue by Fawn77** [httptoolkit/httptoolkit#554]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Example bug report is when try connecting thru qr code on Android 14 devices even when CA is installed.  Always showing "Manual setup is reqired", even when CA is installed. Detail in screenshot. 

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![Screenshot_20240222_170430_HTTP Toolkit](https://github.com/httptoolkit/httptoolkit/assets/143338659/0011a985-b764-4862-9496-bc40f2b8fa90)

**Comment by pimterry** [comment]
To be clear, you're saying that even after you follow those instructions, it still shows the same message again?

It's hard to know what could cause this I'm afraid. That message is only shown when the Android system tells the HTTP Toolkit app that it doesn't trust the certificate. Are you sure it's definitely installed and it hasn't been disabled or something? It might help to try uninstalling & reinstalling, or rebooting the device.

The relevant code is here: https://github.com/httptoolkit/httptoolkit-android/blob/11c9388a6c48d9766cff7d674328e6fedd5790f2/app/src/main/java/tech/httptoolkit/android/ProxySetup.kt#L170-L198. It queries `AndroidCAStore`, finds every certificate there that matches the HTTP Toolkit cert, and reports whether it's a system or user certificate. If you like you can check the ADB logs (via `adb logcat -T1`) and look for the `Proxy cert aliases: ...` line logged there to check exactly what aliases we find.

**Comment by pimterry** [comment]
> In fact, that error is only showing when my phone is connected in macOS.

Absolutely no idea why that would happen, sorry! This should be totally independent of the computer that's connected - the manual certificate handling is purely something that happens on the phone, the computer isn't involved at all.

Sounds like you've got it working though now, is that right?

**Comment by Fawn77** [comment]
Yeah, its totally fine now on windows. Thanks!
