### ISSUE TITLE
[Bug]: Docker Integration on macOS with Orbstack

### ISSUE THREAD

**Issue by appcoders** [httptoolkit/httptoolkit#564]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Install HTTPToolKit Pro
2. Install OrbStack https://orbstack.dev/ which is a (much faster) drop-in replacement for Docker Desktop on macOS
3. Open a terminal
4. eval "$(curl -sS localhost:8001/setup)"
5. docker run --rm -it nginx
6. -> Error response from daemon: HTTP Toolkit could not connect to Docker

Also the option connect to a running container is greyed out.

### How often does this bug happen?

Every time

### The desktop OS you're using

macOS 14

### Details of other apps/devices

OrbStack + HttpToolkit on macOS 14

**Comment by pimterry** [comment]
Can you share your log file? It's available in the menu under Help -> View HTTP Toolkit logs

In general, HTTP Toolkit detects Docker by trying to connect to a unix socket at `$HOME/.docker/run/docker.sock` and `/var/run/docker.sock`. Those are the standard paths where a normal Docker engine exposes its API. Given the errors, that must be failing for some reason.

It looks like Orbstack can listen on the latter path (https://docs.orbstack.dev/docker/#docker-context-socket) but only optionally - do you have that enabled?

**Comment by appcoders** [comment]
Thanks for the hint. The path /Users/markus/.docker/run/docker.sock exists

I stopped OrbStack, deleted the path, restarted Orbstack and now HTTP Toolkit can connect to docker daemon at 
 /var/run/docker.sock.

So the issue is gone  - only weird that /var/run/docker.sock links to the now non-existing path above, but still, it works...

```
ls -la /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  39 Mar  9 18:19 /var/run/docker.sock -> /Users/markus/.orbstack/run/docker.sock
```

```
--- Launching HTTP Toolkit desktop v1.14.10 ---
Config checked in 8 ms
Certificates setup in 42 ms
Standalone server started in 6 ms
Server started in 20 ms
Total startup took 76 ms
INFO: Initialising UI (version cae42f6e7e492da4280c55503a39c21f5f7c740b)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
(node:21783) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ECONNREFUSED /Users/markus/.docker/run/docker.sock
Webextension installed at /var/folders/bv/39z_k8cn5g38hh5ff_39fktr0000gn/T/httptoolkit-webextension
INFO: API store initialized
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.14.10)
INFO: Interceptor store initialized
INFO: Rules store initialized
INFO: Events store initialized
INFO: Send store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.10
Browser cache updated
ERROR: Uncaught (in promise) #<Event>
httptoolkit-server: Updating CLI... fetching manifest
INFO: Service worker loaded
WARN: Reconnecting Mockttp subscription client
httptoolkit-server: Updating CLI... already on latest version: 1.14.10
INFO: Previous server version was 1.14.10
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.10
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.10

```

**Comment by pimterry** [comment]
When you say the issue is gone - is it that Docker interception now works correctly, or just that it's now skipped entirely and that solves your issue?

Notably the server output says:

> Docker not available: connect ECONNREFUSED /Users/markus/.docker/run/docker.sock

Which makes me think that it was using that path previously, and it's now disabled the Docker integration entirely.

You probably don't want to delete this file, since as you say it leaves you with a dangling symlink, and it will probably break any other Docker integrated tools you use on your machine.

Can you make OrbStack recreate it, and then share the output from HTTP Toolkit's logs in that case? That will probably have some clues that might make it possible to actually make this work correctly with OrbStack.

**Comment by appcoders** [comment]
@pimterry Sorry, the log was misleading as it was from the state before I deleted /Users/markus/.docker/run/docker.sock. Now the log indicates that it's connected to /var/run/docker.sock. 
And I mixed up paths:

/Users/markus/.docker/run/docker.sock   <- HTTP Toolkit tried to connect here 

/Users/markus/.orbstack/run/docker.sock   <- the /var/run/docker.dock symlink points here and exists 

So I must be a leftover of old Docker Desktop installation which mislead HTTP Toolkit to try /Users/markus/.docker/run/docker.sock first.

Sorry for the confusion. And thanks again for your quick reply.

**Comment by pimterry** [comment]
Ah, I see! Ok, yes that makes perfect sense I can see how that would cause this, and how deleting the old socket file would fix it. Glad it's working for you now, thanks for the explanation :+1:
