### ISSUE TITLE
[Bug]: Startup failed: "Unexpected token '', ""... is not valid JSON"

### ISSUE THREAD

**Issue by What-XD** [httptoolkit/httptoolkit#567]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Open the desktop app

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/101012824/dc4d02c8-a562-4335-b9c2-d5b689451f9c)

### Any other info?

Before that, the app was working

**Comment by pimterry** [comment]
Hi @What-XD thanks for reporting this, that's very unusual.

Could you please:

* Open HTTP Toolkit
* Go to View -> Toggle Developer Tools
* Go to the Network tab
* Click View -> Force Reload, and wait until this error appears
* Right click on a request in the Network tab, click 'Save all as HAR with content', and share the HAR here
* Click Help -> View HTTP Toolkit logs, and share the logs here

I'm not sure what could cause this, but hopefully that will provide enough information about what's going on here to clear this up, and then I'll be able to get it fixed for you.

**Comment by johanforce** [comment]
Try pressing "force reload". It helped the app run

**Comment by What-XD** [comment]
It fixed itself on restarting the pc XD
