### ISSUE TITLE
Support external proxies

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#57]
In some environments, it's necessary to use an external proxy for outgoing HTTP traffic. HTTP Toolkit doesn't support this at the moment, but it could if it's valuable for people.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
@erhhung just to reply to [your comment](https://github.com/httptoolkit/httptoolkit/issues/117#issuecomment-810660811) here: that completely makes sense. If you _need_ to use an external proxy with your VPN, then I can see how that'll cause big problems, and how the amiusing page may have trouble given external resources there.

I'd like to look at this sooner rather than later, I think it'd be pretty valuable to get at least a basic option working if there's demand for it.

In practice, that would probably look like a configuration option in the advanced Pro settings where you can manually specify an external proxy for upstream requests. Would that work for you?

**Comment by erhhung** [comment]
@pimterry, if you make such proxy config options only available in the Pro version, then I hope you at least provide a free trial for a certain duration, or else none of your potential enterprise users would even be able to evaluate the software without an outright purchase of a license. It's up to you how you group the features, but I'd consider settings critical to the basic operation of  an application to be baseline features.

For example, I use https://github.com/lensapp/lens pretty regularly, and it has a single preference setting for HTTP external proxies. In your case, though, I'd consider using common libraries to handle the same conventions used in parsing "`http_proxy`", "`https_proxy`", and "`no_proxy`" environment variables.

**Comment by erhhung** [comment]
Another reason why you should not put proxy config only in the Pro version: I just clicked on the "Get Pro" icon in the app and got a giant "**Oh no!**" message (maybe a little too big?)—of course reloading the app didn't help, LOL!

I suppose I could disconnect from the VPN to complete the purchase if I'm home, but if I were in the office, this would be a blocker.

**Comment by pimterry** [comment]
> I'd consider using common libraries to handle the same conventions used in parsing "http_proxy", "https_proxy", and "no_proxy" environment variables

The problem is that in many cases these point to HTTP Toolkit itself, because people configure HTTP Toolkit as their system proxy. If we try to use the system settings, everything breaks as all traffic is now an infinite proxy loop. That's why there's a need for manual configuration, or some other way to detect when the proxy config actually points to us before we start loading or initializing anything.

The latter might be possible though, at least by ignoring system settings only if they're set to point to localhost...

That would be sufficient to ensure the app loads ok. The internal proxy behaviour for intercepted traffic is separate, and that would need more complex work to ensure it can forward traffic through the remote proxy, to avoid showing the 502s that you see today.

> It's up to you how you group the features, but I'd consider settings critical to the basic operation of an application to be baseline features.

In general, the goal is that features only relevant to people working heavily with HTTP professionally or within large enterprises go into the paid bucket (i.e. people who are making money from use of the tool help fund the tool) whilst the essential features for one-off use, and for hobbyists/beginners all stay free. Everything's also free for open-source contributors - if you contribute any feature or non-trivial bugfix, you get a year's free Pro susbcription.

You're right that it's a tricky line for this particular case though. It's clearly an enterprise-only feature, but it's also a complete blocker for initial set up.

I'll have a think about all this and see what I can come up with.

**Comment by erhhung** [comment]
> The problem is that in many cases these point to HTTP Toolkit itself, because people configure HTTP Toolkit as their system proxy.

I didn't mean to read those standard environment variables as, as you said, HTTP Toolkit could be the proxy for CLI apps. I meant to say that you should, at a minimum, have in-app config settings matching those 3 environment variables (which could allow specifying proxy auth, or you can break those into separate fields), AND allow the "no proxy" CSV list to use IPv4/6, host names suffixes, CIDR notations, etc. (see https://docs.docker.com/network/proxy/). You should use a standard library to handle proxy settings because parsing the "no proxy" format can be annoyingly non-standard (see https://github.com/curl/curl/issues/1208).

**Comment by pimterry** [comment]
This is now supported (see lots more discussion in #117). For all users, the system proxy settings will be used by default. Pro users can configure settings for HTTP Toolkit specifically on the Pro settings page.
