### ISSUE TITLE
Web Hook

### ISSUE THREAD

**Issue by alisaitteke** [httptoolkit/httptoolkit#570]
In some cases, there is a need to forward HTTP requests to another URL (not as a proxy). It would be a great addition to the project if there could be a feature where a URL can be specified to forward requests based on matching the URL, domain, or path. Perhaps this could be implemented separately for requests and responses, and including a replacement feature would be fantastic.

**Comment by pimterry** [comment]
Hi @alisaitteke, it depends what exactly you're trying to do, but in many cases this is already possible using the Pro "Forward the request to a different host" option. You can use the rule matching options to control which exactly requests are forwarded.

It's also possible to do this without Pro, by creating a breakpoint and manually editing the URL of requests, which will redirect them accordingly.

These forwarding rules do have some limitations, for example it's not currently possible to modify the path of the request directly. It depends on your use case really, as for many cases that's sufficient, but do let me know if not - any more info you can share about specific use cases and how you'd like the URLs to be rewritten would be very helpful.

**Comment by alisaitteke** [comment]
Hi @pimterry, thanks for your replay and sorry for the confusion in my previous request. What I'm seeking is not request forwarding but the ability to hook and send HTTP requests additionally to another destination based on criteria like URL, domain, or path. A feature for configuring hooks separately for requests and responses, with an optional replacement functionality.

**Comment by pimterry** [comment]
Can you share a complete & specific example? E.g. when a request to `example.com` is received, what should happen next? What exactly should the client & server receive? The more detail the better.

From your description, I'm afraid not really clear where the 'replacement' would apply, and there's a lot of different possible ways this could work.

**Comment by alisaitteke** [comment]
Introducing a "web hook" feature in the Mock & Rewrite HTTP section to facilitate sending copies of responses (or requests) based on match criteria to a specified endpoint, without modifying the original request or response flow, directly addresses the need. For instance, responses to requests made to https://example.com/path could be duplicated and sent to "localhost:3000" in parallel. This would be particularly useful for scenarios requiring traffic logging, monitoring, or real-time data processing for specific paths or domains.

**Comment by pimterry** [comment]
Thinking more about this, I think what you're looking for really is either #342 (a rule to auto-save all requests & responses to a HAR file for logging/monitoring) or #37 (scripting rules, where you can add your own code to handle requests).

In the HAR case, that would mean:

* You add a rule matching the requests you're interested in, and saving their data as a HAR file
* Your client sends requests and receives responses as normal
* You can check the target directory on disk to see HAR data for each request & response, and build any automation you like monitoring that folder, or just use those as persistent traffic logs.

In the scripting case, that would mean:

* You add a rule matching the requests you're interested in, and then write a script there which defines exactly what should happen before & after processing each request
  * For example, you could send a copy of each request to a separate logging server before it's sent upstream to the real target server, and then modify every response from the real target server to add extra headers or remove data from the body
* Your client sends requests and receives responses as normal, but with your modifications applied
* You can your logging server to see all the requests that were sent.

The advantage of the HAR case is that it's much simpler, but for any complex cases where you want to use custom logic the scripting case is much more powerful.

Would one/both of those work for you? If so please add a :+1: vote on the issue for the solution you're most interested in to vote for that.
