### ISSUE TITLE
[Bug]: Apps rejecting HTTK certificate even when it's injected in system CAs (root)

### ISSUE THREAD

**Issue by fidalgobr** [httptoolkit/httptoolkit#592]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

- Install the HTTK certificate in the system certificates in a rooted device
- Use the QR code interception function in the app

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

Xiaomi MI A2 Lite (daisy) running Android 13 (SyberiaOS v6.1)

### Error screenshot

![httk](https://github.com/httptoolkit/httptoolkit/assets/82066907/b368f0b6-caa5-4d04-b0c8-901289b75628)
![image](https://github.com/httptoolkit/httptoolkit/assets/82066907/1f04810f-08a2-4505-acb5-f2ea91d4e9d1)

**Comment by pimterry** [comment]
Hi @fidalgobr. Is HTTPS traffic failing by _all_ apps, or just some of them?

Can you explain more about how you installed the CA certificate? This process is quite complicated nowadays, and doing it manually can be very tricky. If you can, you may want to use the ADB-based setup, which fully automates this for you and should work quite reliably.

**Comment by fidalgobr** [comment]
> Hi @fidalgobr. Is HTTPS traffic failing by _all_ apps, or just some of them?
> 
> Can you explain more about how you installed the CA certificate? This process is quite complicated nowadays, and doing it manually can be very tricky. If you can, you may want to use the ADB-based setup, which fully automates this for you and should work quite reliably.

Hi. Thanks for your response. It's failing in almost all apps (except for those who already work with the user installed certificate). 

I installed the CA as a user and then I mounted the /system folder as RW and moved the certificate file from the users certificates folder to system's. 

I could try the ADB approach, but I'm not sure where to find the program that automates the process. Could please you send me the link?

**Comment by pimterry** [comment]
> I installed the CA as a user and then I mounted the /system folder as RW and moved the certificate file from the users certificates folder to system's.

Ah, yes that generally won't be sufficient. It's now quite significantly more complicated. At the very least you'll need to update permissions & SELinux labels, and on most new-ish Android devices you'll need to think about the APEX certificate configuration too and inject a mount for that into the namespace of basically every running process. If you're interested there's a great deal more detail here: https://httptoolkit.com/blog/intercepting-android-https/

> I could try the ADB approach, but I'm not sure where to find the program that automates the process. Could please you send me the link?

To do this automatically, you just need to connect the device to ADB, then click the "Android Device via ADB" button that will activate in HTTP Toolkit, and it'll handle all the setup for you. The HTTP Toolkit app running on the phone can then confirm the current user or system certificate status directly in the UI there.

All the automated setup just uses temporary mounts, so it'll undo automatically when you reboot your phone. If you want to see exactly how this works up close, the core of the process is here: https://github.com/httptoolkit/httptoolkit-server/blob/1f345cba6693540f31eae54a580ed3f614b2b6c9/src/interceptors/android/adb-commands.ts#L300-L413

**Comment by fidalgobr** [comment]
> > I installed the CA as a user and then I mounted the /system folder as RW and moved the certificate file from the users certificates folder to system's.
> 
> Ah, yes that generally won't be sufficient. It's now quite significantly more complicated. At the very least you'll need to update permissions & SELinux labels, and on most new-ish Android devices you'll need to think about the APEX certificate configuration too and inject a mount for that into the namespace of basically every running process. If you're interested there's a great deal more detail here: https://httptoolkit.com/blog/intercepting-android-https/
> 
> > I could try the ADB approach, but I'm not sure where to find the program that automates the process. Could please you send me the link?
> 
> To do this automatically, you just need to connect the device to ADB, then click the "Android Device via ADB" button that will activate in HTTP Toolkit, and it'll handle all the setup for you. The HTTP Toolkit app running on the phone can then confirm the current user or system certificate status directly in the UI there.
> 
> All the automated setup just uses temporary mounts, so it'll undo automatically when you reboot your phone. If you want to see exactly how this works up close, the core of the process is here: https://github.com/httptoolkit/httptoolkit-server/blob/1f345cba6693540f31eae54a580ed3f614b2b6c9/src/interceptors/android/adb-commands.ts#L300-L413

Ohh, I see. Now it worked. It was my mistake then... Sorry for misreporting a bug! 

And thanks a lot for your support!
