### ISSUE TITLE
[Bug]: Filter descriptions don't consider operator when paired with NOT 

### ISSUE THREAD

**Issue by leumasme** [httptoolkit/httptoolkit#601]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

- Go to View Panel
- Type part of a filter proprty (which has string comparison operations) into the filter textbox, e.g. `host`
  - Observe (A): The different operations e.g. `hostname=` vs `hostname*=` will have different descriptions explaining what the specific operator does (good!)
- Clear the filter textbox; instead type part of a filter inside a `not` operator, e.g. `not(host`
  - Observe (B): The different operations e.g. `not(hostname=` vs `not(hostname*=` vs `not(hostname^=` will all have the same description:
  `Match excluding requests sent to a given hostname` (bad!)
  - The shown description would only be correct for the `=` case 
- Continue writing the filter until the operator part, e.g. `not(hostname*=`
  - Observe (C): The issue remains
- Continue writing the filter until the second operand part, e.g. `not(hostname*=g`
  - Observe (D): The issue disappears, the description now correctly reflects that `*=` means "contains"

Note that this issue does **not** affect the `or(` function - `or(host` correctly shows the different descriptions for each individual 
comparison operator (E)

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

A: ✔️ The Text correctly states that `*=` is for matching "contains" value
![image](https://github.com/httptoolkit/httptoolkit/assets/29953391/5ea51fa5-11af-4c1c-afb9-3d125dde18a3)

B: ❌ The Text does not respect the selected operator `*=`
![image](https://github.com/httptoolkit/httptoolkit/assets/29953391/d0f09bcb-90f6-4878-b53b-d829c4ddaed5)

C: ❌ Typing out the operator, reducing the suggestions to only one, updates the title but the description remains wrong
![image](https://github.com/httptoolkit/httptoolkit/assets/29953391/99d04363-e182-41fa-ab5f-1717e19c49f5)

D: ✔️ Typing until the second operand results in a correct description
![image](https://github.com/httptoolkit/httptoolkit/assets/29953391/4d186d52-6db6-4490-8346-3f47c09bf4a2)

E: ✔️ Using the `or` operator instead of `not` correctly customizes the description to the hovered operator (notice "containing")
![image](https://github.com/httptoolkit/httptoolkit/assets/29953391/41917e67-cf22-481d-8b05-648924593c73)

### Any other info?

HTTP Toolkit Version 1.17.2

There appear to be tests for the `not` filter function here:
https://github.com/httptoolkit/httptoolkit-ui/blob/e0d14f693a040d7818fa4772b1d64d97cf421e2d/test/unit/model/filters/search-filter-integration.spec.ts#L1579-L1586
However none of the tests test for this case
- `not` function
- filter property with string comparison operators
- second operand for the string comparison is not typed yet
- the description is correct for the first result, but identical and incorrect for all further results

**Comment by pimterry** [comment]
Good catch! Thanks @leumasme.

This is now fixed in https://github.com/httptoolkit/httptoolkit-ui/commit/4afb18571adf3fc67d5c191723a89647497d4ee1, which should be live in 10 minutes or so. You'll need to run HTTP Toolkit for a minute, so it updates in the background, and then restart it to see the changes. Thanks for reporting this, that's quite a subtle case I'd totally missed, good find.
