### ISSUE TITLE
[Bug]: Certificate rejected error on Roblox using MuMuPlayer

### ISSUE THREAD

**Issue by Joystickplays** [httptoolkit/httptoolkit#607]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Install MuMuPlayer Android emulator if you haven't 
2. Enable root permissions on the emulator (and allow modifying system directory but I don't think that's important?)
3. Install Roblox
4. Open cmd, make sure ADB is connected with the emu
5. On HTTP Toolkit, intercept using ADB
6. Ensure Both user and system trust are true
7. Try opening Roblox after interception
`Certificate Rejected`

8. On HTTP Toolkit, this time intercept ***with Frida***
9. Try opening Roblox after interception
`Certificate Rejected`

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10, Android 12 (MuMuPlayer 12)

### Any other info?

As stated clearly, I had used ADB and Frida both with the generic certificate pinning removal. Both did not work and still rejecting the certificate.

**Comment by xKiian** [comment]
It's probably due to Roblox having a custom certificate pinning mechanism.

Read more [here](https://medium.com/@mohamed.ma872/securing-android-apps-with-ssl-pinning-techniques-and-implementation-certificate-pinning-and-ffe10fca4be6)
