### ISSUE TITLE
[Bug]: removing Facebook Lite SSL pinning won't work

### ISSUE THREAD

**Issue by Were-Logan-0110** [httptoolkit/httptoolkit#608]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

i tried doing normal android capturing and frida but frida gives unparseable and i tried editing the `networkSecurityConfig` and i did but it still gave certificate rejected

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

MeMu emulator

### Error screenshot

![image](https://github.com/user-attachments/assets/31220b02-9ded-4610-aa9a-5b8e6f91ce24)
It either lags like this or says unparseable

**Comment by Were-Logan-0110** [comment]
> If the traffic appears as a row in HTTP Toolkit (not just a 'connection reset' message) then that means that interception is working and SSL pinning for that request has been disabled.
> 
> If that happens but the traffic within the connection is not parseable, it probably means it's not HTTP at all, in which case unfortunately HTTP Toolkit is not going to be able to help you very much, sorry. If you can share a screenshot of some of the unparseable traffic it might be possible to know what protocol it is using though, or at least to confirm that that's what's happening.

Not really i tried the normal facebook using frida and it still said unparseable but when i tried normal facebook without ssl pinning it showed normally
![image](https://github.com/user-attachments/assets/ca524dde-d968-411b-b34d-43d70558cbe0)

**Comment by pimterry** [comment]
> Not really i tried the normal facebook using frida and it still said unparseable but when i tried normal facebook without ssl pinning it showed normally

"Unparseable" and "unsupported HTTP method" (as shown in that screenshot) are basically the same thing really. The traffic shown there is definitely being decrypted successfully (this is not an SSL pinning problem) but it's not HTTP (or anything else closely related) so HTTP Toolkit can't intercept it. You'll struggle to use any similar HTTP proxy tool for this, and your tooling generally to modify/resend these kinds of requests will be limited. [Wireshark](http://wireshark.org/) may be useful though, since it can show the raw bytes without breaking the connection, so you can inspect the traffic, but that's quite complicated to set up for this kind of thing and you'll need to debug the raw traffic byte-by-byte for yourself.

I'm going to close this, since that's not a pinning problem and it's not HTTP traffic. If you do find a solution, please share it here so anybody else with the same problem can follow in your footsteps!

**Comment by Were-Logan-0110** [comment]
> > Not really i tried the normal facebook using frida and it still said unparseable but when i tried normal facebook without ssl pinning it showed normally
> 
> "Unparseable" and "unsupported HTTP method" (as shown in that screenshot) are basically the same thing really. The traffic shown there is definitely being decrypted successfully (this is not an SSL pinning problem) but it's not HTTP (or anything else closely related) so HTTP Toolkit can't intercept it. You'll struggle to use any similar HTTP proxy tool for this, and your tooling generally to modify/resend these kinds of requests will be limited. [Wireshark](http://wireshark.org/) may be useful though, since it can show the raw bytes without breaking the connection, so you can inspect the traffic, but that's quite complicated to set up for this kind of thing and you'll need to debug the raw traffic byte-by-byte for yourself.
> 
> I'm going to close this, since that's not a pinning problem and it's not HTTP traffic. If you do find a solution, please share it here so anybody else with the same problem can follow in your footsteps!

if it's not HTTP how when i don't use frida it shows the domains and that an HTTP happened but the certificate wasn't accepted i don't think it's none HTTP

**Comment by pimterry** [comment]
> if it's not HTTP how when i don't use frida it shows the domains and that an HTTP happened but the certificate wasn't accepted i don't think it's none HTTP

If it shows that the certificate wasn't accepted, then it's basically impossible to know whether it was HTTP or not - only that it uses TLS (HTTPS uses TLS, but so do lots of other protocols). The client doesn't send any actual request at all (or any other kind of data) until after it accepts the certificate of the server.

**Comment by Were-Logan-0110** [comment]
> > if it's not HTTP how when i don't use frida it shows the domains and that an HTTP happened but the certificate wasn't accepted i don't think it's none HTTP
> 
> If it shows that the certificate wasn't accepted, then it's basically impossible to know whether it was HTTP or not - only that it uses TLS (HTTPS uses TLS, but so do lots of other protocols). The client doesn't send any actual request at all (or any other kind of data) until after it accepts the certificate of the server.

is there maybe any info or anything i can try to send you something that may be the issue?

**Comment by Were-Logan-0110** [comment]
> > if it's not HTTP how when i don't use frida it shows the domains and that an HTTP happened but the certificate wasn't accepted i don't think it's none HTTP
> 
> If it shows that the certificate wasn't accepted, then it's basically impossible to know whether it was HTTP or not - only that it uses TLS (HTTPS uses TLS, but so do lots of other protocols). The client doesn't send any actual request at all (or any other kind of data) until after it accepts the certificate of the server.

Yes i think you were right it uses some kind of custom TLS maybe MQTT? idk tbh do you have any idea about smth to capture the TLS requests?
![image](https://github.com/user-attachments/assets/6cbe9551-cebf-489d-803b-32a1f22f5b74)
