### ISSUE TITLE
 httptoolkit pro patcher

### ISSUE THREAD

**Issue by 3052** [httptoolkit/httptoolkit#610]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

I just wanted to make aware that someone is cracking this software

https://github.com/XielQs/httptoolkit-pro-patcher

in case you want to take action against them

### How often does this bug happen?

Every time

### The desktop OS you're using

!

**Comment by pimterry** [comment]
Oooh, interesting, thanks! I'll close this issue but I'll keep an eye on that and see what I can do, thanks for the heads up.

**Comment by 3052** [comment]
FYI another one

https://github.com/ThatNotEasy/HTTPToolkit-Patcher

**Comment by SparkinPack1337** [comment]
Snitch.

**Comment by 3052** [comment]
LOL he is a nobody

https://github.com/SparkinPack1337?tab=repositories
