### ISSUE TITLE
it would be more worth if this can also intercept mqtt connection 

### ISSUE THREAD

**Issue by afandiazmi** [httptoolkit/httptoolkit#623]
it would be more worth if this can also intercept mqtt connection

**Comment by pimterry** [comment]
Thanks @afandiazmi. I'm going to close this as it's a duplicate of https://github.com/httptoolkit/httptoolkit/issues/254 but feel free to :+1: there to vote for this. Contributions towards implementing MQTT support are welcome, but do read the comments on that issue to understand what's involved first.
