### ISSUE TITLE
[Bug]: not intercepting from last update

### ISSUE THREAD

**Issue by msTokens** [httptoolkit/httptoolkit#627]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Hello, 

i changed nothing on my system, as the httptoolkit update came i cannot intercept any longer apps that worked yesterday the apps are patched to trust so i know for 100% that it has to do with httptoolkit im paying for this app i dont know what you change it but roll it BACK! or update your ca's.

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS

**Comment by xKiian** [comment]
Could you share what exactly you're doing? And maybe add some additional information? Logs/screenshots/what app etc.

And if nothing works you can manually roll it back since the repo is public.

**Comment by Jobians** [comment]
This application not showing all requests again and also takes minutes to open 😡

**Comment by pimterry** [comment]
I've moved that comment to a separate issue. I'm going to close this due to the lack of reply, but do get in touch @msTokens if you're still hitting issues here.
