### ISSUE TITLE
[Bug]: Syntax compatibility error

### ISSUE THREAD

**Issue by PeeraponChaipat** [httptoolkit/httptoolkit#630]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Open app

### How often does this bug happen?

Only once

### The desktop OS you're using

win 11

**Comment by PeeraponChaipat** [comment]
![image](https://github.com/user-attachments/assets/75654149-674b-4fd3-977a-89a7ef03d3a7)

By the way, I can use it now.

**Comment by pimterry** [comment]
Hmm, ok! I'm not sure what this could be I'm afraid, I haven't seen this before myself, or heard any other reports.

I'll leave this for now as it's resolved, but do let me know if it appears again. If so, please share a screenshot of the error and the HTTP Toolkit logs (available from Help -> View HTTP Toolkit Logs).

**Comment by IceBotYT** [comment]
I just got the error myself. Initially there was a pop up telling me that there was a significant compatibility error and I was significantly outdated. I clicked Ok, and I got this screen afterward

![image](https://github.com/user-attachments/assets/ffc714d4-9a21-41ec-be57-665cc6d16c13)

And the logs:

```
--- Launching HTTP Toolkit desktop v1.18.1 ---
INFO: Syntax error: [object ErrorEvent]
Config checked in 5 ms
Certificates setup in 9 ms
Standalone server started in 3 ms
Server started in 8 ms
Total startup took 25 ms
(node:8472) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR: Uncaught SyntaxError: Unexpected token '<'
```

**Comment by pimterry** [comment]
Hi @IceBotYT, thanks for reporting this. I think there was a brief blip in one of our service providers, resulting in some broken page loads due to errors, but that should all be resolved now. In general, if you or anybody else runs into this in future then reloading the page is the right way to go, but do let me know if this is happening so I can investigate further.

**Comment by 3052** [comment]
https://github.com/httptoolkit/httptoolkit/issues/641
