### ISSUE TITLE
Add An Option To Trust All Bad/Self-Signed CA Certs

### ISSUE THREAD

**Issue by RebelPat870** [httptoolkit/httptoolkit#640]
It would be really helpful if there was an option to whitelist all bad certifcates. I have the pro version and I iknow about the whiltelist but sometimes there are multiple certifcates that are bad from different hosts and It's a pain to have to look up each and every one and whilte list it only to go back and sudenly you get the same error and have to repeat the process when there should be a way to just turn the certificate checking off. I mean I understand it's about security and all but I'm not going to turn it off on a website that I don't trust httptoolkit is for testing so if I'm testing the certificates might not be correct but I"m not testing on some dangerous website where I have to worry about hackers if I was doing that then I would leave the certificate checking on. I tried the NODE_TLS_REJECT_UNAUTHORIZED=0 and it worked the first time I used it but it doesn't work anymore and I don't know why. If there's some way you could add a option to turn off certificate checking or tell me if there's a way to make NODE_TLS_REJECT_UNAUTHORIZED=0 or something. Finally, before anyone gets too critical I just wanted to let y'all know I didn't go to colllege an take programming or nothing like that everything I know is self-taught other than a little computer science in high school. So if I got anything wrong or if anything I said goes against some programmer rule I don't know about I appologize I'm doin the best I can but I'm still learning. Thank you.

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by RebelPat870** [comment]
Nevermind I found the option "ignoreHostHttpsErrors" in the code and was able to modify it to do what I was asking.

**Comment by pimterry** [comment]
Hi @RebelPat870 - glad you found a workaround for this. It's completely up to you, so if you're happy that's fine, but I would really recommend not disabling HTTPS validation entirely like this if you can avoid it.

When you disable this, it's not that you risk attack by individual dangerous sites - it's that you risk attack by anybody else _between_ you and the site. That means anybody else in your house/office, your internet service provider, and every other internet service provider (in many countries, this also means governments) in between you and the target server.  If you use this in an hotel or cafe wifi for example, anybody else in the hotel can potentially see every site you're talking to and inspect & modify all data you send or receive with HTTP Toolkit.

It's much better to either load additional CA certificates to trust (for sites using non-standard CAs - this will work across multiple sites, and avoids all broader security risks of disabling TLS) or to individually disable TLS just for sites in extreme cases when required.

**Comment by RebelPat870** [comment]
Thank you for the response. I appreciate it helps me understand a little better about the security thing I didn't know about all that. I'll be sure to try an only use it when neccessary then. Usually I stay off of wi-fi anyway and just use my phone as a hotspot cuz T-Mobile 's 5G is faster than wifi that should be safer too I mean I'm sure cell phone signals can be intercepted but it would take a lot more skill than hacking somebody on wifi right?

On Wed, 2024-09-25 at 02:51 -0700, Tim Perry wrote:

Hi @RebelPat870<https://github.com/RebelPat870> - glad you found a workaround for this. It's completely up to you, so if you're happy that's fine, but I would really recommend not disabling HTTPS validation entirely like this if you can avoid it.

When you disable this, it's not that you risk attack by individual dangerous sites - it's that you risk attack by anybody else between you and the site. That means anybody else in your house/office, your internet service provider, and every other internet service provider (in many countries, this also means governments) in between you and the target server. If you use this in an hotel or cafe wifi for example, anybody else in the hotel can potentially see every site you're talking to and inspect & modify all data you send or receive with HTTP Toolkit.

It's much better to either load additional CA certificates to trust (for sites using non-standard CAs - this will work across multiple sites, and avoids all broader security risks of disabling TLS) or to individually disable TLS just for sites in extreme cases when required.

**Comment by pimterry** [comment]
> Usually I stay off of wi-fi anyway and just use my phone as a hotspot cuz T-Mobile 's 5G is faster than wifi that should be safer too I mean I'm sure cell phone signals can be intercepted but it would take a lot more skill than hacking somebody on wifi right?

On mobile, I think you can assume that people around you cannot intercept the traffic just from the mobile radio signal, but your TLS traffic can still be intercepted on the internet itself, e.g. by your mobile carrier (so T-Mobile could see or modify any detail of anything you're doing) and then by everybody upstream of them (T-Mobile will pass the traffic through a couple of other providers within your country, and then your traffic will pass through various connections across the world, and then through the target server's internet provider chain, until it reaches the target server itself - anyone on that path could intercept this).
