### ISSUE TITLE
View -> Send

### ISSUE THREAD

**Issue by TonyValenti** [httptoolkit/httptoolkit#643]
I do a lot of work in Fiddler classic and am looking for a more modern alternative.  I really like HTTP Toolkit but one scenario makes it a lot harder for us to use than Fiddler.

Specifically, here is what I want to be able to do:
Inside the "Intercept" tab, I need to be able to right-click on a request and have a "Send to Send" menu item that will create a tab in the "Send" section that is prepopulated with all the values from the request.  This way I can tweak the request in the Send tab and experiment with different values and options.

**Comment by xKiian** [comment]
I'm pretty sure that's a thing already. If you select your request you can click on the bottom right on the send icon

**Comment by xKiian** [comment]
Oh I just noticed it's a pro feature, but it would be there

**Comment by TonyValenti** [comment]
Is there a way for me to trial pro?
By the way - I'm a huge fan of discoverable features.  It would be great if, instead of hiding whatever button, it was either disabled, or, you could only use it 1-2 times per session unless you were on pro.  That way people will at least know the feature is there and be able to get a sample of it.

**Comment by pimterry** [comment]
Hi @TonyValenti, there's no Pro trials, but it's easy to subscribe cheaply for just 1 month & cancel immediately, so you can test it out with no risk of accidental renewal or anything. See https://httptoolkit.com/docs/faq/payments/ for more details.

Regarding discoverability, thanks for the feedback, I will take a look at this. Right now, the button isn't hidden, but it is shown as disabled - it's the grey Send icon (the arrow) in the bottom right, to the right of "With Pro:". You can also access this same functionality by right clicking any row, where you'll also see "Resend request" as option there too (also disabled, without Pro). You can hover over any icons anywhere for a tooltip that explains what they do (if you find anywhere that that's not the case, let me know and I'll fix it).

If you haven't looked at these icons already, you might also be interested to know that Pro has a similar Create Modify Rule function too (in both locations) which allows you to convert intercepted traffic in a modification rule that matches future requests and returns the response statically (making it easy to mock directly, or manually customize behaviour from there). If you want to know about other features, both these are also listed on the pricing page: https://httptoolkit.com/pricing/

I'm doing an update to the docs soon, so I'll try to include this there more explicitly. For now I'm going to close this issue though, as the requested functionality does indeed exist (thanks @xKiian!)
