### ISSUE TITLE
Custom port for frida-server android

### ISSUE THREAD

**Issue by lugondev** [httptoolkit/httptoolkit#648]
Currently, HttpToolkit only supports the default port on Android and only operates when I run ./frida-server. 
I would like to request support for a custom port, such as 19999, so that I can run ./frida-server -l 0.0.0.0:19999.

Thanks

**Comment by pimterry** [comment]
Hmm, can you explain why this is useful? Currently HTTP Toolkit uses its own port (24072) just to make Frida detection mildly more difficult.

The way the Frida integration works at the moment is that it uses an existing Frida server if one exists on either the default (27042) or custom (24072) ports. If not, then it checks if HTTP Toolkit's version of Frida is installed. If not it offers to install it, and then launch it listening on that custom port.

That should mean that you can run your own Frida server on another different port for your own purposes, and HTTP Toolkit will just ignore it and launch its separate server on 24072 and use that, so everything should work without any special setup required. Can you explain more about your use case, and why that's not working for you?

**Comment by lugondev** [comment]
Oh, thanks for your reply! I will try using custom (24072) ports.
I haven't found any docs related port custom so I created this issue.
