### ISSUE TITLE
I want to shift select multiple urls on the view page and delete them at once. 

### ISSUE THREAD

**Issue by SrikanthKumarC** [httptoolkit/httptoolkit#650]
Basically the title. I would like to have a feature on the view page that allows users to select multiple URLs at once, and then delete/copy/save/etc them all in a single action.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Thanks @SrikanthKumarC! I think this is the same issue as #76 is that right? I'm going to close this as a duplicate, but do put a :+1: there to vote for that, and share any specific details of how this should work that are missing from the discussion there in a comment.
