### ISSUE TITLE
Have more than one mock response thing for an matched url etc

### ISSUE THREAD

**Issue by nutterthanos** [httptoolkit/httptoolkit#652]
![image](https://github.com/user-attachments/assets/0c3b07f8-bb48-4f21-a623-9eb53d8d9179)

in this im finding i can only pick one option but as an example what ones i should be able to multiplely select like forward to an different host and an new option that essentially changes url too and not just an different host and to also to mock the request/response headers, body etc

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Some of what you're looking for may be available in the 'Transform' rule, which lets you do multiple transforms on the same exchange.

For the broader concept, this is covered by https://github.com/httptoolkit/httptoolkit/issues/446, so I'll close this issue. I've added a link to this in the description there.

With that in place, you'd be able to add multiple steps to each rule, with only some rules (like 'Close the connection') ending the chain. In this case, you could add a rule like:

* Forward to host X
* Transform headers + body

This will also allow things like 'Delay 100ms, then...' and 'Save request to a HAR file, then ...'

You can see an existing UI for this if you try creating a WebRTC rule, which already supports steps exactly like this. It's not especially difficult to extend this I think (PRs welcome! First steps are within Mockttp) but there's a lot going on and it's not top of the todo list yet.

**Comment by nutterthanos** [comment]
> With that in place, you'd be able to add multiple steps to each rule, with only some rules (like 'Close the connection') ending the chain. In this case, you could add a rule like:
> 
> * Forward to host X
> * Transform headers + body
> 
> This will also allow things like 'Delay 100ms, then...' and 'Save request to a HAR file, then ...'

thats exactly what i was requesting didn't even realising #446 existed because for one i didn't bother looking and 2 maybe assumes the title for said request wasn't for exactly what i was requesting
