### ISSUE TITLE
[Bug]: Cant Open HTTP Toolkit

### ISSUE THREAD

**Issue by Yotsubal** [httptoolkit/httptoolkit#654]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Opening the App only spawn the process, but the UI is not shown, and https://app.httptoolkit.tech is unavailable to access 

Im trying to do:
```
Open https://app.httptoolkit.tech in Chrome, Edge, Brave or Firefox:
This is the hosted version of the latest HTTP Toolkit UI
```

### How often does this bug happen?

Sometimes

### The desktop OS you're using

Win 11

**Comment by Yotsubal** [comment]
https://app.httptoolkit.tech  returning 204 No Content

**Comment by pimterry** [comment]
I think this might have been caused by a brief infrastructure issue that's now been resolved. Is it working for you if you try again now?

If not, can you open the browser developer tools before you open the UI, try to load the page, and then export a HAR of the traffic that was sent & received?
