### ISSUE TITLE
[Bug]: /docs/reference/amiusing.httptoolkit.tech.txt doesn't exist

### ISSUE THREAD

**Issue by xKiian** [httptoolkit/httptoolkit#659]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

go to https://httptoolkit.com/docs/
on the left click on "Reference" and then "AmIUsing Test Site"
get a 404

### How often does this bug happen?

Every time

### The desktop OS you're using

firefox but doesnt really matter

### Any other info?

small bug but why not report it 🤷

**Comment by pimterry** [comment]
Huh, that's very weird. Correct URL is https://httptoolkit.com/docs/reference/amiusing.httptoolkit.tech/.

No idea where that `.txt` is coming from, the new website has some quirks that still need ironing out, thanks for reporting this! Will update once that's fixed.

**Comment by pimterry** [comment]
Now fixed! Thanks for reporting this
