### ISSUE TITLE
[Bug]: can i talk about a bug privately

### ISSUE THREAD

**Issue by elproricardo123** [httptoolkit/httptoolkit#660]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

it is just i think they will check the issues of http toolkit so to keep it a little bit more private

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

**Comment by pimterry** [comment]
Sure - send an email to help @ httptoolkit.com
