### ISSUE TITLE
ONTERFACE  ABLE TO HCUSTOMIZE

### ISSUE THREAD

**Issue by lulzactive** [httptoolkit/httptoolkit#668]
---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by lulzactive** [comment]
Sorry.... more options to change the GUI... mas pay u need.

**Comment by pimterry** [comment]
Hi @lulzactive, that's still not very clear. It sounds like you want to reconfigure the UI somehow? But I don't know which bits, or why, or what you're trying to do.

Can you explain what you're trying to do, what you want to reconfigure, and how it will help you? It's very hard to build anything without _much_ more information about what you actually want.

For example, at least this much information:

> I am working for ... building .... using these technologies ...
> My job right now is ..., and that means I need to .... Currently that's difficult in HTTP Toolkit because .... It would be easier if there was a way to .... I would use this by: reconfiguring the UI to show ... then comparing that to ... and this would make it easier to ...

Without a detailed understanding of what you're doing and why, there's nothing I can do.
