### ISSUE TITLE
Add support for launching an existing fish shell

### ISSUE THREAD

**Issue by ElijahLynn** [httptoolkit/httptoolkit#67]
To add support for launching an existing fish shell, two changes needed:

1. the example command should be `source (curl -sS localhost:8001/setup | psub )` see https://github.com/fish-shell/fish-shell/issues/1786#issuecomment-592922090

2. The setup script should be:

```
export http_proxy="http://127.0.0.1:8000"
# ...

if command -v winpty >/dev/null 2>&1
    # Work around for winpty's hijacking of certain commands
    alias php=php
    alias node=node
end

echo 'HTTP Toolkit interception enabled'
```

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
It's taken a while, but this is now available :slightly_smiling_face:. The 'Existing Terminal' button has a new dropdown to support multiple shells, and Fish is one of the options supported there. Enjoy!

![Screenshot from 2022-05-12 20-48-18](https://user-images.githubusercontent.com/1526883/168147160-98102ca6-7612-4099-a6ba-eff67d901d3d.png)
