### ISSUE TITLE
Is it possible to use the API without opening HTTPtoolkit

### ISSUE THREAD

**Issue by Truewaydm** [httptoolkit/httptoolkit#676]
When making a request, I want to connect to an application on an android emulator, but I get the following error
The httptoolkit-server project is running, but the application or web version (https://app.httptoolkit.tech) is not.

Request:
`curl --location 'http://127.0.0.1:45457/interceptors/android-adb/activate/8000' \
--header 'Origin: https://app.httptoolkit.tech' \
--header 'Content-Type: application/json' \
--data '{
    "deviceId": "localhost:5588"
}'`
Response:
`{
    "result": {
        "success": true
    }
}`

Emulator
![2024-12-17_18-35](https://github.com/user-attachments/assets/23cac037-c49d-4856-aef0-3ff7116b7b38)

`curl --location 'http://127.0.0.1:45457/interceptors?proxyPort=8000' \
--header 'Origin: https://app.httptoolkit.tech'`

Response:
`{
    "interceptors": [
        {
            "id": "android-adb",
            "version": "1.0.0",
            "metadata": {
                "deviceIds": [
                    "localhost:5588"
                ],
                "devices": {
                    "localhost:5588": {
                        "id": "localhost:5588",
                        "name": "sdk_gphone64_x86_64"
                    }
                }
            },
            "isActivable": true,
            "isActive": false
        },
        {
            "id": "android-frida",
            "version": "1.0.0",
            "metadata": {
                "hosts": {
                    "localhost:5588": {
                        "id": "localhost:5588",
                        "name": "sdk_gphone64_x86_64",
                        "type": "android",
                        "state": "setup-required"
                    }
                }
            },
            "isActivable": true,
            "isActive": false
        },
    ]
}`

**Comment by pimterry** [comment]
> Is it possible to use the API without opening HTTPtoolkit

Hi! The short answer is no.

Obviously you're welcome to poke around at the internal API if you like, but it's not officially supported, it may change any time, the API isn't designed for 3rd party use (so you'll find all sorts of weird behaviours & restrictions) and there's no support available for this.

To be honest, if you want to do something similar to what HTTP Toolkit is doing for automated setup headlessly, your best bet is to dig into the source for yourself, and use the code and the various published subpackages directly. It's all open source and there are many components you can reuse for yourself to fit the needs of whatever you're building.

**Comment by Truewaydm** [comment]
I have question about more devices to connect httptoolkit

For example response:
`{
            "id": "android-adb",
            "version": "1.0.0",
            "metadata": {
                "deviceIds": [
                    "localhost:5588"
                ],
                "devices": {
                    "localhost:5588": {
                        "id": "localhost:5588",
                        "name": "sdk_gphone64_x86_64"
                    }
                }
            },
            "isActivable": true,
            "isActive": false
        },`
        
 If I need connect 2 or more android devices, I can activate (http://127.0.0.1:45457/interceptors/android-adb/activate/8000) not only 1 device?
