### ISSUE TITLE
Forward to other Proxy (Pro Feature)

### ISSUE THREAD

**Issue by emlinhax** [httptoolkit/httptoolkit#678]
I would love to be able to forward all proxy traffic to yet another proxy like BURP Suite.
Since this would be used to bypass the Pro Restrictions, might aswell make it a Pro-only feature.

Burp Suite is best for bug bounty hunting but HTTP Toolkit has the better Android Integrations (ADB etc).

**Comment by pimterry** [comment]
You'll be pleased to know that this does already exist as a Pro feature! It's an option on the Settings page that appears for Pro users. I'll close this as already completed.

See the list at the bottom of https://httptoolkit.com/pricing/ for the full list of Pro features available.

> Burp Suite is best for bug bounty hunting

Can you be more specific about the features you find useful? I'm definitely interested in expanding HTTP Toolkit to cover more of this use case.
