### ISSUE TITLE
check http douyin app 

### ISSUE THREAD

**Issue by sonrasa2k** [httptoolkit/httptoolkit#681]
douyin app not internet when i turn on httptoolkit

**Comment by pimterry** [comment]
Hi @sonrasa2k. This probably means there is some kind of certificate pinning or interception detection in this app. You may have more success if you try to use the 'Frida' interception option, which can disable many of these protections. Alternatively, you will need to reverse engineer this yourself. I'm afraid I can't help with investigating individual apps like this, but I've written a guide here: https://httptoolkit.com/blog/android-reverse-engineering/
