### ISSUE TITLE
Right Click request in list to "create a mock rule from this request"

### ISSUE THREAD

**Issue by ElijahLynn** [httptoolkit/httptoolkit#69]
Feature request to be able to also right click on a request from the list to "create a mock rule from this request". 

Thanks

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
This is now live! Pro users can now make a rule directly from the context menu.

The new context menu here is HTML-based by default, in all current versions and on the web, but from the next desktop release, the same UI will automatically use native context menus everywhere.
