### ISSUE TITLE
Automatic interception for IE

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#7]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by daluu** [comment]
Or do we mean Edge browser now? The Chromium based one and/or the non-Chromium based one. Not sure IE itself has much relevance now that IE and Windows 7 and older OSes are deprecated. So Windows 8 maybe and Windows 10, and Windows 10 is more about Edge browser I believe.

**Comment by pimterry** [comment]
This was originally referring to IE. I think you'd be sadly surprised to this day about the number of old enterprises and government offices that use IE internally! But it's certainly not widespread, and it did turn out to be very impractical - there's no way to intercept IE separate from the rest of the system.

I think this would be better covered by #8 in the few cases where it matters, so I'll close it for now.
