### ISSUE TITLE
Protocol buffer (protobuf) decoding

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#80]
HTTP Toolkit could decode and show protocol buffer data more clearly.

By default, with no info, they could be [partially decoded](https://stackoverflow.com/questions/7343867/raw-decoder-for-protobufs-format) into basic data structures.

Given a schema though (either manually configured or referenced somehow by the message, e.g. the `messageType` param in the content type) we could easily decode the whole thing completely.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by daluu** [comment]
What did you have in mind with respect to the manual configuration?

**Comment by pimterry** [comment]
Somehow, HTTP Toolkit needs to get the schema for the protobuf messages to be able to fully parse them. 

It seems like in some cases some details could be in the content-type header, but that's not frequently used. Given that, there's usually nothing in the message or its headers that tells us where to find the schema we need for detailed parsing, so you'd need to manually provide it somehow. I'm not an expert on protobuf though, so I'd love to hear if that's wrong!

To actually configure it, the details are TBC: maybe you configure "for URL X use schema Y" in the settings, maybe there's a button next to the body to pick a schema, or maybe you just provide a set of schemas and we test every protobuf message against all of them.

**Comment by Jhartulion** [comment]
It is correct that you need the .proto file for a detailed decoding but you could think about a basic decoding which also works 
without the .proto file.
Their are some apis available doing that decode or some websites that actually offer that:
https://protogen.marcgravell.com/decode 
Testdata if you have none
`0a 40 0a 20 74 79 70 65 2e 67 6f 6f 67 6c 65 61 70 69 73 2e 63 6f 6d 2f 4c 6f 63 61 52 65 73 70 6f 6e 73 65 12 1c 0a 05 65 6e 5f 44 4b 12 0c 59 34 31 51 2b 65 48 4f 61 76 58 44 22 05 76 31 5f 32 37`

Here is some java code i am currently using for decoding proto when i don't have the proto file available:
`	private static String decodeProtoInput(CodedInputStream input, int depth, boolean singleLine) throws IOException {
		StringBuilder s = new StringBuilder("{ ");
		boolean foundFields = false;
		while (true) {
			final int tag = input.readTag();
			int type = WireFormat.getTagWireType(tag);
			if (tag == 0 || type == WireFormat.WIRETYPE_END_GROUP) {
				break;
			}
			foundFields = true;
			protoNewline(depth, s, singleLine);

			final int number = WireFormat.getTagFieldNumber(tag);
			s.append(number).append(": ");

			switch (type) {
			case WireFormat.WIRETYPE_VARINT:
				s.append(input.readInt64());
				break;
			case WireFormat.WIRETYPE_FIXED64:
				s.append(Double.longBitsToDouble(input.readFixed64()));
				break;
			case WireFormat.WIRETYPE_LENGTH_DELIMITED:
				com.google.protobuf.ByteString data = input.readBytes();
				try {
					String submessage = decodeProto(data, depth + 1, singleLine);
					if (data.size() < 30) {
						boolean probablyString = true;
						String str = new String(data.toByteArray(), Charsets.UTF_8);
						for (char c : str.toCharArray()) {
							if (c < '\n') {
								probablyString = false;
								break;
							}
						}
						if (probablyString) {
							s.append("\"").append(str).append("\" ");
						}
					}
					s.append(submessage);
				} catch (IOException e) {
					s.append('"').append(new String(data.toByteArray())).append('"');
				}
				break;
			case WireFormat.WIRETYPE_START_GROUP:
				s.append(decodeProtoInput(input, depth + 1, singleLine));
				break;
			case WireFormat.WIRETYPE_FIXED32:
				s.append(Float.intBitsToFloat(input.readFixed32()));
				break;
			default:
				throw new InvalidProtocolBufferException("Invalid wire type");
			}

		}
		if (foundFields) {
			protoNewline(depth - 1, s, singleLine);
		}
		return s.append('}').toString();
	}`

**Comment by konsumer** [comment]
I wrote a [js library](https://github.com/konsumer/rawproto) that can show a reasonable representation of arbitrary protobuf, and even try to guess the proto definition.

**Comment by pimterry** [comment]
Very cool, thanks @konsumer! This is exactly the kind of thing I was imagining.

I'm definitely interested in doing this, although there's a lot going on and it's not really top of my list quite yet. If you or anybody else wants to take a shot at a PR to add this in the meantime though, be my guest! Happy to share pointers and answer questions on that here - just shout if you're interested.

**Comment by konsumer** [comment]
I am knee-deep in some heavy projects right now, so it will probably be a bit before I have time to work on it.

If you want to quickly try it out:

```
npx -y rawproto@latest -j -f f < YOURPROTOSCRAPE.bin | npx -y flat
```

I recently added a `-f` flag, that is a field-name prefix, and can make it easier to find stuff with json-path (the fields are strings, numbers are for arrays.)

**Comment by pimterry** [comment]
:tada: Automatic protobuf decoding is now available:

![Screenshot from 2024-03-06 13-39-57](https://github.com/httptoolkit/httptoolkit/assets/1526883/0b427996-0111-4728-9305-a37a1eb38e84)

This is selected by default for all HTTP or websocket messages that explicitly contain protobuf data (in their content-type header or subprotocol respectively) and is available in the dropdown (but not selected automatically) for all other content that appears to be protobuf even if it's not explicitly marked as such.

This is just a first step; it doesn't yet have an option to load your own schemas, and it doesn't give you a mechanism to edit protobuf content (by breakpoint or in rules) but it can do automatic raw decoding of content regardless (powered by @konsumer's excellent [rawprotoparse](https://www.npmjs.com/package/rawprotoparse) library) which is perfect for most reverse engineering use cases.

I'll close this now since this is the most important step, but I've opened new issues for the other possible extensions:

* #559
* #560
* #561

If you're interested in any of those, you can add a :+1: to those issues to vote for them, and/or subscribe to the issues via GitHub for notifications once that's available.

**Comment by konsumer** [comment]
@pimterry I just published a new version that lets you specify a "value callback" which is useful for the field could be several possible things (we were sometimes losing a string that would miraculously parse as a sub-message.) Here is an example form our test-code, that has a known-location for the aforementioned string:

```js
import rawprotoparse, { getVal } from 'rawprotoparse'

it('should find weird title-field', () => {
  const d = new TextDecoder()
  let title
  let count = 0
  const customFieldHandler = (data, wireType, ...args) => {
    if (wireType === 2) {
      count++
      if (!title && count === 6) {
        title = d.decode(data)
      }
    }

    // do default original thing
    return getVal(data, wireType, ...args)
  }

  const r = rawprotoparse(pb, 'f', 'auto', false, customFieldHandler)
  console.log(title)
})
```

I could imagine filling an array with "possible values are..." for even nicer display, based on `wireType`.

**Comment by pimterry** [comment]
Neat, thanks @konsumer! I've filed another protobuf sub-issue, as you're right that there's a good possible extension there: https://github.com/httptoolkit/httptoolkit/issues/562.

I have a few other bits to discuss about rawproto etc, but I'll open issues on those repos to discuss that directly rather than continuing here.

**Comment by emrovsky** [comment]
How can we return this decoded data to the protobuff schema?

**Comment by konsumer** [comment]
@emrovsky using the wire format requires basically guessing the schema. Pretty much every type could be several different types in schema and there is no way to get the field-name. I made [this tool](https://github.com/konsumer/rawproto) to try to guess, but you will get something like this (which you can hand-tune into the correct types/field-names/etc):

```proto
syntax = "proto3";

message MessageRoot {
  bytes field1 = 1; // could be a repeated-value, string, bytes, or malformed sub-message
  int32 field2 = 2; // could be a int32, int64, uint32, bool, enum, etc, or even a float of some kind
  string field3 = 3; // could be a repeated-value, string, bytes, or malformed sub-message

  message Message4 {
    int32 field1 = 1; // could be a int32, int64, uint32, bool, enum, etc, or even a float of some kind
    string field2 = 2; // could be a repeated-value, string, bytes, or malformed sub-message

    message Message3 {
      int32 field1 = 1; // could be a int32, int64, uint32, bool, enum, etc, or even a float of some kind
    }
    
    Message3 subMessage3 = 3;
  }
  
  repeated Message4 subMessage4 = 4;
  string field5 = 5; // could be a repeated-value, string, bytes, or malformed sub-message
}
```
