### ISSUE TITLE
Auto scroll view window as requests comes in.

### ISSUE THREAD

**Issue by Nightfright** [httptoolkit/httptoolkit#81]
Really good tool!

I would love a toggle under the view window that enables auto scroll of the view window as new request comes in.
(Like in Android studio logcat/run windows you press that and it always scroll as new lines comes until you manually scroll the window or press the toggle again)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Yes! Great suggestion. Shouldn't be too difficult I think either, I'll try to find some time to look into it soon.

Would you want it to be a toggle button? I think I've seen behaviour elsewhere where tools follow the logs if you're currently at the bottom or if you scroll down to the bottom, and unsticks if you scroll up (i.e. it behaves like the bottom is sticky). I don't know if that kind of behaviour would be more natural, or more confusing & implicit. Any thoughts?

In the meantime, if you or anybody else feels passionately about this, you're welcome to dive into to add it yourself right away. That list is rendered [here](https://github.com/httptoolkit/httptoolkit-ui/blob/master/src/components/view/view-event-list.tsx#L435-L447), and all contributors to the open source projects get [free HTTP Toolkit Pro](https://httptoolkit.tech/blog/free-as-in-beer#new-decade-resolutions).

**Comment by Nightfright** [comment]
Only thing is if you need to scroll down to bottom for it to stick again you might either have to clear the window or scroll pages and pages before hitting bottom again and make it stick. But if you have a "toggle" you could just press that to activate it again (auto jump to bottom and keep scrolling as new comes in when toggle is on, and if you scroll up or click the toggle again it would deactivate).

Just some thoughts about it. Might not be a problem either way. Just having ability for it in any way would be nice :)

**Comment by pimterry** [comment]
I put up a quick [twitter poll](https://twitter.com/HttpToolkit/status/1279005256232435725) to try and get some wider opinions on it :smile:. I've now done a little research too:

* The "follow if you're at the bottom" approach is what both Firefox & Chrome do in their network tab.
* Charles seems to _always_ follow requests, regardless, with no toggle that I can find?
* Android Studio does both - the logs are followed if you scroll to the bottom, but there's also a button to jump to the bottom and start following (which toggles itself if you scroll manually).

I'll wait and see what the poll says, but I think I'm still leaning towards sticky follow first, unless the wider world clearly disagrees. It'd still be possible to add a button later though, and do it like Android Studio, if sticky following isn't good in practice.

**Comment by pimterry** [comment]
Now implemented! It's a simple sticky follow for now - if you're ever scrolled to the end of the list, and a new event comes in, the UI will scroll down to include it. If you're not scrolled to the end of the list, everything behaves like normal.

There isn't a UI button to jump to the end of the list to do this, but when the list is focused you can now use Home/End on the keyboard to select & scroll to the first/last row, which lets you jump into this directly from the keyboard.
