### ISSUE TITLE
Cant view some requests on custom ports.

### ISSUE THREAD

**Issue by Urahara** [httptoolkit/httptoolkit#86]
Hi!

First thank you for this awesome app! Is helping me alot, my doubt is that some requests is not logged on **View** tabs, _example_:  A third-party app make request to the address: `https://example.com:81` (SSL on 81 port) and `http://example.com:8081` but none of them is logged.

I also use [HttpCanary](https://github.com/MegatronKing/HttpCanary) for analysis, and he can capture that request. I also read [here](https://httptoolkit.tech/docs/guides/android#the-android-app) that the ports that **HTTP Toolkit** support are:

- 80
- 443
- 8000
- 8001
- 8080
- 8888
- 9000

Is there any sort of config that i can expand this list to fit my need like i described above?

The device that i using to test is a rooted **Moto Z** (Magisk) with **LineageOS 16**, i also use [AlwaysTrustUserCerts](https://github.com/NVISO-BE/MagiskTrustUserCerts) module to treat my user certificates as Root certificate.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
That makes sense. Right now it's not configurable, but I do agree that that would be valuable.

The challenge is making sure other network traffic remains unaffected. HttpCanary will presumably be doing this by collecting all traffic and sniffing the first couple of bytes to work out the protocol, but that has various complicated reliability/performance downsides. I might look into it more if this is a long-term issue though.

Right now, I think there's two options for you:

* You can upgrade to Android 10 (so LineageOS 17), so the VPN's [HTTP proxy setting](https://developer.android.com/reference/android/net/VpnService.Builder#setHttpProxy(android.net.ProxyInfo)) is used by default. That should collect traffic on any port automatically.
* You can download the [Android app source](https://github.com/httptoolkit/httptoolkit-android/), manually edit the [list of ports](https://github.com/httptoolkit/httptoolkit-android/blob/1c72175f91d9867e085fbf7b6dbe5273fbdffe48/app/src/main/java/tech/httptoolkit/android/ProxyVpnService.kt#L197-L201), rebuild it and install that manually. Once you have any build of the mobile app installed the desktop app will work with it no problem, so you can then use that just like normal.

Does one of those options work for you?

**Comment by Urahara** [comment]
I will try build apk on my local machine and them i give you a feedback, thanks!

**Comment by pimterry** [comment]
Great! Glad to hear that's sorted you out.

Let's leave this issue open for now, it would be good to know if there are other users hitting this issue, so I know whether to prioritize building a UI for this.
